In [1]:
import polars as pl

def classify_cancer_samples(df: pl.DataFrame) -> pl.DataFrame:
    """
    Classify samples as cancer / non-cancer / uncertain based on metadata text patterns.
    Returns the same DataFrame with added classification columns.
    """

    # --- Step 1: Setup ---
    PRIORITY_COLS = ["source_name", "tissue", "phenotype", "disease", "cell_type", "tumor_type"]
    PRIORITY_COLS = [c for c in PRIORITY_COLS if c in df.columns]

    # Regex patterns
    CANCER_POS = r"(?:\bcancers?\b|\btumou?rs?\b|\bmalignan(?:t|cy)\b|\bcarcinomas?\b|\bneoplasms?\b|\bmetasta(?:s|t)es?\b|\badenocarcinomas?\b|\bsarcomas?\b|\bleukemi(?:a|as)\b|\blymphom(?:a|as)\b|\bglioblastomas?\b|\bmelanomas?\b|\boncolog(?:y|ic|ical)\b)"
    CANCER_NEG = r"(?:\bnormal\b|\bhealthy\b|\bctrl\b|\badjacent normal\b|\bnon[-\s]?tumou?r(?:al)?\b|\bbenign\b|\bnon[-\s]?cancer(?:ous)?\b|\bsham\b|\bunaffected\b)"
    ONCO_TRAPS = r"(?:\boncophora\b|\boncorhynchus\b|\boncotic\b|\boncomodulin\b)"

    # Helper to normalize text columns
    def normalize_text(col_expr):
        return (
            col_expr.cast(pl.Utf8)
            .fill_null("")
            .str.to_lowercase()
            .str.replace_all(r"[_/|]", " ")
            .str.replace_all(r"\s+", " ")
            .str.strip_chars()
        )

    # --- Step 2: Sample name detection ---
    sample_name_col = "title" if "title" in df.columns else "biosample"

    df = df.with_columns([
        normalize_text(pl.col(sample_name_col)).str.contains(CANCER_POS).alias("cancer_in_sample_name"),
        normalize_text(pl.col(sample_name_col)).str.contains(CANCER_NEG).alias("negative_in_sample_name"),
        normalize_text(pl.col(sample_name_col)).str.contains(ONCO_TRAPS).alias("onco_trap_in_sample_name"),
    ])

    # --- Step 3: Check priority columns ---
    for col in PRIORITY_COLS:
        df = df.with_columns([
            normalize_text(pl.col(col)).str.contains(CANCER_POS).alias(f"cancer_in_{col}"),
            normalize_text(pl.col(col)).str.contains(CANCER_NEG).alias(f"negative_in_{col}"),
        ])

    # --- Step 4: Count mentions ---
    cancer_mention_cols = [f"cancer_in_{c}" for c in PRIORITY_COLS]
    negative_mention_cols = [f"negative_in_{c}" for c in PRIORITY_COLS]

    df = df.with_columns([
        pl.sum_horizontal([pl.col(c) for c in cancer_mention_cols if c in df.columns]).alias("n_cancer_mentions"),
        pl.sum_horizontal([pl.col(c) for c in negative_mention_cols if c in df.columns]).alias("n_negative_mentions"),
    ])

    # --- Step 5: Confidence category ---
    df = df.with_columns([
        pl.when(pl.col("onco_trap_in_sample_name"))
        .then(pl.lit("uncertain_onco_trap"))
        .when(
            pl.col("cancer_in_sample_name") &
            (pl.col("n_cancer_mentions") >= 1) &
            (pl.col("n_negative_mentions") == 0)
        )
        .then(pl.lit("confident_cancer"))
        .when(
            (pl.col("cancer_in_sample_name") & (pl.col("n_negative_mentions") == 0)) |
            (pl.col("n_cancer_mentions") >= 2)
        )
        .then(pl.lit("likely_cancer"))
        .when(
            pl.col("negative_in_sample_name") |
            (pl.col("n_negative_mentions") >= 1)
        )
        .then(pl.lit("likely_non_cancer"))
        .when(pl.col("n_cancer_mentions") == 1)
        .then(pl.lit("uncertain_weak_signal"))
        .otherwise(pl.lit("uncertain_no_signal"))
        .alias("confidence_category")
    ])

    return df

In [2]:
full_dataset = pl.read_csv(
    "data/combined_metadata_noncancer_removed.csv",
    schema_overrides={"group": pl.Utf8},   # <- dict of {col_name: dtype}
    infer_schema_length=0,                  # scan entire file for other cols
)

df = pl.read_csv("data/train_test.csv")

In [3]:
df = df[["experiment_accession", "bioproject", "biosample", "sample_accession","run_accession", "is_cancer"]]

# idx = full_dataset.columns.index("cancer_type")

# full_dataset = full_dataset[full_dataset.columns[:idx+1]]

In [4]:
df.head()

# full_dataset.head()

shape: (5, 6)
┌──────────────────────┬─────────────┬──────────────┬──────────────────┬───────────────┬───────────┐
│ experiment_accession ┆ bioproject  ┆ biosample    ┆ sample_accession ┆ run_accession ┆ is_cancer │
│ ---                  ┆ ---         ┆ ---          ┆ ---              ┆ ---           ┆ ---       │
│ str                  ┆ str         ┆ str          ┆ str              ┆ str           ┆ i64       │
╞══════════════════════╪═════════════╪══════════════╪══════════════════╪═══════════════╪═══════════╡
│ SRX10489019          ┆ PRJNA718814 ┆ GSM5220969   ┆ SRS8615268       ┆ SRR14118670   ┆ 1         │
│ ERX1283444           ┆ PRJEB6455   ┆ SAMEA3724868 ┆ ERS1032017       ┆ ERR1211193    ┆ 0         │
│ SRX17708205          ┆ PRJNA884362 ┆ GSM6601021   ┆ SRS15238722      ┆ SRR21710838   ┆ 1         │
│ SRX4518392           ┆ PRJNA484951 ┆ GSM3323504   ┆ SRS3636903       ┆ SRR7655999    ┆ 0         │
│ SRX9364181           ┆ PRJNA671877 ┆ GSM4860401   ┆ SRS7586602       ┆ SRR12899131   ┆ 0         │
└──────────────────────┴─────────────┴──────────────┴──────────────────┴───────────────┴───────────┘

In [5]:
joined = full_dataset.join(
    df,
    on=["experiment_accession", "bioproject", "biosample", "sample_accession", "run_accession"],  # matching keys
    how="inner"  # keep only matching rows
)

In [6]:
predicted_df = classify_cancer_samples(joined)

In [7]:
# find the position of "cancer_type"
idx = predicted_df.columns.index("cancer_type")

# slice up to that column (inclusive)
cols_to_keep = predicted_df.columns[:idx + 1]

# add the two specific extra columns
cols_to_keep += ["is_cancer", "confidence_category"]

predicted_df.select(cols_to_keep)

shape: (172, 40)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ experimen ┆ experimen ┆ title     ┆ study_nam ┆ … ┆ n_count  ┆ cancer_ty ┆ is_cancer ┆ confidenc │
│ t_alias   ┆ t_accessi ┆ ---       ┆ e         ┆   ┆ ---      ┆ pe        ┆ ---       ┆ e_categor │
│ ---       ┆ on        ┆ str       ┆ ---       ┆   ┆ str      ┆ ---       ┆ i64       ┆ y         │
│ str       ┆ ---       ┆           ┆ str       ┆   ┆          ┆ str       ┆           ┆ ---       │
│           ┆ str       ┆           ┆           ┆   ┆          ┆           ┆           ┆ str       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ ena-EXPER ┆ ERX352605 ┆ Illumina  ┆ null      ┆ … ┆ 2525599  ┆ carcinoma ┆ 0         ┆ likely_no │
│ IMENT-FUN ┆ 7         ┆ HiSeq     ┆           ┆   ┆          ┆           ┆           ┆ n_cancer  │
│ CTIONAL   ┆           ┆ 2500      ┆           ┆   ┆          ┆           ┆           ┆           │
│ GENO…     ┆           ┆ paired    ┆           ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆ end…      ┆           ┆   ┆          ┆           ┆           ┆           │
│ GSM486040 ┆ SRX936418 ┆ GSM486040 ┆ null      ┆ … ┆ 6787073  ┆ tumor*    ┆ 0         ┆ likely_no │
│ 0         ┆ 0         ┆ 0: Fresh- ┆           ┆   ┆          ┆           ┆           ┆ n_cancer  │
│           ┆           ┆ frozen    ┆           ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆ canin…    ┆           ┆   ┆          ┆           ┆           ┆           │
│ GSM486040 ┆ SRX936418 ┆ GSM486040 ┆ null      ┆ … ┆ 14821009 ┆ tumor*    ┆ 0         ┆ likely_no │
│ 1         ┆ 1         ┆ 1: Fresh- ┆           ┆   ┆          ┆           ┆           ┆ n_cancer  │
│           ┆           ┆ frozen    ┆           ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆ canin…    ┆           ┆   ┆          ┆           ┆           ┆           │
│ GSM300511 ┆ SRX139997 ┆ GSM300511 ┆ null      ┆ … ┆ 2648204  ┆ bladder   ┆ 0         ┆ likely_no │
│ 1         ┆ 82        ┆ 1: D_Norm ┆           ┆   ┆          ┆ cancer    ┆           ┆ n_cancer  │
│           ┆           ┆ al_Mucosa ┆           ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆ ; C…      ┆           ┆   ┆          ┆           ┆           ┆           │
│ GSM249835 ┆ SRX258189 ┆ GSM249835 ┆ null      ┆ … ┆ 2991046  ┆ tumor*    ┆ 1         ┆ uncertain │
│ 7         ┆ 9         ┆ 7:        ┆           ┆   ┆          ┆           ┆           ┆ _no_signa │
│           ┆           ┆ CHAD-P9;  ┆           ┆   ┆          ┆           ┆           ┆ l         │
│           ┆           ┆ Canis     ┆           ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆ lup…      ┆           ┆   ┆          ┆           ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …         ┆ …         ┆ …         │
│ GSM318787 ┆ SRX420033 ┆ GSM318787 ┆ null      ┆ … ┆ 5364090  ┆ rhabdomyo ┆ 1         ┆ uncertain │
│ 6         ┆ 4         ┆ 6: Rh30:  ┆           ┆   ┆          ┆ sarcoma   ┆           ┆ _weak_sig │
│           ┆           ┆ RH30_ENT; ┆           ┆   ┆          ┆           ┆           ┆ nal       │
│           ┆           ┆ Mu…       ┆           ┆   ┆          ┆           ┆           ┆           │
│ GSM357314 ┆ SRX527294 ┆ GSM357314 ┆ null      ┆ … ┆ 189230   ┆ tumor*    ┆ 1         ┆ likely_no │
│ 0         ┆ 6         ┆ 0: SAM243 ┆           ┆   ┆          ┆           ┆           ┆ n_cancer  │
│           ┆           ┆ 42223     ┆           ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆ Macrop…   ┆           ┆   ┆          ┆           ┆           ┆           │
│ GSM357315 ┆ SRX527295 ┆ GSM357315 ┆ null      ┆ … ┆ 205251   ┆ tumor*    ┆ 1         ┆ likely_no │
│ 0         ┆ 6         ┆ 0: SAM243 ┆           ┆   ┆          ┆           ┆           ┆ n_cancer  │
│           ┆           ┆ 42227     ┆           ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆ Macrop…   ┆           ┆   ┆          ┆           ┆           ┆           │
│ GSM361182 ┆ SRX538990 ┆ GSM361182 ┆ null      ┆ … ┆ 17061    ┆ tumor*    ┆ 1         ┆ confident │
│ 3         ┆ 0         ┆ 3: Tumor  ┆           ┆   ┆          ┆           ┆           ┆ _cancer   │
│           ┆           ┆ 5_non-PoE ┆           ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆ Ms;…      ┆           ┆   ┆          ┆           ┆           ┆           │
│ GSM403702 ┆ SRX672076 ┆ GSM403702 ┆ null      ┆ … ┆ 2310298  ┆ hepatocel ┆ 1         ┆ likely_ca │
│ 9         ┆ 4         ┆ 9: MYC_Tw ┆           ┆   ┆          ┆ lular     ┆           ┆ ncer      │
│           ┆           ┆ ist1_HCC_ ┆           ┆   ┆          ┆ cancer    ┆           ┆           │
│           ┆           ┆ 5; …      ┆           ┆   ┆          ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

In [8]:
import spacy
import medspacy

# Option 1: Use medspacy pipeline directly
nlp = medspacy.load()

# Option 2: If you need to add to existing pipeline
# Load medspacy and copy the context component
negex = medspacy.load()
nlp.add_pipe("medspacy_context", source=negex, name="context", last=True)

In [19]:
text = "No evidence of metastatic cancer in the liver."

doc = nlp(text)
for ent in doc.ents:
    print(ent.text, ent._.is_negated, ent._.is_family, ent._.is_historical)

2025-11-04 01:07:15.050 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=660] [doc 0] Token 0 'No' marked as sentence start (span begin)
2025-11-04 01:07:15.052 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=660] Token/tag mapping: [(No, True), (evidence, False), (of, False), (metastatic, False), (cancer, False), (in, False), (the, False), (liver, False), (., False)]

cancer True False False

In [20]:
import re

def clean_tissue(val: str) -> str:
    if not val or val.lower() == "nan":
        return None
    val = re.sub(r"\s+", " ", val.strip())
    tokens = [t for t in val.split() if t.lower() != "nan"]
    cleaned = []
    for t in tokens:
        if not cleaned or cleaned[-1].lower() != t.lower():
            cleaned.append(t)
    return " ".join(cleaned)

## First medspaCy

In [21]:
import spacy
import medspacy

# Load medspacy pipeline once (global scope for efficiency)
nlp = medspacy.load()


def analyze_text_with_spacy(text: str) -> dict:
    """
    Use spaCy/medspacy to detect cancer terms and check if they're negated.
    Returns a dict with: has_cancer_term, has_negated_cancer, has_confirmed_cancer
    """
    if not text or not isinstance(text, str) or not text.strip():
        return {
            "has_cancer_term": False,
            "has_negated_cancer": False,
            "has_confirmed_cancer": False
        }

    # Define cancer-related terms
    cancer_terms = [
        "cancer", "tumor", "tumour", "malignant", "malignancy",
        "carcinoma", "neoplasm", "metastatic", "metastasis",
        "adenocarcinoma", "sarcoma", "leukemia", "leukaemia",
        "lymphoma", "glioblastoma", "melanoma"
    ]

    doc = nlp(text.lower())

    has_cancer_term = False
    has_negated_cancer = False
    has_confirmed_cancer = False

    # Check entities detected by medspacy
    for ent in doc.ents:
        # Check if entity contains cancer-related terms
        if any(term in ent.text for term in cancer_terms):
            has_cancer_term = True

            # Check negation using medspacy's context detection
            if hasattr(ent._, "is_negated") and ent._.is_negated:
                has_negated_cancer = True
            else:
                has_confirmed_cancer = True

    # Fallback: if no entities but cancer terms present in text
    if not has_cancer_term and any(term in text.lower() for term in cancer_terms):
        # Run a simple token check
        tokens = text.lower().split()
        for term in cancer_terms:
            if term in tokens:
                has_cancer_term = True
                # Simple negation check for standalone terms
                idx = tokens.index(term)
                if idx > 0 and tokens[idx - 1] in ["no", "not", "without", "negative"]:
                    has_negated_cancer = True
                else:
                    has_confirmed_cancer = True
                break

    return {
        "has_cancer_term": has_cancer_term,
        "has_negated_cancer": has_negated_cancer,
        "has_confirmed_cancer": has_confirmed_cancer
    }

In [22]:
def classify_cancer_samples(df: pl.DataFrame) -> pl.DataFrame:
    """
    Classify samples as cancer / non-cancer / uncertain using spaCy NLP.
    Returns the same DataFrame with added classification columns.
    """

    # --- Step 1: Setup ---
    PRIORITY_COLS = ["source_name", "tissue", "phenotype", "disease", "cell_type", "tumor_type"]
    PRIORITY_COLS = [c for c in PRIORITY_COLS if c in df.columns]

    # Onco-traps pattern (still useful for false positives)
    ONCO_TRAPS = r"(?:\boncophora\b|\boncorhynchus\b|\boncotic\b|\boncomodulin\b)"

    # Helper to normalize text columns
    def normalize_text(col_expr):
        return (
            col_expr.cast(pl.Utf8)
            .fill_null("")
            .str.to_lowercase()
            .str.replace_all(r"[_/|]", " ")
            .str.replace_all(r"\s+", " ")
            .str.strip_chars()
        )
    # --- Step 1.5: Clean tissue column if present ---
    if "tissue" in df.columns:
        df = df.with_columns(
            pl.col("tissue").map_elements(clean_tissue, return_dtype=pl.Utf8)
        )

    # --- Step 2: Sample name detection using spaCy ---
    sample_name_col = "title" if "title" in df.columns else "biosample"

    # Extract texts directly from Polars (no pandas conversion)
    sample_texts = df.select(normalize_text(pl.col(sample_name_col)).alias("text"))["text"].to_list()

    # Analyze each sample name with spaCy
    spacy_results = [analyze_text_with_spacy(text) for text in sample_texts]

    df = df.with_columns([
        pl.Series("cancer_in_sample_name", [r["has_confirmed_cancer"] for r in spacy_results]),
        pl.Series("negative_in_sample_name", [r["has_negated_cancer"] for r in spacy_results]),
        normalize_text(pl.col(sample_name_col)).str.contains(ONCO_TRAPS).alias("onco_trap_in_sample_name"),
    ])

    # --- Step 3: Check priority columns with spaCy ---
    for col in PRIORITY_COLS:
        # Extract texts directly from Polars (no pandas conversion)
        col_texts = df.select(normalize_text(pl.col(col)).alias("text"))["text"].to_list()
        col_results = [analyze_text_with_spacy(text) for text in col_texts]

        df = df.with_columns([
            pl.Series(f"cancer_in_{col}", [r["has_confirmed_cancer"] for r in col_results]),
            pl.Series(f"negative_in_{col}", [r["has_negated_cancer"] for r in col_results]),
        ])


    # --- Step 4: Count mentions ---
    cancer_mention_cols = [f"cancer_in_{c}" for c in PRIORITY_COLS]
    negative_mention_cols = [f"negative_in_{c}" for c in PRIORITY_COLS]

    df = df.with_columns([
        pl.sum_horizontal([pl.col(c) for c in cancer_mention_cols if c in df.columns]).alias("n_cancer_mentions"),
        pl.sum_horizontal([pl.col(c) for c in negative_mention_cols if c in df.columns]).alias("n_negative_mentions"),
    ])

    # --- Step 5: Confidence category ---
    df = df.with_columns([
        pl.when(pl.col("onco_trap_in_sample_name"))
        .then(pl.lit("uncertain_onco_trap"))
        .when(
            pl.col("cancer_in_sample_name") &
            (pl.col("n_cancer_mentions") >= 1) &
            (pl.col("n_negative_mentions") == 0)
        )
        .then(pl.lit("confident_cancer"))
        .when(
            (pl.col("cancer_in_sample_name") & (pl.col("n_negative_mentions") == 0)) |
            (pl.col("n_cancer_mentions") >= 2)
        )
        .then(pl.lit("likely_cancer"))
        .when(
            pl.col("negative_in_sample_name") |
            (pl.col("n_negative_mentions") >= 1)
        )
        .then(pl.lit("likely_non_cancer"))
        .when(pl.col("n_cancer_mentions") == 1)
        .then(pl.lit("uncertain_weak_signal"))
        .otherwise(pl.lit("uncertain_no_signal"))
        .alias("confidence_category")
    ])

    # --- Step 6: Binary classification (1 = cancer, 0 = not cancer) ---
    df = df.with_columns([
        pl.when(pl.col("confidence_category").is_in(["confident_cancer", "likely_cancer", "uncertain_weak_signal"]))
        .then(pl.lit(1))
        .otherwise(pl.lit(0))
        .alias("predicted_cancer_binary")
    ])

    return df

In [13]:
predicted_df = classify_cancer_samples(joined)

2025-11-04 00:53:25.198 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1] [doc 0] Token 0 'illumina' marked as sentence start (span begin)
2025-11-04 00:53:25.199 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1] Token/tag mapping: [(illumina, True), (hiseq, False), (2500, False), (paired, False), (end, False), (sequencing, False)]
2025-11-04 00:53:25.201 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2] [doc 0] Token 0 'gsm4860400' marked as sentence start (span begin)
2025-11-04 00:53:25.201 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2] Token/tag mapping: [(gsm4860400, True), (:, False), (fresh, False), (-, False), (frozen, False), (canine, False), (healthy, False), (brain, False), (tissue, False), (-, False), (dog, False), (no, False), (., False), (60459, False), (;, False), (canis, False), (lupus, False), (familiaris, False), (;, False), (rna, False), (-, False), (seq, False)]
2025-11-04 00:53:25.204 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3] [doc 0] Token 0 'gsm4860401' marked as sentence start (span begin)
2025-11-04 00:53:25.204 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3] Token/tag mapping: [(gsm4860401, True), (:, False), (fresh, False), (-, False), (frozen, False), (canine, False), (healthy, False), (brain, False), (tissue, False), (-, False), (dog, False), (no, False), (., False), (60460, False), (;, False), (canis, False), (lupus, False), (familiaris, False), (;, False), (rna, False), (-, False), (seq, False)]
2025-11-04 00:53:25.206 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=4] [doc 0] Token 0 'gsm3005111' marked as sentence start (span begin)
2025-11-04 00:53:25.206 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=4] Token/tag mapping: [(gsm3005111, True), (:, False), (d, False), (normal, False), (mucosa, False), (;, False), (canis, False), (lupus, False), (familiaris, False), (;, False), (rna, False), (-, False), (seq, False)]
2025-11-04 00:53:25.207 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=5] [doc 0] Token 0 'gsm2498357' marked as sentence start (span begin)
2025-11-04 00:53:25.207 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=5] Token/tag mapping: [(gsm2498357, True), (:, False), (chad, False), (-, False), (p9, False), (;, False), (canis, False), (lupus, False), (familiaris, False), (;, False), (rna, False), (-, False), (seq, False)]
2025-11-04 00:53:25.209 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=6] [doc 0] Token 0 'whole' marked as sentence start (span begin)
2025-11-04 00:53:25.210 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=6] Token/tag mapping: [(whole, True), (exome, False), (sequencing, False), (of, False), (canine, False), (mucosal, False), (melanoma, False)]
2025-11-04 00:53:25.212 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] [doc 0] Token 0 'gsm3384215' marked as sentence start (span begin)
2025-11-04 00:53:25.212 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] Token/tag mapping: [(gsm3384215, True), (:, False), (cmt, False), (-, False), (121, False), (-, False), (normal, False), (;, False), (canis, False), (lupus, False), (familiaris, False), (;, False), (rna, False), (-, False), (seq, False)]
2025-11-04 00:53:25.213 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=8] [doc 0] Token 0 'gsm3384243' marked as sentence start (span begin)
2025-11-04 00:53:25.213 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=8] Token/tag mapping: [(gsm3384243, True), (:, False), (cmt, False), (-, False), (193, False), (-, False), (normal, False), (;, False), (canis, False), (lupus, False), (familiaris, False), (;, False), (rna, False), (-, False), (seq, False)]
2025-11-04 00:53:25.215 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=9] [doc 0] Token 0 'gsm3384261' marked as sentence start (span begin)
2025-11-04 00:53:25.215 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=9] Token/tag mapping: [(gsm3384261, True), (:, False), (cmt, False), (-, False), (232, False), (-, False), (normal, False), (;, False), (canis, False), (lupus, False), (familiaris, False), (;, False), (rna, False), (-, False), (seq, False)]
2025-11-04 00:53:25.217 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=10] [doc 0] Token 0 '32510' marked as sentence start (span begin)
2025-11-04 00:53:25.218 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=10] Token/tag mapping: [(32510, True), (rna, False), (-, False), (seq, False), (of, False), (spontaneous, False), (canine, False), (mammary, False), (cancers, False), (and, False), (matching, False), (normal, False), (samples, False)]
2025-11-04 00:53:25.220 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=11] [doc 0] Token 0 'gsm3993105' marked as sentence start (span begin)
2025-11-04 00:53:25.220 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=11] Token/tag mapping: [(gsm3993105, True), (:, False), (normal, False), (stroma, False), (123, False), (norm, False), (;, False), (canis, False), (lupus, False), (familiaris, False), (;, False), (rna, False), (-, False), (seq, False)]
2025-11-04 00:53:25.223 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=12] [doc 0] Token 0 'illumina' marked as sentence start (span begin)
2025-11-04 00:53:25.223 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=12] Token/tag mapping: [(illumina, True), (hiseq, False), (4000, False), (paired, False), (end, False), (sequencing, False), (;, False), (whole, False), (transcriptome, False), (analysis, False), (of, False), (rat, False), (peritoneal, False), (cells, False), (in, False), (a, False), (tgfβ1, False), (induced, False), (mesothelial, False), (-, False), (to, False), (-, False), (mesenchymal, False), (transition, False)]
2025-11-04 00:53:25.225 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=13] [doc 0] Token 0 'rna' marked as sentence start (span begin)
2025-11-04 00:53:25.225 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=13] Token/tag mapping: [(rna, True), (-, False), (seq, False), (of, False), (rattus, False), (norvegicusreplication, False), (2, False), (of, False), (untreated, False), (poorly, False), (differentiated, False), (pc12, False), (cells, False)]
2025-11-04 00:53:25.227 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=14] [doc 0] Token 0 'gsm5957075' marked as sentence start (span begin)
2025-11-04 00:53:25.228 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=14] Token/tag mapping: [(gsm5957075, True), (:, False), (osteosarcoma, False), (from, False), (p53r245w, False), (+, False), (gigi, False), (r245w, False), (16, False), (22, False), (;, False), (mus, False), (musculus, False), (;, False), (rna, False), (-, False), (seq, False)]
2025-11-04 00:53:25.229 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=15] [doc 0] Token 0 'nextseq' marked as sentence start (span begin)
2025-11-04 00:53:25.230 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=15] Token/tag mapping: [(nextseq, True), (500, False), (sequencing, False)]
2025-11-04 00:53:25.235 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=16] [doc 0] Token 0 'nan' marked as sentence start (span begin)
2025-11-04 00:53:25.235 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=16] Token/tag mapping: [(nan, True), (illumina, False), (hiseq, False), (2000, False), (paired, False), (end, False), (sequencing, False), (;, False), (single, False), (cell, False), (mrna, False), (-sequencing, False), (reveals, False), (cell, False), (-, False), (to, False), (-, False), (cell, False), (variation, False), (in, False), (three, False), (mouse, False), (es, False), (cell, False), (culture, False), (conditions, False), (nan, False), (nan, False), (illumina, False), (hiseq, False), (2000, False), (paired, False), (end, False), (sequencing, False), (;, False), (single, False), (cell, False), (mrna, False), (-sequencing, False), (reveals, False), (cell, False), (-, False), (to, False), (-, False), (cell, False), (variation, False), (in, False), (three, False), (mouse, False), (es, False), (cell, False), (culture, False), (conditions, False), (nan, False)]
2025-11-04 00:53:25.237 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=17] [doc 0] Token 0 'bulk' marked as sentence start (span begin)
2025-11-04 00:53:25.238 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=17] Token/tag mapping: [(bulk, True), (rna, False), (-, False), (seq, False), (of, False), (cd4, False), (t, False), (cells, False), (from, False), (mice, False), (with, False), (mc38, False), (tumors, False)]
2025-11-04 00:53:25.241 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=18] [doc 0] Token 0 'illumina' marked as sentence start (span begin)
2025-11-04 00:53:25.242 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=18] Token/tag mapping: [(illumina, True), (hiseq, False), (4000, False), (sequencing, False), (;, False), (rna, False), (-, False), (seq, False), (of, False), (mus, False), (musculus, False), (beta, False), (cells, False), (to, False), (determine, False), (the, False), (role, False), (of, False), (the, False), (mir, False), (-, False), (200, False), (–, False), (zeb1, False), (axis, False), (in, False), (beta, False), (cell, False), (tumor, False), (development, False)]
2025-11-04 00:53:25.245 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=19] [doc 0] Token 0 'illumina' marked as sentence start (span begin)
2025-11-04 00:53:25.245 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=19] Token/tag mapping: [(illumina, True), (hiseq, False), (2500, False), (sequencing, False), (;, False), (regional, False), (cns, False), (immune, False), (fingerprint, False), (in, False), (chronic, False), (peripheral, False), (inflammation, False)]
2025-11-04 00:53:25.248 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=20] [doc 0] Token 0 'illumina' marked as sentence start (span begin)
2025-11-04 00:53:25.248 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=20] Token/tag mapping: [(illumina, True), (hiseq, False), (4000, False), (sequencing, False), (;, False), (rna, False), (-, False), (seq, False), (analysis, False), (of, False), (macrophages, False), (from, False), (normal, False), (and, False), (tumor, False), (-, False), (infiltrated, False), (omentum, False)]
2025-11-04 00:53:25.249 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=21] [doc 0] Token 0 'nextseq' marked as sentence start (span begin)
2025-11-04 00:53:25.249 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=21] Token/tag mapping: [(nextseq, True), (500, False), (paired, False), (end, False), (sequencing, False)]
2025-11-04 00:53:25.252 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=22] [doc 0] Token 0 'illumina' marked as sentence start (span begin)
2025-11-04 00:53:25.252 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=22] Token/tag mapping: [(illumina, True), (miseq, False), (paired, False), (end, False), (sequencing, False), (;, False), (complement, False), (c3ar, False), (acts, False), (as, False), (an, False), (oncosuppressor, False), (in, False), (colorectal, False), (cancer, False), (by, False), (modulating, False), (gut, False), (microbiota, False)]
2025-11-04 00:53:25.255 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=23] [doc 0] Token 0 'illumina' marked as sentence start (span begin)
2025-11-04 00:53:25.256 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=23] Token/tag mapping: [(illumina, True), (hiseq, False), (4000, False), (paired, False), (end, False), (sequencing, False), (;, False), (scrnaseq, False), (of, False), (cyp11a1, False), (-, False), (expressing, False), (cells, False), (from, False), (mouse, False), (melanoma, False), (model, False), (derived, False), (tumors, False)]
2025-11-04 00:53:25.258 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=24] [doc 0] Token 0 'illumina' marked as sentence start (span begin)
2025-11-04 00:53:25.259 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=24] Token/tag mapping: [(illumina, True), (hiseq, False), (4000, False), (paired, False), (end, False), (sequencing, False), (;, False), (scrnaseq, False), (of, False), (cyp11a1, False), (-, False), (expressing, False), (cells, False), (from, False), (mouse, False), (melanoma, False), (model, False), (derived, False), (tumors, False)]
2025-11-04 00:53:25.262 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=25] [doc 0] Token 0 'nextseq' marked as sentence start (span begin)
2025-11-04 00:53:25.263 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=25] Token/tag mapping: [(nextseq, True), (500, False), (sequencing, False), (;, False), (rna, False), (sequencing, False), (of, False), (mouse, False), (samples, False), (using, False), (the, False), (illumina, False), (truseq, False), (®, False), (stranded, False), (mrna, False), (technology, False), (and, False), (the, False), (nextseq500, False), (next, False), (generation, False), (sequencing, False), (system, False)]
2025-11-04 00:53:25.266 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=26] [doc 0] Token 0 'nextseq' marked as sentence start (span begin)
2025-11-04 00:53:25.266 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=26] Token/tag mapping: [(nextseq, True), (500, False), (paired, False), (end, False), (sequencing, False), (;, False), (dna, False), (barcoding, False), (reveals, False), (ongoing, False), (immunoediting, False), (of, False), (clonal, False), (cancer, False), (populations, False), (during, False), (metastatic, False), (progression, False), (and, False), (in, False), (response, False), (to, False), (immunotherapy, False)]
2025-11-04 00:53:25.270 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=27] [doc 0] Token 0 'nan' marked as sentence start (span begin)
2025-11-04 00:53:25.271 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=27] Token/tag mapping: [(nan, True), (illumina, False), (hiseq, False), (2000, False), (paired, False), (end, False), (sequencing, False), (;, False), (gene, False), (expression, False), (pattern, False), (of, False), (single, False), (mes, False), (cells, False), (during, False), (cell, False), (cycle, False), (stages, False), (nan, False), (nan, False), (illumina, False), (hiseq, False), (2000, False), (paired, False), (end, False), (sequencing, False), (;, False), (gene, False), (expression, False), (pattern, False), (of, False), (single, False), (mes, False), (cells, False), (during, False), (cell, False), (cycle, False), (stages, False), (nan, False)]
2025-11-04 00:53:25.272 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=28] [doc 0] Token 0 'illumina' marked as sentence start (span begin)
2025-11-04 00:53:25.272 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=28] Token/tag mapping: [(illumina, True), (hiseq, False), (2000, False), (paired, False), (end, False), (sequencing, False)]
2025-11-04 00:53:25.275 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=29] [doc 0] Token 0 'illumina' marked as sentence start (span begin)
2025-11-04 00:53:25.275 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=29] Token/tag mapping: [(illumina, True), (hiseq, False), (2500, False), (sequencing, False), (;, False), (melanoma, False), (-, False), (derived, False), (extracellular, False), (vesicles, False), (mediate, False), (lymphatic, False), (remodeling, False), (and, False), (impair, False), (tumor, False), (immunity, False), (in, False), (draining, False), (lymph, False), (nodes, False)]
2025-11-04 00:53:25.278 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=30] [doc 0] Token 0 'illumina' marked as sentence start (span begin)
2025-11-04 00:53:25.278 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=30] Token/tag mapping: [(illumina, True), (hiseq, False), (4000, False), (paired, False), (end, False), (sequencing, False), (;, False), (spatiotemporal, False), (dynamics, False), (of, False), (crc, False), (metastases, False), (resolved, False), (by, False), (single, False), (cell, False), (rnaseq, False)]
2025-11-04 00:53:25.281 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=31] [doc 0] Token 0 'gsm1245211' marked as sentence start (span begin)
2025-11-04 00:53:25.281 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=31] Token/tag mapping: [(gsm1245211, True), (:, False), (normal, False), (homogenate, False), (rna, False), (-, False), (seq, False), (a, False), (;, False), (mus, False), (musculus, False), (;, False), (rna, False), (-, False), (seq, False), (nan, False), (gsm1245211, False), (:, False), (normal, False), (homogenate, False), (rna, False), (-, False), (seq, False), (a, False), (;, False), (mus, False), (musculus, False), (;, False), (rna, False), (-, False), (seq, False), (nan, False)]
2025-11-04 00:53:25.282 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=32] [doc 0] Token 0 'gsm4232527' marked as sentence start (span begin)
2025-11-04 00:53:25.282 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=32] Token/tag mapping: [(gsm4232527, True), (:, False), (mettl14, False), (ko, False), (rna, False), (seq, False), (rep3, False), (;, False), (mus, False), (musculus, False), (;, False), (rna, False), (-, False), (seq, False)]
2025-11-04 00:53:25.284 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=33] [doc 0] Token 0 'gsm4279928' marked as sentence start (span begin)
2025-11-04 00:53:25.284 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=33] Token/tag mapping: [(gsm4279928, True), (:, False), (kshv, False), ((, False), (+, False), (), False), (tumors, False), ([, False), (ds015accepted, False), (hitsmouse, False), (], False), (;, False), (mus, False), (musculus, False), (;, False), (rna, False), (-, False), (seq, False)]
2025-11-04 00:53:25.285 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=34] [doc 0] Token 0 'gsm4396316' marked as sentence start (span begin)
2025-11-04 00:53:25.286 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=34] Token/tag mapping: [(gsm4396316, True), (:, False), (sh, False), (-, False), (ctrl, False), (replicate, False), (2, False), (;, False), (mus, False), (musculus, False), (;, False), (rna, False), (-, False), (seq, False)]

In [14]:
# find the position of "cancer_type"
idx = predicted_df.columns.index("cancer_type")

# slice up to that column (inclusive)
cols_to_keep = predicted_df.columns[:idx + 1]

# add the two specific extra columns
cols_to_keep += ["is_cancer", "confidence_category", "predicted_cancer_binary"]

predicted_df.select(cols_to_keep)

shape: (172, 41)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ experimen ┆ experimen ┆ title     ┆ study_nam ┆ … ┆ cancer_ty ┆ is_cancer ┆ confidenc ┆ predicte │
│ t_alias   ┆ t_accessi ┆ ---       ┆ e         ┆   ┆ pe        ┆ ---       ┆ e_categor ┆ d_cancer │
│ ---       ┆ on        ┆ str       ┆ ---       ┆   ┆ ---       ┆ i64       ┆ y         ┆ _binary  │
│ str       ┆ ---       ┆           ┆ str       ┆   ┆ str       ┆           ┆ ---       ┆ ---      │
│           ┆ str       ┆           ┆           ┆   ┆           ┆           ┆ str       ┆ i32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ ena-EXPER ┆ ERX352605 ┆ Illumina  ┆ null      ┆ … ┆ carcinoma ┆ 0         ┆ uncertain ┆ 0        │
│ IMENT-FUN ┆ 7         ┆ HiSeq     ┆           ┆   ┆           ┆           ┆ _no_signa ┆          │
│ CTIONAL   ┆           ┆ 2500      ┆           ┆   ┆           ┆           ┆ l         ┆          │
│ GENO…     ┆           ┆ paired    ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ end…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ GSM486040 ┆ SRX936418 ┆ GSM486040 ┆ null      ┆ … ┆ tumor*    ┆ 0         ┆ uncertain ┆ 0        │
│ 0         ┆ 0         ┆ 0: Fresh- ┆           ┆   ┆           ┆           ┆ _no_signa ┆          │
│           ┆           ┆ frozen    ┆           ┆   ┆           ┆           ┆ l         ┆          │
│           ┆           ┆ canin…    ┆           ┆   ┆           ┆           ┆           ┆          │
│ GSM486040 ┆ SRX936418 ┆ GSM486040 ┆ null      ┆ … ┆ tumor*    ┆ 0         ┆ uncertain ┆ 0        │
│ 1         ┆ 1         ┆ 1: Fresh- ┆           ┆   ┆           ┆           ┆ _no_signa ┆          │
│           ┆           ┆ frozen    ┆           ┆   ┆           ┆           ┆ l         ┆          │
│           ┆           ┆ canin…    ┆           ┆   ┆           ┆           ┆           ┆          │
│ GSM300511 ┆ SRX139997 ┆ GSM300511 ┆ null      ┆ … ┆ bladder   ┆ 0         ┆ uncertain ┆ 0        │
│ 1         ┆ 82        ┆ 1: D_Norm ┆           ┆   ┆ cancer    ┆           ┆ _no_signa ┆          │
│           ┆           ┆ al_Mucosa ┆           ┆   ┆           ┆           ┆ l         ┆          │
│           ┆           ┆ ; C…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ GSM249835 ┆ SRX258189 ┆ GSM249835 ┆ null      ┆ … ┆ tumor*    ┆ 1         ┆ uncertain ┆ 0        │
│ 7         ┆ 9         ┆ 7:        ┆           ┆   ┆           ┆           ┆ _no_signa ┆          │
│           ┆           ┆ CHAD-P9;  ┆           ┆   ┆           ┆           ┆ l         ┆          │
│           ┆           ┆ Canis     ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ lup…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ GSM318787 ┆ SRX420033 ┆ GSM318787 ┆ null      ┆ … ┆ rhabdomyo ┆ 1         ┆ uncertain ┆ 1        │
│ 6         ┆ 4         ┆ 6: Rh30:  ┆           ┆   ┆ sarcoma   ┆           ┆ _weak_sig ┆          │
│           ┆           ┆ RH30_ENT; ┆           ┆   ┆           ┆           ┆ nal       ┆          │
│           ┆           ┆ Mu…       ┆           ┆   ┆           ┆           ┆           ┆          │
│ GSM357314 ┆ SRX527294 ┆ GSM357314 ┆ null      ┆ … ┆ tumor*    ┆ 1         ┆ uncertain ┆ 0        │
│ 0         ┆ 6         ┆ 0: SAM243 ┆           ┆   ┆           ┆           ┆ _no_signa ┆          │
│           ┆           ┆ 42223     ┆           ┆   ┆           ┆           ┆ l         ┆          │
│           ┆           ┆ Macrop…   ┆           ┆   ┆           ┆           ┆           ┆          │
│ GSM357315 ┆ SRX527295 ┆ GSM357315 ┆ null      ┆ … ┆ tumor*    ┆ 1         ┆ uncertain ┆ 0        │
│ 0         ┆ 6         ┆ 0: SAM243 ┆           ┆   ┆           ┆           ┆ _no_signa ┆          │
│           ┆           ┆ 42227     ┆           ┆   ┆           ┆           ┆ l         ┆          │
│           ┆           ┆ Macrop…   ┆           ┆   ┆           ┆           ┆           ┆          │
│ GSM361182 ┆ SRX538990 ┆ GSM361182 ┆ null      ┆ … ┆ tumor*    ┆ 1         ┆ confident ┆ 1        │
│ 3         ┆ 0         ┆ 3: Tumor  ┆           ┆   ┆           ┆           ┆ _cancer   ┆          │
│           ┆           ┆ 5_non-PoE ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Ms;…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ GSM403702 ┆ SRX672076 ┆ GSM403702 ┆ null      ┆ … ┆ hepatocel ┆ 1         ┆ likely_ca ┆ 1        │
│ 9         ┆ 4         ┆ 9: MYC_Tw ┆           ┆   ┆ lular     ┆           ┆ ncer      ┆          │
│           ┆           ┆ ist1_HCC_ ┆           ┆   ┆ cancer    ┆           ┆           ┆          │
│           ┆           ┆ 5; …      ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [15]:
import numpy as np
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

# Convert to numpy arrays
y_true = predicted_df["is_cancer"].to_numpy()
y_pred = predicted_df["predicted_cancer_binary"].to_numpy()

# --- Metrics ---
acc = accuracy_score(y_true, y_pred)
prec = precision_score(y_true, y_pred)
rec = recall_score(y_true, y_pred)
f1 = f1_score(y_true, y_pred)

print(f"Accuracy:  {acc:.3f}")
print(f"Precision: {prec:.3f}")
print(f"Recall:    {rec:.3f}")
print(f"F1-score:  {f1:.3f}")

# --- Confusion Matrix ---
cm = confusion_matrix(y_true, y_pred)
print("\nConfusion Matrix:\n", cm)

# --- Full report ---
print("\nClassification Report:\n", classification_report(y_true, y_pred))

Accuracy:  0.744
Precision: 0.894
Recall:    0.712
F1-score:  0.792

Confusion Matrix:
 [[44 10]
 [34 84]]

Classification Report:
               precision    recall  f1-score   support

           0       0.56      0.81      0.67        54
           1       0.89      0.71      0.79       118

    accuracy                           0.74       172
   macro avg       0.73      0.76      0.73       172
weighted avg       0.79      0.74      0.75       172

In [16]:
predicted_df.filter(
    (pl.col("predicted_cancer_binary") == 0) & (pl.col("is_cancer") == 1)
).select([
    "sample_id", "source_name", "tissue", "is_cancer", "predicted_cancer_binary",
    "confidence_category"
])[:100]

shape: (34, 6)
┌─────────────┬──────────────────┬─────────────────┬───────────┬─────────────────┬─────────────────┐
│ sample_id   ┆ source_name      ┆ tissue          ┆ is_cancer ┆ predicted_cance ┆ confidence_cate │
│ ---         ┆ ---              ┆ ---             ┆ ---       ┆ r_binary        ┆ gory            │
│ str         ┆ str              ┆ str             ┆ i64       ┆ ---             ┆ ---             │
│             ┆                  ┆                 ┆           ┆ i32             ┆ str             │
╞═════════════╪══════════════════╪═════════════════╪═══════════╪═════════════════╪═════════════════╡
│ null        ┆ hemangiosarcoma  ┆ spleen          ┆ 1         ┆ 0               ┆ uncertain_no_si │
│             ┆                  ┆                 ┆           ┆                 ┆ gnal            │
│ null        ┆ canine mammary   ┆ mammary normal  ┆ 1         ┆ 0               ┆ uncertain_no_si │
│             ┆ normal tissue    ┆ tissue          ┆           ┆                 ┆ gnal            │
│ null        ┆ null             ┆                 ┆ 1         ┆ 0               ┆ uncertain_no_si │
│             ┆                  ┆                 ┆           ┆                 ┆ gnal            │
│ null        ┆ null             ┆ Untreated PC12  ┆ 1         ┆ 0               ┆ uncertain_no_si │
│             ┆                  ┆ cells from      ┆           ┆                 ┆ gnal            │
│             ┆                  ┆ pheo…           ┆           ┆                 ┆                 │
│ nan nan nan ┆ null             ┆                 ┆ 1         ┆ 0               ┆ uncertain_no_si │
│ nan nan nan ┆                  ┆                 ┆           ┆                 ┆ gnal            │
│ nan na…     ┆                  ┆                 ┆           ┆                 ┆                 │
│ …           ┆ …                ┆ …               ┆ …         ┆ …               ┆ …               │
│ nan nan nan ┆ Mus musculus CD8 ┆                 ┆ 1         ┆ 0               ┆ uncertain_no_si │
│ nan         ┆ TILs             ┆                 ┆           ┆                 ┆ gnal            │
│ nan nan nan ┆ Cell explanted   ┆                 ┆ 1         ┆ 0               ┆ uncertain_no_si │
│ nan         ┆ from EGFRvIII d… ┆                 ┆           ┆                 ┆ gnal            │
│ null        ┆ mice brain       ┆ null            ┆ 1         ┆ 0               ┆ uncertain_no_si │
│             ┆ tumors           ┆                 ┆           ┆                 ┆ gnal            │
│ nan nan nan ┆ cells sorted     ┆                 ┆ 1         ┆ 0               ┆ uncertain_no_si │
│ SAM24342223 ┆ from MC38 tumors ┆                 ┆           ┆                 ┆ gnal            │
│ nan na…     ┆                  ┆                 ┆           ┆                 ┆                 │
│ nan nan nan ┆ cells sorted     ┆                 ┆ 1         ┆ 0               ┆ uncertain_no_si │
│ SAM24342227 ┆ from MC38 tumors ┆                 ┆           ┆                 ┆ gnal            │
│ nan na…     ┆                  ┆                 ┆           ┆                 ┆                 │
└─────────────┴──────────────────┴─────────────────┴───────────┴─────────────────┴─────────────────┘

## Testing medspaCy (NLP based approach)

In [17]:
import spacy
import medspacy
from medspacy.ner import TargetRule
# Note: TargetMatcher is fetched via pipeline, not imported directly

nlp = medspacy.load()  # load medspacy pipeline

# Retrieve the target matcher pipe
target_matcher = nlp.get_pipe("medspacy_target_matcher")

# Define your list of cancer-related terms
cancer_terms = ["cancer", "tumor", "tumour", "carcinoma", "neoplasm", "metastasis"]

# Build target rules
target_rules = [
    TargetRule(term, category="CANCER")
    for term in cancer_terms
]

# Add the rules to the matcher
target_matcher.add(target_rules)

# Test it
text = "The biopsy showed a malignant carcinoma and bone metastasis but no benign tumor."
doc = nlp(text)
for ent in doc.ents:
    print(ent.text, ent.label_, ent._.target_rule)

2025-11-04 00:54:37.817 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=656] [doc 0] Token 0 'The' marked as sentence start (span begin)
2025-11-04 00:54:37.817 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=656] Token/tag mapping: [(The, True), (biopsy, False), (showed, False), (a, False), (malignant, False), (carcinoma, False), (and, False), (bone, False), (metastasis, False), (but, False), (no, False), (benign, False), (tumor, False), (., False)]

carcinoma CANCER TargetRule(literal="carcinoma", category="CANCER", pattern=None, attributes=None, on_match=None)
metastasis CANCER TargetRule(literal="metastasis", category="CANCER", pattern=None, attributes=None, on_match=None)
tumor CANCER TargetRule(literal="tumor", category="CANCER", pattern=None, attributes=None, on_match=None)

In [18]:
import medspacy
from medspacy.ner import TargetRule

# Load full medspaCy pipeline (includes context/negation detection)
nlp = medspacy.load()
target_matcher = nlp.get_pipe("medspacy_target_matcher")

# Add some cancer-related target rules
for term in ["cancer", "tumor", "carcinoma"]:
    target_matcher.add([TargetRule(literal=term, category="CANCER")])

# Test examples
texts = [
    "There is no cancer here.",
    "Patient diagnosed with malignant tumor.",
    "No evidence of carcinoma detected."
]

for text in texts:
    doc = nlp(text)
    print(f"\nText: {text}")
    for ent in doc.ents:
        print(f" - Entity: {ent.text!r}, Category: {ent.label_}, Negated: {ent._.is_negated}")

2025-11-04 00:54:38.073 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=657] [doc 0] Token 0 'There' marked as sentence start (span begin)
2025-11-04 00:54:38.074 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=657] Token/tag mapping: [(There, True), (is, False), (no, False), (cancer, False), (here, False), (., False)]
2025-11-04 00:54:38.075 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=658] [doc 0] Token 0 'Patient' marked as sentence start (span begin)
2025-11-04 00:54:38.076 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=658] Token/tag mapping: [(Patient, True), (diagnosed, False), (with, False), (malignant, False), (tumor, False), (., False)]
2025-11-04 00:54:38.077 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=659] [doc 0] Token 0 'No' marked as sentence start (span begin)
2025-11-04 00:54:38.078 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=659] Token/tag mapping: [(No, True), (evidence, False), (of, False), (carcinoma, False), (detected, False), (., False)]

Text: There is no cancer here.
 - Entity: 'cancer', Category: CANCER, Negated: True

Text: Patient diagnosed with malignant tumor.
 - Entity: 'tumor', Category: CANCER, Negated: False

Text: No evidence of carcinoma detected.
 - Entity: 'carcinoma', Category: CANCER, Negated: True

## Second medspaCy (Failed Attempt)

In [32]:
import medspacy
from medspacy.ner import TargetRule

# --- Load medspacy pipeline ---
nlp = medspacy.load()
target_matcher = nlp.get_pipe("medspacy_target_matcher")

# Add cancer-related terms
CANCER_TERMS = [
    "cancer", "tumor", "tumour", "malignant", "malignancy",
    "carcinoma", "neoplasm", "metastatic", "metastasis",
    "adenocarcinoma", "sarcoma", "leukemia", "leukaemia",
    "lymphoma", "glioblastoma", "melanoma"
]
target_rules = [TargetRule(term, category="CANCER") for term in CANCER_TERMS]
target_matcher.add(target_rules)


def analyze_text_with_spacy(text: str) -> dict:
    """
    Detect cancer terms and check if they're negated using medspacy's context model.
    """
    if not text or not isinstance(text, str) or not text.strip():
        return {
            "has_cancer_term": False,
            "has_negated_cancer": False,
            "has_confirmed_cancer": False
        }

    doc = nlp(text.lower())

    has_cancer_term = False
    has_negated_cancer = False
    has_confirmed_cancer = False

    for ent in doc.ents:
        if ent.label_ == "CANCER":      # detected by target matcher
            has_cancer_term = True
            if getattr(ent._, "is_negated", False):
                has_negated_cancer = True
            else:
                has_confirmed_cancer = True

    return {
        "has_cancer_term": has_cancer_term,
        "has_negated_cancer": has_negated_cancer,
        "has_confirmed_cancer": has_confirmed_cancer
    }

In [34]:
# Test medspacy entity detection on real metadata samples
import spacy
import medspacy

# Load medspacy
nlp = medspacy.load()

# # Sample texts from different scenarios
test_texts = [
    "breast cancer tissue",
    "normal breast tissue",
    "no evidence of tumor",
    "tumor sample from lung",
    "cancer cell line",
    "adjacent normal tissue",
    "metastatic carcinoma",
    "healthy control sample",
    "glioblastoma multiforme",
    "non-tumor breast tissue"
]

print("=" * 80)
print("TESTING MEDSPACY ENTITY DETECTION")
print("=" * 80)

for text in test_texts:
    doc = nlp(text)
    entities = [(ent.text, ent.label_, getattr(ent._, 'is_negated', None)) for ent in doc.ents]

    print(f"\nText: '{text}'")
    if entities:
        print(f"  ✓ Entities found: {entities}")
    else:
        print(f"  ✗ NO ENTITIES DETECTED")

print("\n" + "=" * 80)

2025-10-28 13:11:10.465 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1341] [doc 0] Token 0 'breast' marked as sentence start (span begin)
2025-10-28 13:11:10.465 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1341] Token/tag mapping: [(breast, True), (cancer, False), (tissue, False)]
2025-10-28 13:11:10.466 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1342] [doc 0] Token 0 'normal' marked as sentence start (span begin)
2025-10-28 13:11:10.466 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1342] Token/tag mapping: [(normal, True), (breast, False), (tissue, False)]
2025-10-28 13:11:10.467 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1343] [doc 0] Token 0 'no' marked as sentence start (span begin)
2025-10-28 13:11:10.467 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1343] Token/tag mapping: [(no, True), (evidence, False), (of, False), (tumor, False)]
2025-10-28 13:11:10.468 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1344] [doc 0] Token 0 'tumor' marked as sentence start (span begin)
2025-10-28 13:11:10.469 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1344] Token/tag mapping: [(tumor, True), (sample, False), (from, False), (lung, False)]
2025-10-28 13:11:10.470 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1345] [doc 0] Token 0 'cancer' marked as sentence start (span begin)
2025-10-28 13:11:10.470 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1345] Token/tag mapping: [(cancer, True), (cell, False), (line, False)]
2025-10-28 13:11:10.470 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1346] [doc 0] Token 0 'adjacent' marked as sentence start (span begin)
2025-10-28 13:11:10.470 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1346] Token/tag mapping: [(adjacent, True), (normal, False), (tissue, False)]
2025-10-28 13:11:10.471 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1347] [doc 0] Token 0 'metastatic' marked as sentence start (span begin)
2025-10-28 13:11:10.471 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1347] Token/tag mapping: [(metastatic, True), (carcinoma, False)]
2025-10-28 13:11:10.472 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1348] [doc 0] Token 0 'healthy' marked as sentence start (span begin)
2025-10-28 13:11:10.472 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1348] Token/tag mapping: [(healthy, True), (control, False), (sample, False)]
2025-10-28 13:11:10.473 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1349] [doc 0] Token 0 'glioblastoma' marked as sentence start (span begin)
2025-10-28 13:11:10.473 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1349] Token/tag mapping: [(glioblastoma, True), (multiforme, False)]
2025-10-28 13:11:10.473 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1350] [doc 0] Token 0 'non' marked as sentence start (span begin)
2025-10-28 13:11:10.474 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1350] Token/tag mapping: [(non, True), (-, False), (tumor, False), (breast, False), (tissue, False)]

================================================================================
TESTING MEDSPACY ENTITY DETECTION
================================================================================

Text: 'breast cancer tissue'
  ✗ NO ENTITIES DETECTED

Text: 'normal breast tissue'
  ✗ NO ENTITIES DETECTED

Text: 'no evidence of tumor'
  ✗ NO ENTITIES DETECTED

Text: 'tumor sample from lung'
  ✗ NO ENTITIES DETECTED

Text: 'cancer cell line'
  ✗ NO ENTITIES DETECTED

Text: 'adjacent normal tissue'
  ✗ NO ENTITIES DETECTED

Text: 'metastatic carcinoma'
  ✗ NO ENTITIES DETECTED

Text: 'healthy control sample'
  ✗ NO ENTITIES DETECTED

Text: 'glioblastoma multiforme'
  ✗ NO ENTITIES DETECTED

Text: 'non-tumor breast tissue'
  ✗ NO ENTITIES DETECTED

================================================================================

In [57]:
import spacy
import medspacy
from medspacy.ner import TargetRule

# Load medspacy pipeline
nlp = medspacy.load()

# Get the target matcher component
target_matcher = nlp.get_pipe("medspacy_target_matcher")

# Define cancer-related terms to detect
cancer_rules = [
    # General cancer terms
    TargetRule("cancer", "PROBLEM"),
    TargetRule("cancers", "PROBLEM"),
    TargetRule("tumor", "PROBLEM"),
    TargetRule("tumour", "PROBLEM"),
    TargetRule("tumors", "PROBLEM"),
    TargetRule("tumours", "PROBLEM"),

    # Malignancy terms
    TargetRule("malignant", "PROBLEM"),
    TargetRule("malignancy", "PROBLEM"),

    # Specific cancer types
    TargetRule("carcinoma", "PROBLEM"),
    TargetRule("adenocarcinoma", "PROBLEM"),
    TargetRule("sarcoma", "PROBLEM"),
    TargetRule("melanoma", "PROBLEM"),
    TargetRule("glioma", "PROBLEM"),
    TargetRule("glioblastoma", "PROBLEM"),
    TargetRule("leukemia", "PROBLEM"),
    TargetRule("leukaemia", "PROBLEM"),
    TargetRule("lymphoma", "PROBLEM"),
    TargetRule("myeloma", "PROBLEM"),

    # Metastasis
    TargetRule("metastatic", "PROBLEM"),
    TargetRule("metastasis", "PROBLEM"),
    TargetRule("metastases", "PROBLEM"),

    # Neoplasm
    TargetRule("neoplasm", "PROBLEM"),
    TargetRule("neoplastic", "PROBLEM"),

    # Add Healthy & Normal
    TargetRule("healthy","HEALTHY"),
    TargetRule("normal","HEALTHY")
]

# Add all rules to the target matcher
target_matcher.add(cancer_rules)

print(f"✓ Added {len(cancer_rules)} cancer-related target rules to medspacy")

✓ Added 25 cancer-related target rules to medspacy

In [58]:
import medspacy
help(medspacy.ner.TargetRule)

Help on class TargetRule in module medspacy.target_matcher.target_rule:

class TargetRule(medspacy.common.base_rule.BaseRule)
 |  TargetRule(literal: 'str', category: 'str', pattern: 'Optional[Union[List[Dict[str, str]], str]]' = None, on_match: 'Optional[Callable[[Matcher, Doc, int, List[Tuple[int, int, int]]], Any]]' = None, attributes: 'Optional[Dict[str, Any]]' = None, metadata: 'Optional[Dict[Any, Any]]' = None)
 |
 |  TargetRule defines rules for extracting entities from text using the TargetMatcher.
 |
 |  Method resolution order:
 |      TargetRule
 |      medspacy.common.base_rule.BaseRule
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __init__(self, literal: 'str', category: 'str', pattern: 'Optional[Union[List[Dict[str, str]], str]]' = None, on_match: 'Optional[Callable[[Matcher, Doc, int, List[Tuple[int, int, int]]], Any]]' = None, attributes: 'Optional[Dict[str, Any]]' = None, metadata: 'Optional[Dict[Any, Any]]' = None)
 |      Creates a new TargetRule.
 |
 |      Args:
 |          literal: The string representation of a concept. If `pattern` is None, this string will be lower-cased and
 |              matched to the lower-case string. If `pattern` is not None, this argument will not be used for matching
 |              but can be used as a reference as the rule name.
 |          category: The semantic class of the matched span. This corresponds to the `label_` attribute of an entity.
 |          pattern: A list or string to use as a spaCy pattern rather than `literal`. If a list, will use spaCy
 |              token-based pattern matching to match using token attributes. If a string, will use medspaCy's
 |              RegexMatcher. If None, will use `literal` as the pattern for phrase matching. For more information, see
 |              https://spacy.io/usage/rule-based-matching.
 |          on_match: An optional callback function or other callable which takes 4 arguments: `(matcher, doc, i,
 |              matches)`. For more information, see https://spacy.io/usage/rule-based-matching#on_match
 |          attributes: Optional custom attribute names to set for a Span matched by the direction. These attribute
 |              names are stored under Span._.[attribute_name]. For example, if `attributes={'is_historical':True}`,
 |              then any spans matched by this direction will have span._.is_historical = True
 |          metadata: Optional dictionary of any extra metadata.
 |
 |  __repr__(self)
 |      Return repr(self).
 |
 |  to_dict(self)
 |      Converts TargetRules to a python dictionary. Used when writing target rules to a json file.
 |
 |      Returns:
 |          The dictionary containing the TargetRule info.
 |
 |  ----------------------------------------------------------------------
 |  Class methods defined here:
 |
 |  from_dict(rule_dict: 'Dict') -> 'TargetRule'
 |      Reads a dictionary into a ConTextRule. Used when reading from a json file.
 |
 |      Args:
 |          rule_dict: the dictionary to convert
 |
 |      Returns:
 |          The ConTextRule created from the dictionary
 |
 |      Raises:
 |          ValueError: if the json is invalid
 |
 |  from_json(filepath: 'str') -> 'List[TargetRule]'
 |      Read in a lexicon of modifiers from a JSON file.
 |
 |      Args:
 |          filepath: the .json file containing modifier rules
 |
 |      Returns:
 |          context_item: A list of ConTextRule objects.
 |
 |      Raises:
 |          KeyError: If the dictionary contains any keys other than
 |              those accepted by ConTextRule.__init__
 |
 |  to_json(target_rules: 'List[TargetRule]', filepath: 'str')
 |      Writes ConTextItems to a json file.
 |
 |      Args:
 |          target_rules: a list of TargetRules that will be written to a file.
 |          filepath: the .json file to contain modifier rules
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from medspacy.common.base_rule.BaseRule:
 |
 |  __dict__
 |      dictionary for instance variables
 |
 |  __weakref__
 |      list of weak references to the object

In [59]:
# Re-test with TargetMatcher configured
test_texts = [
    "breast cancer tissue",
    "normal breast tissue",
    "no evidence of tumor",
    "tumor sample from lung",
    "cancer cell line",
    "adjacent normal tissue",
    "metastatic carcinoma",
    "healthy control sample",
    "glioblastoma multiforme",
    "non-tumor breast tissue"
]

print("=" * 80)
print("TESTING WITH TARGET MATCHER")
print("=" * 80)

for text in test_texts:
    doc = nlp(text)

    print(f"\nText: '{text}'")

    if doc.ents:
        for ent in doc.ents:
            negated = "✗ NEGATED" if ent._.is_negated else "✓ AFFIRMED"
            print(f"  Entity: '{ent.text}' | Label: {ent.label_} | {negated}")
    else:
        print(f"  ✗ NO ENTITIES DETECTED")

print("\n" + "=" * 80)

2025-10-28 13:25:35.629 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1411] [doc 0] Token 0 'breast' marked as sentence start (span begin)
2025-10-28 13:25:35.630 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1411] Token/tag mapping: [(breast, True), (cancer, False), (tissue, False)]
2025-10-28 13:25:35.632 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1412] [doc 0] Token 0 'normal' marked as sentence start (span begin)
2025-10-28 13:25:35.633 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1412] Token/tag mapping: [(normal, True), (breast, False), (tissue, False)]
2025-10-28 13:25:35.634 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1413] [doc 0] Token 0 'no' marked as sentence start (span begin)
2025-10-28 13:25:35.634 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1413] Token/tag mapping: [(no, True), (evidence, False), (of, False), (tumor, False)]
2025-10-28 13:25:35.636 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1414] [doc 0] Token 0 'tumor' marked as sentence start (span begin)
2025-10-28 13:25:35.636 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1414] Token/tag mapping: [(tumor, True), (sample, False), (from, False), (lung, False)]
2025-10-28 13:25:35.637 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1415] [doc 0] Token 0 'cancer' marked as sentence start (span begin)
2025-10-28 13:25:35.638 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1415] Token/tag mapping: [(cancer, True), (cell, False), (line, False)]
2025-10-28 13:25:35.639 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1416] [doc 0] Token 0 'adjacent' marked as sentence start (span begin)
2025-10-28 13:25:35.639 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1416] Token/tag mapping: [(adjacent, True), (normal, False), (tissue, False)]
2025-10-28 13:25:35.641 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1417] [doc 0] Token 0 'metastatic' marked as sentence start (span begin)
2025-10-28 13:25:35.641 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1417] Token/tag mapping: [(metastatic, True), (carcinoma, False)]
2025-10-28 13:25:35.642 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1418] [doc 0] Token 0 'healthy' marked as sentence start (span begin)
2025-10-28 13:25:35.643 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1418] Token/tag mapping: [(healthy, True), (control, False), (sample, False)]
2025-10-28 13:25:35.645 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1419] [doc 0] Token 0 'glioblastoma' marked as sentence start (span begin)
2025-10-28 13:25:35.646 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1419] Token/tag mapping: [(glioblastoma, True), (multiforme, False)]
2025-10-28 13:25:35.648 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1420] [doc 0] Token 0 'non' marked as sentence start (span begin)
2025-10-28 13:25:35.648 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1420] Token/tag mapping: [(non, True), (-, False), (tumor, False), (breast, False), (tissue, False)]

================================================================================
TESTING WITH TARGET MATCHER
================================================================================

Text: 'breast cancer tissue'
  Entity: 'cancer' | Label: PROBLEM | ✓ AFFIRMED

Text: 'normal breast tissue'
  Entity: 'normal' | Label: HEALTHY | ✓ AFFIRMED

Text: 'no evidence of tumor'
  Entity: 'tumor' | Label: PROBLEM | ✗ NEGATED

Text: 'tumor sample from lung'
  Entity: 'tumor' | Label: PROBLEM | ✓ AFFIRMED

Text: 'cancer cell line'
  Entity: 'cancer' | Label: PROBLEM | ✓ AFFIRMED

Text: 'adjacent normal tissue'
  Entity: 'normal' | Label: HEALTHY | ✓ AFFIRMED

Text: 'metastatic carcinoma'
  Entity: 'metastatic' | Label: PROBLEM | ✓ AFFIRMED
  Entity: 'carcinoma' | Label: PROBLEM | ✓ AFFIRMED

Text: 'healthy control sample'
  Entity: 'healthy' | Label: HEALTHY | ✓ AFFIRMED

Text: 'glioblastoma multiforme'
  Entity: 'glioblastoma' | Label: PROBLEM | ✓ AFFIRMED

Text: 'non-tumor breast tissue'
  Entity: 'tumor' | Label: PROBLEM | ✓ AFFIRMED

================================================================================