In [71]:
import polars as pl

def classify_cancer_samples(df: pl.DataFrame) -> pl.DataFrame:
    """
    Classify samples as cancer / non-cancer / uncertain based on metadata text patterns.
    Returns the same DataFrame with added classification columns.
    """

    # --- Step 1: Setup ---
    PRIORITY_COLS = ["source_name", "tissue", "phenotype", "disease", "cell_type", "tumor_type"]
    PRIORITY_COLS = [c for c in PRIORITY_COLS if c in df.columns]

    # Regex patterns
    CANCER_POS = r"(?:\bcancers?\b|\btumou?rs?\b|\bmalignan(?:t|cy)\b|\bcarcinomas?\b|\bneoplasms?\b|\bmetasta(?:s|t)es?\b|\badenocarcinomas?\b|\bsarcomas?\b|\bleukemi(?:a|as)\b|\blymphom(?:a|as)\b|\bglioblastomas?\b|\bmelanomas?\b|\boncolog(?:y|ic|ical)\b)"
    CANCER_NEG = r"(?:\bnormal\b|\bhealthy\b|\bctrl\b|\badjacent normal\b|\bnon[-\s]?tumou?r(?:al)?\b|\bbenign\b|\bnon[-\s]?cancer(?:ous)?\b|\bsham\b|\bunaffected\b)"
    ONCO_TRAPS = r"(?:\boncophora\b|\boncorhynchus\b|\boncotic\b|\boncomodulin\b)"

    # Helper to normalize text columns
    def normalize_text(col_expr):
        return (
            col_expr.cast(pl.Utf8)
            .fill_null("")
            .str.to_lowercase()
            .str.replace_all(r"[_/|]", " ")
            .str.replace_all(r"\s+", " ")
            .str.strip_chars()
        )

    # --- Step 2: Sample name detection ---
    sample_name_col = "title" if "title" in df.columns else "biosample"

    df = df.with_columns([
        normalize_text(pl.col(sample_name_col)).str.contains(CANCER_POS).alias("cancer_in_sample_name"),
        normalize_text(pl.col(sample_name_col)).str.contains(CANCER_NEG).alias("negative_in_sample_name"),
        normalize_text(pl.col(sample_name_col)).str.contains(ONCO_TRAPS).alias("onco_trap_in_sample_name"),
    ])

    # --- Step 3: Check priority columns ---
    for col in PRIORITY_COLS:
        df = df.with_columns([
            normalize_text(pl.col(col)).str.contains(CANCER_POS).alias(f"cancer_in_{col}"),
            normalize_text(pl.col(col)).str.contains(CANCER_NEG).alias(f"negative_in_{col}"),
        ])

    # --- Step 4: Count mentions ---
    cancer_mention_cols = [f"cancer_in_{c}" for c in PRIORITY_COLS]
    negative_mention_cols = [f"negative_in_{c}" for c in PRIORITY_COLS]

    df = df.with_columns([
        pl.sum_horizontal([pl.col(c) for c in cancer_mention_cols if c in df.columns]).alias("n_cancer_mentions"),
        pl.sum_horizontal([pl.col(c) for c in negative_mention_cols if c in df.columns]).alias("n_negative_mentions"),
    ])

    # --- Step 5: Confidence category ---
    df = df.with_columns([
        pl.when(pl.col("onco_trap_in_sample_name"))
        .then(pl.lit("uncertain_onco_trap"))
        .when(
            pl.col("cancer_in_sample_name") &
            (pl.col("n_cancer_mentions") >= 1) &
            (pl.col("n_negative_mentions") == 0)
        )
        .then(pl.lit("confident_cancer"))
        .when(
            (pl.col("cancer_in_sample_name") & (pl.col("n_negative_mentions") == 0)) |
            (pl.col("n_cancer_mentions") >= 2)
        )
        .then(pl.lit("likely_cancer"))
        .when(
            pl.col("negative_in_sample_name") |
            (pl.col("n_negative_mentions") >= 1)
        )
        .then(pl.lit("likely_non_cancer"))
        .when(pl.col("n_cancer_mentions") == 1)
        .then(pl.lit("uncertain_weak_signal"))
        .otherwise(pl.lit("uncertain_no_signal"))
        .alias("confidence_category")
    ])

    return df

In [72]:
full_dataset = pl.read_csv(
    "data/combined_metadata_noncancer_removed.csv",
    schema_overrides={"group": pl.Utf8},   # <- dict of {col_name: dtype}
    infer_schema_length=0,                  # scan entire file for other cols
)

df = pl.read_csv("data/train_test.csv")

In [73]:
df = df[["experiment_accession", "bioproject", "biosample", "sample_accession","run_accession", "is_cancer"]]

# idx = full_dataset.columns.index("cancer_type")

# full_dataset = full_dataset[full_dataset.columns[:idx+1]]

In [74]:
df.head()

# full_dataset.head()

shape: (5, 6)
┌──────────────────────┬─────────────┬──────────────┬──────────────────┬───────────────┬───────────┐
│ experiment_accession ┆ bioproject  ┆ biosample    ┆ sample_accession ┆ run_accession ┆ is_cancer │
│ ---                  ┆ ---         ┆ ---          ┆ ---              ┆ ---           ┆ ---       │
│ str                  ┆ str         ┆ str          ┆ str              ┆ str           ┆ i64       │
╞══════════════════════╪═════════════╪══════════════╪══════════════════╪═══════════════╪═══════════╡
│ SRX10489019          ┆ PRJNA718814 ┆ GSM5220969   ┆ SRS8615268       ┆ SRR14118670   ┆ 1         │
│ ERX1283444           ┆ PRJEB6455   ┆ SAMEA3724868 ┆ ERS1032017       ┆ ERR1211193    ┆ 0         │
│ SRX17708205          ┆ PRJNA884362 ┆ GSM6601021   ┆ SRS15238722      ┆ SRR21710838   ┆ 1         │
│ SRX4518392           ┆ PRJNA484951 ┆ GSM3323504   ┆ SRS3636903       ┆ SRR7655999    ┆ 0         │
│ SRX9364181           ┆ PRJNA671877 ┆ GSM4860401   ┆ SRS7586602       ┆ SRR12899131   ┆ 0         │
└──────────────────────┴─────────────┴──────────────┴──────────────────┴───────────────┴───────────┘

In [75]:
joined = full_dataset.join(
    df,
    on=["experiment_accession", "bioproject", "biosample", "sample_accession", "run_accession"],  # matching keys
    how="inner"  # keep only matching rows
)

In [76]:
predicted_df = classify_cancer_samples(joined)

In [77]:
# find the position of "cancer_type"
idx = predicted_df.columns.index("cancer_type")

# slice up to that column (inclusive)
cols_to_keep = predicted_df.columns[:idx + 1]

# add the two specific extra columns
cols_to_keep += ["is_cancer", "confidence_category"]

predicted_df.select(cols_to_keep)

shape: (172, 40)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ experimen ┆ experimen ┆ title     ┆ study_nam ┆ … ┆ n_count  ┆ cancer_ty ┆ is_cancer ┆ confidenc │
│ t_alias   ┆ t_accessi ┆ ---       ┆ e         ┆   ┆ ---      ┆ pe        ┆ ---       ┆ e_categor │
│ ---       ┆ on        ┆ str       ┆ ---       ┆   ┆ str      ┆ ---       ┆ i64       ┆ y         │
│ str       ┆ ---       ┆           ┆ str       ┆   ┆          ┆ str       ┆           ┆ ---       │
│           ┆ str       ┆           ┆           ┆   ┆          ┆           ┆           ┆ str       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ ena-EXPER ┆ ERX352605 ┆ Illumina  ┆ null      ┆ … ┆ 2525599  ┆ carcinoma ┆ 0         ┆ likely_no │
│ IMENT-FUN ┆ 7         ┆ HiSeq     ┆           ┆   ┆          ┆           ┆           ┆ n_cancer  │
│ CTIONAL   ┆           ┆ 2500      ┆           ┆   ┆          ┆           ┆           ┆           │
│ GENO…     ┆           ┆ paired    ┆           ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆ end…      ┆           ┆   ┆          ┆           ┆           ┆           │
│ GSM486040 ┆ SRX936418 ┆ GSM486040 ┆ null      ┆ … ┆ 6787073  ┆ tumor*    ┆ 0         ┆ likely_no │
│ 0         ┆ 0         ┆ 0: Fresh- ┆           ┆   ┆          ┆           ┆           ┆ n_cancer  │
│           ┆           ┆ frozen    ┆           ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆ canin…    ┆           ┆   ┆          ┆           ┆           ┆           │
│ GSM486040 ┆ SRX936418 ┆ GSM486040 ┆ null      ┆ … ┆ 14821009 ┆ tumor*    ┆ 0         ┆ likely_no │
│ 1         ┆ 1         ┆ 1: Fresh- ┆           ┆   ┆          ┆           ┆           ┆ n_cancer  │
│           ┆           ┆ frozen    ┆           ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆ canin…    ┆           ┆   ┆          ┆           ┆           ┆           │
│ GSM300511 ┆ SRX139997 ┆ GSM300511 ┆ null      ┆ … ┆ 2648204  ┆ bladder   ┆ 0         ┆ likely_no │
│ 1         ┆ 82        ┆ 1: D_Norm ┆           ┆   ┆          ┆ cancer    ┆           ┆ n_cancer  │
│           ┆           ┆ al_Mucosa ┆           ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆ ; C…      ┆           ┆   ┆          ┆           ┆           ┆           │
│ GSM249835 ┆ SRX258189 ┆ GSM249835 ┆ null      ┆ … ┆ 2991046  ┆ tumor*    ┆ 1         ┆ uncertain │
│ 7         ┆ 9         ┆ 7:        ┆           ┆   ┆          ┆           ┆           ┆ _no_signa │
│           ┆           ┆ CHAD-P9;  ┆           ┆   ┆          ┆           ┆           ┆ l         │
│           ┆           ┆ Canis     ┆           ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆ lup…      ┆           ┆   ┆          ┆           ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …         ┆ …         ┆ …         │
│ GSM318787 ┆ SRX420033 ┆ GSM318787 ┆ null      ┆ … ┆ 5364090  ┆ rhabdomyo ┆ 1         ┆ uncertain │
│ 6         ┆ 4         ┆ 6: Rh30:  ┆           ┆   ┆          ┆ sarcoma   ┆           ┆ _weak_sig │
│           ┆           ┆ RH30_ENT; ┆           ┆   ┆          ┆           ┆           ┆ nal       │
│           ┆           ┆ Mu…       ┆           ┆   ┆          ┆           ┆           ┆           │
│ GSM357314 ┆ SRX527294 ┆ GSM357314 ┆ null      ┆ … ┆ 189230   ┆ tumor*    ┆ 1         ┆ likely_no │
│ 0         ┆ 6         ┆ 0: SAM243 ┆           ┆   ┆          ┆           ┆           ┆ n_cancer  │
│           ┆           ┆ 42223     ┆           ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆ Macrop…   ┆           ┆   ┆          ┆           ┆           ┆           │
│ GSM357315 ┆ SRX527295 ┆ GSM357315 ┆ null      ┆ … ┆ 205251   ┆ tumor*    ┆ 1         ┆ likely_no │
│ 0         ┆ 6         ┆ 0: SAM243 ┆           ┆   ┆          ┆           ┆           ┆ n_cancer  │
│           ┆           ┆ 42227     ┆           ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆ Macrop…   ┆           ┆   ┆          ┆           ┆           ┆           │
│ GSM361182 ┆ SRX538990 ┆ GSM361182 ┆ null      ┆ … ┆ 17061    ┆ tumor*    ┆ 1         ┆ confident │
│ 3         ┆ 0         ┆ 3: Tumor  ┆           ┆   ┆          ┆           ┆           ┆ _cancer   │
│           ┆           ┆ 5_non-PoE ┆           ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆ Ms;…      ┆           ┆   ┆          ┆           ┆           ┆           │
│ GSM403702 ┆ SRX672076 ┆ GSM403702 ┆ null      ┆ … ┆ 2310298  ┆ hepatocel ┆ 1         ┆ likely_ca │
│ 9         ┆ 4         ┆ 9: MYC_Tw ┆           ┆   ┆          ┆ lular     ┆           ┆ ncer      │
│           ┆           ┆ ist1_HCC_ ┆           ┆   ┆          ┆ cancer    ┆           ┆           │
│           ┆           ┆ 5; …      ┆           ┆   ┆          ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

In [78]:
import spacy
import medspacy

# Option 1: Use medspacy pipeline directly
nlp = medspacy.load()

# Option 2: If you need to add to existing pipeline
# Load medspacy and copy the context component
negex = medspacy.load()
nlp.add_pipe("medspacy_context", source=negex, name="context", last=True)

In [79]:
text = "No evidence of metastatic cancer in the liver."

doc = nlp(text)
for ent in doc.ents:
    print(ent.text, ent._.is_negated, ent._.is_family, ent._.is_historical)

2025-10-28 01:39:48.693 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3357] [doc 0] Token 0 'No' marked as sentence start (span begin)
2025-10-28 01:39:48.693 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3357] Token/tag mapping: [(No, True), (evidence, False), (of, False), (metastatic, False), (cancer, False), (in, False), (the, False), (liver, False), (., False)]

In [80]:
import re

def clean_tissue(val: str) -> str:
    if not val or val.lower() == "nan":
        return None
    val = re.sub(r"\s+", " ", val.strip())
    tokens = [t for t in val.split() if t.lower() != "nan"]
    cleaned = []
    for t in tokens:
        if not cleaned or cleaned[-1].lower() != t.lower():
            cleaned.append(t)
    return " ".join(cleaned)

## First medspaCy

In [81]:
import spacy
import medspacy

# Load medspacy pipeline once (global scope for efficiency)
nlp = medspacy.load()


def analyze_text_with_spacy(text: str) -> dict:
    """
    Use spaCy/medspacy to detect cancer terms and check if they're negated.
    Returns a dict with: has_cancer_term, has_negated_cancer, has_confirmed_cancer
    """
    if not text or not isinstance(text, str) or not text.strip():
        return {
            "has_cancer_term": False,
            "has_negated_cancer": False,
            "has_confirmed_cancer": False
        }

    # Define cancer-related terms
    cancer_terms = [
        "cancer", "tumor", "tumour", "malignant", "malignancy",
        "carcinoma", "neoplasm", "metastatic", "metastasis",
        "adenocarcinoma", "sarcoma", "leukemia", "leukaemia",
        "lymphoma", "glioblastoma", "melanoma"
    ]

    doc = nlp(text.lower())

    has_cancer_term = False
    has_negated_cancer = False
    has_confirmed_cancer = False

    # Check entities detected by medspacy
    for ent in doc.ents:
        # Check if entity contains cancer-related terms
        if any(term in ent.text for term in cancer_terms):
            has_cancer_term = True

            # Check negation using medspacy's context detection
            if hasattr(ent._, "is_negated") and ent._.is_negated:
                has_negated_cancer = True
            else:
                has_confirmed_cancer = True

    # Fallback: if no entities but cancer terms present in text
    if not has_cancer_term and any(term in text.lower() for term in cancer_terms):
        # Run a simple token check
        tokens = text.lower().split()
        for term in cancer_terms:
            if term in tokens:
                has_cancer_term = True
                # Simple negation check for standalone terms
                idx = tokens.index(term)
                if idx > 0 and tokens[idx - 1] in ["no", "not", "without", "negative"]:
                    has_negated_cancer = True
                else:
                    has_confirmed_cancer = True
                break

    return {
        "has_cancer_term": has_cancer_term,
        "has_negated_cancer": has_negated_cancer,
        "has_confirmed_cancer": has_confirmed_cancer
    }

In [82]:
def classify_cancer_samples(df: pl.DataFrame) -> pl.DataFrame:
    """
    Classify samples as cancer / non-cancer / uncertain using spaCy NLP.
    Returns the same DataFrame with added classification columns.
    """

    # --- Step 1: Setup ---
    PRIORITY_COLS = ["source_name", "tissue", "phenotype", "disease", "cell_type", "tumor_type"]
    PRIORITY_COLS = [c for c in PRIORITY_COLS if c in df.columns]

    # Onco-traps pattern (still useful for false positives)
    ONCO_TRAPS = r"(?:\boncophora\b|\boncorhynchus\b|\boncotic\b|\boncomodulin\b)"

    # Helper to normalize text columns
    def normalize_text(col_expr):
        return (
            col_expr.cast(pl.Utf8)
            .fill_null("")
            .str.to_lowercase()
            .str.replace_all(r"[_/|]", " ")
            .str.replace_all(r"\s+", " ")
            .str.strip_chars()
        )
    # --- Step 1.5: Clean tissue column if present ---
    if "tissue" in df.columns:
        df = df.with_columns(
            pl.col("tissue").map_elements(clean_tissue, return_dtype=pl.Utf8)
        )

    # --- Step 2: Sample name detection using spaCy ---
    sample_name_col = "title" if "title" in df.columns else "biosample"

    # Extract texts directly from Polars (no pandas conversion)
    sample_texts = df.select(normalize_text(pl.col(sample_name_col)).alias("text"))["text"].to_list()

    # Analyze each sample name with spaCy
    spacy_results = [analyze_text_with_spacy(text) for text in sample_texts]

    df = df.with_columns([
        pl.Series("cancer_in_sample_name", [r["has_confirmed_cancer"] for r in spacy_results]),
        pl.Series("negative_in_sample_name", [r["has_negated_cancer"] for r in spacy_results]),
        normalize_text(pl.col(sample_name_col)).str.contains(ONCO_TRAPS).alias("onco_trap_in_sample_name"),
    ])

    # --- Step 3: Check priority columns with spaCy ---
    for col in PRIORITY_COLS:
        # Extract texts directly from Polars (no pandas conversion)
        col_texts = df.select(normalize_text(pl.col(col)).alias("text"))["text"].to_list()
        col_results = [analyze_text_with_spacy(text) for text in col_texts]

        df = df.with_columns([
            pl.Series(f"cancer_in_{col}", [r["has_confirmed_cancer"] for r in col_results]),
            pl.Series(f"negative_in_{col}", [r["has_negated_cancer"] for r in col_results]),
        ])

    # --- Step 4: Count mentions ---
    cancer_mention_cols = [f"cancer_in_{c}" for c in PRIORITY_COLS]
    negative_mention_cols = [f"negative_in_{c}" for c in PRIORITY_COLS]

    df = df.with_columns([
        pl.sum_horizontal([pl.col(c) for c in cancer_mention_cols if c in df.columns]).alias("n_cancer_mentions"),
        pl.sum_horizontal([pl.col(c) for c in negative_mention_cols if c in df.columns]).alias("n_negative_mentions"),
    ])

    # --- Step 5: Confidence category ---
    df = df.with_columns([
        pl.when(pl.col("onco_trap_in_sample_name"))
        .then(pl.lit("uncertain_onco_trap"))
        .when(
            pl.col("cancer_in_sample_name") &
            (pl.col("n_cancer_mentions") >= 1) &
            (pl.col("n_negative_mentions") == 0)
        )
        .then(pl.lit("confident_cancer"))
        .when(
            (pl.col("cancer_in_sample_name") & (pl.col("n_negative_mentions") == 0)) |
            (pl.col("n_cancer_mentions") >= 2)
        )
        .then(pl.lit("likely_cancer"))
        .when(
            pl.col("negative_in_sample_name") |
            (pl.col("n_negative_mentions") >= 1)
        )
        .then(pl.lit("likely_non_cancer"))
        .when(pl.col("n_cancer_mentions") == 1)
        .then(pl.lit("uncertain_weak_signal"))
        .otherwise(pl.lit("uncertain_no_signal"))
        .alias("confidence_category")
    ])

    # --- Step 6: Binary classification (1 = cancer, 0 = not cancer) ---
    df = df.with_columns([
        pl.when(pl.col("confidence_category").is_in(["confident_cancer", "likely_cancer"]))
        .then(pl.lit(1))
        .otherwise(pl.lit(0))
        .alias("predicted_cancer_binary")
    ])

    return df

In [83]:
predicted_df = classify_cancer_samples(joined)

2025-10-28 01:39:52.116 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3358] [doc 0] Token 0 'illumina' marked as sentence start (span begin)
2025-10-28 01:39:52.116 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3358] Token/tag mapping: [(illumina, True), (hiseq, False), (2500, False), (paired, False), (end, False), (sequencing, False)]
2025-10-28 01:39:52.118 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3359] [doc 0] Token 0 'gsm4860400' marked as sentence start (span begin)
2025-10-28 01:39:52.119 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3359] Token/tag mapping: [(gsm4860400, True), (:, False), (fresh, False), (-, False), (frozen, False), (canine, False), (healthy, False), (brain, False), (tissue, False), (-, False), (dog, False), (no, False), (., False), (60459, False), (;, False), (canis, False), (lupus, False), (familiaris, False), (;, False), (rna, False), (-, False), (seq, False)]
2025-10-28 01:39:52.121 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3360] [doc 0] Token 0 'gsm4860401' marked as sentence start (span begin)
2025-10-28 01:39:52.122 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3360] Token/tag mapping: [(gsm4860401, True), (:, False), (fresh, False), (-, False), (frozen, False), (canine, False), (healthy, False), (brain, False), (tissue, False), (-, False), (dog, False), (no, False), (., False), (60460, False), (;, False), (canis, False), (lupus, False), (familiaris, False), (;, False), (rna, False), (-, False), (seq, False)]
2025-10-28 01:39:52.124 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3361] [doc 0] Token 0 'gsm3005111' marked as sentence start (span begin)
2025-10-28 01:39:52.124 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3361] Token/tag mapping: [(gsm3005111, True), (:, False), (d, False), (normal, False), (mucosa, False), (;, False), (canis, False), (lupus, False), (familiaris, False), (;, False), (rna, False), (-, False), (seq, False)]
2025-10-28 01:39:52.125 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3362] [doc 0] Token 0 'gsm2498357' marked as sentence start (span begin)
2025-10-28 01:39:52.126 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3362] Token/tag mapping: [(gsm2498357, True), (:, False), (chad, False), (-, False), (p9, False), (;, False), (canis, False), (lupus, False), (familiaris, False), (;, False), (rna, False), (-, False), (seq, False)]
2025-10-28 01:39:52.127 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3363] [doc 0] Token 0 'whole' marked as sentence start (span begin)
2025-10-28 01:39:52.127 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3363] Token/tag mapping: [(whole, True), (exome, False), (sequencing, False), (of, False), (canine, False), (mucosal, False), (melanoma, False)]
2025-10-28 01:39:52.128 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3364] [doc 0] Token 0 'gsm3384215' marked as sentence start (span begin)
2025-10-28 01:39:52.129 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3364] Token/tag mapping: [(gsm3384215, True), (:, False), (cmt, False), (-, False), (121, False), (-, False), (normal, False), (;, False), (canis, False), (lupus, False), (familiaris, False), (;, False), (rna, False), (-, False), (seq, False)]
2025-10-28 01:39:52.130 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3365] [doc 0] Token 0 'gsm3384243' marked as sentence start (span begin)
2025-10-28 01:39:52.130 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3365] Token/tag mapping: [(gsm3384243, True), (:, False), (cmt, False), (-, False), (193, False), (-, False), (normal, False), (;, False), (canis, False), (lupus, False), (familiaris, False), (;, False), (rna, False), (-, False), (seq, False)]
2025-10-28 01:39:52.132 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3366] [doc 0] Token 0 'gsm3384261' marked as sentence start (span begin)
2025-10-28 01:39:52.132 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3366] Token/tag mapping: [(gsm3384261, True), (:, False), (cmt, False), (-, False), (232, False), (-, False), (normal, False), (;, False), (canis, False), (lupus, False), (familiaris, False), (;, False), (rna, False), (-, False), (seq, False)]
2025-10-28 01:39:52.134 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3367] [doc 0] Token 0 '32510' marked as sentence start (span begin)
2025-10-28 01:39:52.135 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3367] Token/tag mapping: [(32510, True), (rna, False), (-, False), (seq, False), (of, False), (spontaneous, False), (canine, False), (mammary, False), (cancers, False), (and, False), (matching, False), (normal, False), (samples, False)]
2025-10-28 01:39:52.136 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3368] [doc 0] Token 0 'gsm3993105' marked as sentence start (span begin)
2025-10-28 01:39:52.136 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3368] Token/tag mapping: [(gsm3993105, True), (:, False), (normal, False), (stroma, False), (123, False), (norm, False), (;, False), (canis, False), (lupus, False), (familiaris, False), (;, False), (rna, False), (-, False), (seq, False)]
2025-10-28 01:39:52.139 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3369] [doc 0] Token 0 'illumina' marked as sentence start (span begin)
2025-10-28 01:39:52.140 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3369] Token/tag mapping: [(illumina, True), (hiseq, False), (4000, False), (paired, False), (end, False), (sequencing, False), (;, False), (whole, False), (transcriptome, False), (analysis, False), (of, False), (rat, False), (peritoneal, False), (cells, False), (in, False), (a, False), (tgfβ1, False), (induced, False), (mesothelial, False), (-, False), (to, False), (-, False), (mesenchymal, False), (transition, False)]
2025-10-28 01:39:52.142 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3370] [doc 0] Token 0 'rna' marked as sentence start (span begin)
2025-10-28 01:39:52.142 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3370] Token/tag mapping: [(rna, True), (-, False), (seq, False), (of, False), (rattus, False), (norvegicusreplication, False), (2, False), (of, False), (untreated, False), (poorly, False), (differentiated, False), (pc12, False), (cells, False)]
2025-10-28 01:39:52.143 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3371] [doc 0] Token 0 'gsm5957075' marked as sentence start (span begin)
2025-10-28 01:39:52.144 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3371] Token/tag mapping: [(gsm5957075, True), (:, False), (osteosarcoma, False), (from, False), (p53r245w, False), (+, False), (gigi, False), (r245w, False), (16, False), (22, False), (;, False), (mus, False), (musculus, False), (;, False), (rna, False), (-, False), (seq, False)]
2025-10-28 01:39:52.144 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3372] [doc 0] Token 0 'nextseq' marked as sentence start (span begin)
2025-10-28 01:39:52.145 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3372] Token/tag mapping: [(nextseq, True), (500, False), (sequencing, False)]
2025-10-28 01:39:52.150 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3373] [doc 0] Token 0 'nan' marked as sentence start (span begin)
2025-10-28 01:39:52.150 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3373] Token/tag mapping: [(nan, True), (illumina, False), (hiseq, False), (2000, False), (paired, False), (end, False), (sequencing, False), (;, False), (single, False), (cell, False), (mrna, False), (-sequencing, False), (reveals, False), (cell, False), (-, False), (to, False), (-, False), (cell, False), (variation, False), (in, False), (three, False), (mouse, False), (es, False), (cell, False), (culture, False), (conditions, False), (nan, False), (nan, False), (illumina, False), (hiseq, False), (2000, False), (paired, False), (end, False), (sequencing, False), (;, False), (single, False), (cell, False), (mrna, False), (-sequencing, False), (reveals, False), (cell, False), (-, False), (to, False), (-, False), (cell, False), (variation, False), (in, False), (three, False), (mouse, False), (es, False), (cell, False), (culture, False), (conditions, False), (nan, False)]
2025-10-28 01:39:52.152 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3374] [doc 0] Token 0 'bulk' marked as sentence start (span begin)
2025-10-28 01:39:52.152 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3374] Token/tag mapping: [(bulk, True), (rna, False), (-, False), (seq, False), (of, False), (cd4, False), (t, False), (cells, False), (from, False), (mice, False), (with, False), (mc38, False), (tumors, False)]
2025-10-28 01:39:52.155 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3375] [doc 0] Token 0 'illumina' marked as sentence start (span begin)
2025-10-28 01:39:52.155 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3375] Token/tag mapping: [(illumina, True), (hiseq, False), (4000, False), (sequencing, False), (;, False), (rna, False), (-, False), (seq, False), (of, False), (mus, False), (musculus, False), (beta, False), (cells, False), (to, False), (determine, False), (the, False), (role, False), (of, False), (the, False), (mir, False), (-, False), (200, False), (–, False), (zeb1, False), (axis, False), (in, False), (beta, False), (cell, False), (tumor, False), (development, False)]
2025-10-28 01:39:52.158 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3376] [doc 0] Token 0 'illumina' marked as sentence start (span begin)
2025-10-28 01:39:52.158 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3376] Token/tag mapping: [(illumina, True), (hiseq, False), (2500, False), (sequencing, False), (;, False), (regional, False), (cns, False), (immune, False), (fingerprint, False), (in, False), (chronic, False), (peripheral, False), (inflammation, False)]
2025-10-28 01:39:52.160 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3377] [doc 0] Token 0 'illumina' marked as sentence start (span begin)
2025-10-28 01:39:52.160 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3377] Token/tag mapping: [(illumina, True), (hiseq, False), (4000, False), (sequencing, False), (;, False), (rna, False), (-, False), (seq, False), (analysis, False), (of, False), (macrophages, False), (from, False), (normal, False), (and, False), (tumor, False), (-, False), (infiltrated, False), (omentum, False)]
2025-10-28 01:39:52.161 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3378] [doc 0] Token 0 'nextseq' marked as sentence start (span begin)
2025-10-28 01:39:52.162 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3378] Token/tag mapping: [(nextseq, True), (500, False), (paired, False), (end, False), (sequencing, False)]
2025-10-28 01:39:52.164 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3379] [doc 0] Token 0 'illumina' marked as sentence start (span begin)
2025-10-28 01:39:52.164 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3379] Token/tag mapping: [(illumina, True), (miseq, False), (paired, False), (end, False), (sequencing, False), (;, False), (complement, False), (c3ar, False), (acts, False), (as, False), (an, False), (oncosuppressor, False), (in, False), (colorectal, False), (cancer, False), (by, False), (modulating, False), (gut, False), (microbiota, False)]
2025-10-28 01:39:52.166 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3380] [doc 0] Token 0 'illumina' marked as sentence start (span begin)
2025-10-28 01:39:52.167 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3380] Token/tag mapping: [(illumina, True), (hiseq, False), (4000, False), (paired, False), (end, False), (sequencing, False), (;, False), (scrnaseq, False), (of, False), (cyp11a1, False), (-, False), (expressing, False), (cells, False), (from, False), (mouse, False), (melanoma, False), (model, False), (derived, False), (tumors, False)]
2025-10-28 01:39:52.169 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3381] [doc 0] Token 0 'illumina' marked as sentence start (span begin)
2025-10-28 01:39:52.169 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3381] Token/tag mapping: [(illumina, True), (hiseq, False), (4000, False), (paired, False), (end, False), (sequencing, False), (;, False), (scrnaseq, False), (of, False), (cyp11a1, False), (-, False), (expressing, False), (cells, False), (from, False), (mouse, False), (melanoma, False), (model, False), (derived, False), (tumors, False)]
2025-10-28 01:39:52.172 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3382] [doc 0] Token 0 'nextseq' marked as sentence start (span begin)
2025-10-28 01:39:52.173 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3382] Token/tag mapping: [(nextseq, True), (500, False), (sequencing, False), (;, False), (rna, False), (sequencing, False), (of, False), (mouse, False), (samples, False), (using, False), (the, False), (illumina, False), (truseq, False), (®, False), (stranded, False), (mrna, False), (technology, False), (and, False), (the, False), (nextseq500, False), (next, False), (generation, False), (sequencing, False), (system, False)]
2025-10-28 01:39:52.176 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3383] [doc 0] Token 0 'nextseq' marked as sentence start (span begin)
2025-10-28 01:39:52.176 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3383] Token/tag mapping: [(nextseq, True), (500, False), (paired, False), (end, False), (sequencing, False), (;, False), (dna, False), (barcoding, False), (reveals, False), (ongoing, False), (immunoediting, False), (of, False), (clonal, False), (cancer, False), (populations, False), (during, False), (metastatic, False), (progression, False), (and, False), (in, False), (response, False), (to, False), (immunotherapy, False)]
2025-10-28 01:39:52.180 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3384] [doc 0] Token 0 'nan' marked as sentence start (span begin)
2025-10-28 01:39:52.181 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3384] Token/tag mapping: [(nan, True), (illumina, False), (hiseq, False), (2000, False), (paired, False), (end, False), (sequencing, False), (;, False), (gene, False), (expression, False), (pattern, False), (of, False), (single, False), (mes, False), (cells, False), (during, False), (cell, False), (cycle, False), (stages, False), (nan, False), (nan, False), (illumina, False), (hiseq, False), (2000, False), (paired, False), (end, False), (sequencing, False), (;, False), (gene, False), (expression, False), (pattern, False), (of, False), (single, False), (mes, False), (cells, False), (during, False), (cell, False), (cycle, False), (stages, False), (nan, False)]
2025-10-28 01:39:52.182 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3385] [doc 0] Token 0 'illumina' marked as sentence start (span begin)
2025-10-28 01:39:52.182 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3385] Token/tag mapping: [(illumina, True), (hiseq, False), (2000, False), (paired, False), (end, False), (sequencing, False)]
2025-10-28 01:39:52.185 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3386] [doc 0] Token 0 'illumina' marked as sentence start (span begin)
2025-10-28 01:39:52.185 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3386] Token/tag mapping: [(illumina, True), (hiseq, False), (2500, False), (sequencing, False), (;, False), (melanoma, False), (-, False), (derived, False), (extracellular, False), (vesicles, False), (mediate, False), (lymphatic, False), (remodeling, False), (and, False), (impair, False), (tumor, False), (immunity, False), (in, False), (draining, False), (lymph, False), (nodes, False)]
2025-10-28 01:39:52.187 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3387] [doc 0] Token 0 'illumina' marked as sentence start (span begin)
2025-10-28 01:39:52.187 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3387] Token/tag mapping: [(illumina, True), (hiseq, False), (4000, False), (paired, False), (end, False), (sequencing, False), (;, False), (spatiotemporal, False), (dynamics, False), (of, False), (crc, False), (metastases, False), (resolved, False), (by, False), (single, False), (cell, False), (rnaseq, False)]
2025-10-28 01:39:52.190 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3388] [doc 0] Token 0 'gsm1245211' marked as sentence start (span begin)
2025-10-28 01:39:52.190 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3388] Token/tag mapping: [(gsm1245211, True), (:, False), (normal, False), (homogenate, False), (rna, False), (-, False), (seq, False), (a, False), (;, False), (mus, False), (musculus, False), (;, False), (rna, False), (-, False), (seq, False), (nan, False), (gsm1245211, False), (:, False), (normal, False), (homogenate, False), (rna, False), (-, False), (seq, False), (a, False), (;, False), (mus, False), (musculus, False), (;, False), (rna, False), (-, False), (seq, False), (nan, False)]
2025-10-28 01:39:52.191 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3389] [doc 0] Token 0 'gsm4232527' marked as sentence start (span begin)
2025-10-28 01:39:52.192 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3389] Token/tag mapping: [(gsm4232527, True), (:, False), (mettl14, False), (ko, False), (rna, False), (seq, False), (rep3, False), (;, False), (mus, False), (musculus, False), (;, False), (rna, False), (-, False), (seq, False)]
2025-10-28 01:39:52.193 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3390] [doc 0] Token 0 'gsm4279928' marked as sentence start (span begin)
2025-10-28 01:39:52.193 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3390] Token/tag mapping: [(gsm4279928, True), (:, False), (kshv, False), ((, False), (+, False), (), False), (tumors, False), ([, False), (ds015accepted, False), (hitsmouse, False), (], False), (;, False), (mus, False), (musculus, False), (;, False), (rna, False), (-, False), (seq, False)]
2025-10-28 01:39:52.195 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3391] [doc 0] Token 0 'gsm4396316' marked as sentence start (span begin)

In [84]:
# find the position of "cancer_type"
idx = predicted_df.columns.index("cancer_type")

# slice up to that column (inclusive)
cols_to_keep = predicted_df.columns[:idx + 1]

# add the two specific extra columns
cols_to_keep += ["is_cancer", "confidence_category", "predicted_cancer_binary"]

predicted_df.select(cols_to_keep)

shape: (172, 41)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ experimen ┆ experimen ┆ title     ┆ study_nam ┆ … ┆ cancer_ty ┆ is_cancer ┆ confidenc ┆ predicte │
│ t_alias   ┆ t_accessi ┆ ---       ┆ e         ┆   ┆ pe        ┆ ---       ┆ e_categor ┆ d_cancer │
│ ---       ┆ on        ┆ str       ┆ ---       ┆   ┆ ---       ┆ i64       ┆ y         ┆ _binary  │
│ str       ┆ ---       ┆           ┆ str       ┆   ┆ str       ┆           ┆ ---       ┆ ---      │
│           ┆ str       ┆           ┆           ┆   ┆           ┆           ┆ str       ┆ i32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ ena-EXPER ┆ ERX352605 ┆ Illumina  ┆ null      ┆ … ┆ carcinoma ┆ 0         ┆ uncertain ┆ 0        │
│ IMENT-FUN ┆ 7         ┆ HiSeq     ┆           ┆   ┆           ┆           ┆ _no_signa ┆          │
│ CTIONAL   ┆           ┆ 2500      ┆           ┆   ┆           ┆           ┆ l         ┆          │
│ GENO…     ┆           ┆ paired    ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ end…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ GSM486040 ┆ SRX936418 ┆ GSM486040 ┆ null      ┆ … ┆ tumor*    ┆ 0         ┆ uncertain ┆ 0        │
│ 0         ┆ 0         ┆ 0: Fresh- ┆           ┆   ┆           ┆           ┆ _no_signa ┆          │
│           ┆           ┆ frozen    ┆           ┆   ┆           ┆           ┆ l         ┆          │
│           ┆           ┆ canin…    ┆           ┆   ┆           ┆           ┆           ┆          │
│ GSM486040 ┆ SRX936418 ┆ GSM486040 ┆ null      ┆ … ┆ tumor*    ┆ 0         ┆ uncertain ┆ 0        │
│ 1         ┆ 1         ┆ 1: Fresh- ┆           ┆   ┆           ┆           ┆ _no_signa ┆          │
│           ┆           ┆ frozen    ┆           ┆   ┆           ┆           ┆ l         ┆          │
│           ┆           ┆ canin…    ┆           ┆   ┆           ┆           ┆           ┆          │
│ GSM300511 ┆ SRX139997 ┆ GSM300511 ┆ null      ┆ … ┆ bladder   ┆ 0         ┆ uncertain ┆ 0        │
│ 1         ┆ 82        ┆ 1: D_Norm ┆           ┆   ┆ cancer    ┆           ┆ _no_signa ┆          │
│           ┆           ┆ al_Mucosa ┆           ┆   ┆           ┆           ┆ l         ┆          │
│           ┆           ┆ ; C…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ GSM249835 ┆ SRX258189 ┆ GSM249835 ┆ null      ┆ … ┆ tumor*    ┆ 1         ┆ uncertain ┆ 0        │
│ 7         ┆ 9         ┆ 7:        ┆           ┆   ┆           ┆           ┆ _no_signa ┆          │
│           ┆           ┆ CHAD-P9;  ┆           ┆   ┆           ┆           ┆ l         ┆          │
│           ┆           ┆ Canis     ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ lup…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ GSM318787 ┆ SRX420033 ┆ GSM318787 ┆ null      ┆ … ┆ rhabdomyo ┆ 1         ┆ uncertain ┆ 0        │
│ 6         ┆ 4         ┆ 6: Rh30:  ┆           ┆   ┆ sarcoma   ┆           ┆ _weak_sig ┆          │
│           ┆           ┆ RH30_ENT; ┆           ┆   ┆           ┆           ┆ nal       ┆          │
│           ┆           ┆ Mu…       ┆           ┆   ┆           ┆           ┆           ┆          │
│ GSM357314 ┆ SRX527294 ┆ GSM357314 ┆ null      ┆ … ┆ tumor*    ┆ 1         ┆ uncertain ┆ 0        │
│ 0         ┆ 6         ┆ 0: SAM243 ┆           ┆   ┆           ┆           ┆ _no_signa ┆          │
│           ┆           ┆ 42223     ┆           ┆   ┆           ┆           ┆ l         ┆          │
│           ┆           ┆ Macrop…   ┆           ┆   ┆           ┆           ┆           ┆          │
│ GSM357315 ┆ SRX527295 ┆ GSM357315 ┆ null      ┆ … ┆ tumor*    ┆ 1         ┆ uncertain ┆ 0        │
│ 0         ┆ 6         ┆ 0: SAM243 ┆           ┆   ┆           ┆           ┆ _no_signa ┆          │
│           ┆           ┆ 42227     ┆           ┆   ┆           ┆           ┆ l         ┆          │
│           ┆           ┆ Macrop…   ┆           ┆   ┆           ┆           ┆           ┆          │
│ GSM361182 ┆ SRX538990 ┆ GSM361182 ┆ null      ┆ … ┆ tumor*    ┆ 1         ┆ confident ┆ 1        │
│ 3         ┆ 0         ┆ 3: Tumor  ┆           ┆   ┆           ┆           ┆ _cancer   ┆          │
│           ┆           ┆ 5_non-PoE ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Ms;…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ GSM403702 ┆ SRX672076 ┆ GSM403702 ┆ null      ┆ … ┆ hepatocel ┆ 1         ┆ likely_ca ┆ 1        │
│ 9         ┆ 4         ┆ 9: MYC_Tw ┆           ┆   ┆ lular     ┆           ┆ ncer      ┆          │
│           ┆           ┆ ist1_HCC_ ┆           ┆   ┆ cancer    ┆           ┆           ┆          │
│           ┆           ┆ 5; …      ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [85]:
import numpy as np
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

# Convert to numpy arrays
y_true = predicted_df["is_cancer"].to_numpy()
y_pred = predicted_df["predicted_cancer_binary"].to_numpy()

# --- Metrics ---
acc = accuracy_score(y_true, y_pred)
prec = precision_score(y_true, y_pred)
rec = recall_score(y_true, y_pred)
f1 = f1_score(y_true, y_pred)

print(f"Accuracy:  {acc:.3f}")
print(f"Precision: {prec:.3f}")
print(f"Recall:    {rec:.3f}")
print(f"F1-score:  {f1:.3f}")

# --- Confusion Matrix ---
cm = confusion_matrix(y_true, y_pred)
print("\nConfusion Matrix:\n", cm)

# --- Full report ---
print("\nClassification Report:\n", classification_report(y_true, y_pred))

Accuracy:  0.558
Precision: 0.920
Recall:    0.390
F1-score:  0.548

Confusion Matrix:
 [[50  4]
 [72 46]]

Classification Report:
               precision    recall  f1-score   support

           0       0.41      0.93      0.57        54
           1       0.92      0.39      0.55       118

    accuracy                           0.56       172
   macro avg       0.66      0.66      0.56       172
weighted avg       0.76      0.56      0.55       172

In [47]:
predicted_df.filter((pl.col("predicted_cancer_binary") == 0) & (pl.col("is_cancer") == 1))[:, :100]

shape: (65, 100)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ experimen ┆ experimen ┆ title     ┆ study_nam ┆ … ┆ phenotype ┆ stimulus ┆ tumor_typ ┆ diagnosis │
│ t_alias   ┆ t_accessi ┆ ---       ┆ e         ┆   ┆ ---       ┆ ---      ┆ e         ┆ ---       │
│ ---       ┆ on        ┆ str       ┆ ---       ┆   ┆ str       ┆ str      ┆ ---       ┆ str       │
│ str       ┆ ---       ┆           ┆ str       ┆   ┆           ┆          ┆ str       ┆           │
│           ┆ str       ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ GSM249835 ┆ SRX258189 ┆ GSM249835 ┆ null      ┆ … ┆ null      ┆ null     ┆ null      ┆ null      │
│ 7         ┆ 9         ┆ 7:        ┆           ┆   ┆           ┆          ┆           ┆           │
│           ┆           ┆ CHAD-P9;  ┆           ┆   ┆           ┆          ┆           ┆           │
│           ┆           ┆ Canis     ┆           ┆   ┆           ┆          ┆           ┆           │
│           ┆           ┆ lup…      ┆           ┆   ┆           ┆          ┆           ┆           │
│ GSM338421 ┆ SRX467110 ┆ GSM338421 ┆ null      ┆ … ┆ null      ┆ null     ┆ null      ┆ Complex   │
│ 5         ┆ 4         ┆ 5: CMT-12 ┆           ┆   ┆           ┆          ┆           ┆ carcinoma │
│           ┆           ┆ 1-normal; ┆           ┆   ┆           ┆          ┆           ┆           │
│           ┆           ┆ Ca…       ┆           ┆   ┆           ┆          ┆           ┆           │
│ 32510     ┆ SRX295047 ┆ 32510     ┆ null      ┆ … ┆ null      ┆ null     ┆ null      ┆ null      │
│ RNA-seq   ┆           ┆ RNA-seq   ┆           ┆   ┆           ┆          ┆           ┆           │
│ of sponta ┆           ┆ of sponta ┆           ┆   ┆           ┆          ┆           ┆           │
│ neous c…  ┆           ┆ neous c…  ┆           ┆   ┆           ┆          ┆           ┆           │
│ GSM399310 ┆ SRX662328 ┆ GSM399310 ┆ null      ┆ … ┆ null      ┆ null     ┆ null      ┆ null      │
│ 5         ┆ 8         ┆ 5: Normal ┆           ┆   ┆           ┆          ┆           ┆           │
│           ┆           ┆ stroma    ┆           ┆   ┆           ┆          ┆           ┆           │
│           ┆           ┆ 123…      ┆           ┆   ┆           ┆          ┆           ┆           │
│ sample    ┆ SRX155665 ┆ RNA-seq   ┆ RNA-seq   ┆ … ┆ null      ┆ null     ┆ null      ┆ null      │
│ 2_replica ┆ 95        ┆ of Rattus ┆ of rat    ┆   ┆           ┆          ┆           ┆           │
│ tion 2    ┆           ┆ norvegicu ┆ PC12 cell ┆   ┆           ┆          ┆           ┆           │
│           ┆           ┆ sre…      ┆ s,repl…   ┆   ┆           ┆          ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …        ┆ …         ┆ …         │
│ GSM311993 ┆ SRX401933 ┆ GSM311993 ┆ null      ┆ … ┆ null      ┆ null     ┆ null      ┆ null      │
│ 2         ┆ 7         ┆ 2: S258_d ┆           ┆   ┆           ┆          ┆           ┆           │
│           ┆           ┆ og_WT4_CD ┆           ┆   ┆           ┆          ┆           ┆           │
│           ┆           ┆ 4_p…      ┆           ┆   ┆           ┆          ┆           ┆           │
│ GSM314205 ┆ SRX408331 ┆ GSM314205 ┆ null      ┆ … ┆ null      ┆ null     ┆ null      ┆ null      │
│ 2         ┆ 6         ┆ 2:        ┆           ┆   ┆           ┆          ┆           ┆           │
│           ┆           ┆ GS2-35;   ┆           ┆   ┆           ┆          ┆           ┆           │
│           ┆           ┆ Mus       ┆           ┆   ┆           ┆          ┆           ┆           │
│           ┆           ┆ muscul…   ┆           ┆   ┆           ┆          ┆           ┆           │
│ GSM318787 ┆ SRX420033 ┆ GSM318787 ┆ null      ┆ … ┆ null      ┆ null     ┆ null      ┆ null      │
│ 6         ┆ 4         ┆ 6: Rh30:  ┆           ┆   ┆           ┆          ┆           ┆           │
│           ┆           ┆ RH30_ENT; ┆           ┆   ┆           ┆          ┆           ┆           │
│           ┆           ┆ Mu…       ┆           ┆   ┆           ┆          ┆           ┆           │
│ GSM357314 ┆ SRX527294 ┆ GSM357314 ┆ null      ┆ … ┆ null      ┆ null     ┆ nan nan   ┆ null      │
│ 0         ┆ 6         ┆ 0: SAM243 ┆           ┆   ┆           ┆          ┆ nan nan   ┆           │
│           ┆           ┆ 42223     ┆           ┆   ┆           ┆          ┆ nan nan   ┆           │
│           ┆           ┆ Macrop…   ┆           ┆   ┆           ┆          ┆ nan na…   ┆           │
│ GSM357315 ┆ SRX527295 ┆ GSM357315 ┆ null      ┆ … ┆ null      ┆ null     ┆ nan nan   ┆ null      │
│ 0         ┆ 6         ┆ 0: SAM243 ┆           ┆   ┆           ┆          ┆ nan nan   ┆           │
│           ┆           ┆ 42227     ┆           ┆   ┆           ┆          ┆ nan nan   ┆           │
│           ┆           ┆ Macrop…   ┆           ┆   ┆           ┆          ┆ nan na…   ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴───────────┘

## Testing medspaCy (NLP based approach)

In [40]:
import spacy
import medspacy
from medspacy.ner import TargetRule
# Note: TargetMatcher is fetched via pipeline, not imported directly

nlp = medspacy.load()  # load medspacy pipeline

# Retrieve the target matcher pipe
target_matcher = nlp.get_pipe("medspacy_target_matcher")

# Define your list of cancer-related terms
cancer_terms = ["cancer", "tumor", "tumour", "carcinoma", "neoplasm", "metastasis"]

# Build target rules
target_rules = [
    TargetRule(term, category="CANCER")
    for term in cancer_terms
]

# Add the rules to the matcher
target_matcher.add(target_rules)

# Test it
text = "The biopsy showed a malignant carcinoma and bone metastasis but no benign tumor."
doc = nlp(text)
for ent in doc.ents:
    print(ent.text, ent.label_, ent._.target_rule)

2025-10-28 00:01:09.823 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1367] [doc 0] Token 0 'The' marked as sentence start (span begin)
2025-10-28 00:01:09.825 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1367] Token/tag mapping: [(The, True), (biopsy, False), (showed, False), (a, False), (malignant, False), (carcinoma, False), (and, False), (bone, False), (metastasis, False), (but, False), (no, False), (benign, False), (tumor, False), (., False)]

carcinoma CANCER TargetRule(literal="carcinoma", category="CANCER", pattern=None, attributes=None, on_match=None)
metastasis CANCER TargetRule(literal="metastasis", category="CANCER", pattern=None, attributes=None, on_match=None)
tumor CANCER TargetRule(literal="tumor", category="CANCER", pattern=None, attributes=None, on_match=None)

In [41]:
import medspacy
from medspacy.ner import TargetRule

# Load full medspaCy pipeline (includes context/negation detection)
nlp = medspacy.load()
target_matcher = nlp.get_pipe("medspacy_target_matcher")

# Add some cancer-related target rules
for term in ["cancer", "tumor", "carcinoma"]:
    target_matcher.add([TargetRule(literal=term, category="CANCER")])

# Test examples
texts = [
    "There is no cancer here.",
    "Patient diagnosed with malignant tumor.",
    "No evidence of carcinoma detected."
]

for text in texts:
    doc = nlp(text)
    print(f"\nText: {text}")
    for ent in doc.ents:
        print(f" - Entity: {ent.text!r}, Category: {ent.label_}, Negated: {ent._.is_negated}")

2025-10-28 00:48:55.490 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1368] [doc 0] Token 0 'There' marked as sentence start (span begin)
2025-10-28 00:48:55.490 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1368] Token/tag mapping: [(There, True), (is, False), (no, False), (cancer, False), (here, False), (., False)]
2025-10-28 00:48:55.493 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1369] [doc 0] Token 0 'Patient' marked as sentence start (span begin)
2025-10-28 00:48:55.493 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1369] Token/tag mapping: [(Patient, True), (diagnosed, False), (with, False), (malignant, False), (tumor, False), (., False)]
2025-10-28 00:48:55.494 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1370] [doc 0] Token 0 'No' marked as sentence start (span begin)
2025-10-28 00:48:55.495 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1370] Token/tag mapping: [(No, True), (evidence, False), (of, False), (carcinoma, False), (detected, False), (., False)]

Text: There is no cancer here.
 - Entity: 'cancer', Category: CANCER, Negated: True

Text: Patient diagnosed with malignant tumor.
 - Entity: 'tumor', Category: CANCER, Negated: False

Text: No evidence of carcinoma detected.
 - Entity: 'carcinoma', Category: CANCER, Negated: True

## Second medspaCy (Failed Attempt)

In [42]:
import medspacy
from medspacy.ner import TargetRule

# --- Load medspacy pipeline ---
nlp = medspacy.load()
target_matcher = nlp.get_pipe("medspacy_target_matcher")

# Add cancer-related terms
CANCER_TERMS = [
    "cancer", "tumor", "tumour", "malignant", "malignancy",
    "carcinoma", "neoplasm", "metastatic", "metastasis",
    "adenocarcinoma", "sarcoma", "leukemia", "leukaemia",
    "lymphoma", "glioblastoma", "melanoma"
]
target_rules = [TargetRule(term, category="CANCER") for term in CANCER_TERMS]
target_matcher.add(target_rules)


def analyze_text_with_spacy(text: str) -> dict:
    """
    Detect cancer terms and check if they're negated using medspacy's context model.
    """
    if not text or not isinstance(text, str) or not text.strip():
        return {
            "has_cancer_term": False,
            "has_negated_cancer": False,
            "has_confirmed_cancer": False
        }

    doc = nlp(text.lower())

    has_cancer_term = False
    has_negated_cancer = False
    has_confirmed_cancer = False

    for ent in doc.ents:
        if ent.label_ == "CANCER":      # detected by target matcher
            has_cancer_term = True
            if getattr(ent._, "is_negated", False):
                has_negated_cancer = True
            else:
                has_confirmed_cancer = True

    return {
        "has_cancer_term": has_cancer_term,
        "has_negated_cancer": has_negated_cancer,
        "has_confirmed_cancer": has_confirmed_cancer
    }

In [53]:
# Test medspacy entity detection on real metadata samples
import spacy
import medspacy

# Load medspacy
nlp = medspacy.load()

# Sample texts from different scenarios
test_texts = [
    "breast cancer tissue",
    "normal breast tissue",
    "no evidence of tumor",
    "tumor sample from lung",
    "cancer cell line",
    "adjacent normal tissue",
    "metastatic carcinoma",
    "healthy control sample",
    "glioblastoma multiforme",
    "non-tumor breast tissue"
]

print("=" * 80)
print("TESTING MEDSPACY ENTITY DETECTION")
print("=" * 80)

for text in test_texts:
    doc = nlp(text)
    entities = [(ent.text, ent.label_, getattr(ent._, 'is_negated', None)) for ent in doc.ents]

    print(f"\nText: '{text}'")
    if entities:
        print(f"  ✓ Entities found: {entities}")
    else:
        print(f"  ✗ NO ENTITIES DETECTED")

print("\n" + "=" * 80)

2025-10-28 01:16:42.206 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2681] [doc 0] Token 0 'breast' marked as sentence start (span begin)
2025-10-28 01:16:42.206 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2681] Token/tag mapping: [(breast, True), (cancer, False), (tissue, False)]
2025-10-28 01:16:42.207 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2682] [doc 0] Token 0 'normal' marked as sentence start (span begin)
2025-10-28 01:16:42.207 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2682] Token/tag mapping: [(normal, True), (breast, False), (tissue, False)]
2025-10-28 01:16:42.208 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2683] [doc 0] Token 0 'no' marked as sentence start (span begin)
2025-10-28 01:16:42.208 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2683] Token/tag mapping: [(no, True), (evidence, False), (of, False), (tumor, False)]
2025-10-28 01:16:42.210 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2684] [doc 0] Token 0 'tumor' marked as sentence start (span begin)
2025-10-28 01:16:42.210 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2684] Token/tag mapping: [(tumor, True), (sample, False), (from, False), (lung, False)]
2025-10-28 01:16:42.211 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2685] [doc 0] Token 0 'cancer' marked as sentence start (span begin)
2025-10-28 01:16:42.211 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2685] Token/tag mapping: [(cancer, True), (cell, False), (line, False)]
2025-10-28 01:16:42.212 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2686] [doc 0] Token 0 'adjacent' marked as sentence start (span begin)
2025-10-28 01:16:42.212 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2686] Token/tag mapping: [(adjacent, True), (normal, False), (tissue, False)]
2025-10-28 01:16:42.212 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2687] [doc 0] Token 0 'metastatic' marked as sentence start (span begin)
2025-10-28 01:16:42.213 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2687] Token/tag mapping: [(metastatic, True), (carcinoma, False)]
2025-10-28 01:16:42.213 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2688] [doc 0] Token 0 'healthy' marked as sentence start (span begin)
2025-10-28 01:16:42.214 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2688] Token/tag mapping: [(healthy, True), (control, False), (sample, False)]
2025-10-28 01:16:42.214 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2689] [doc 0] Token 0 'glioblastoma' marked as sentence start (span begin)
2025-10-28 01:16:42.215 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2689] Token/tag mapping: [(glioblastoma, True), (multiforme, False)]
2025-10-28 01:16:42.215 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2690] [doc 0] Token 0 'non' marked as sentence start (span begin)
2025-10-28 01:16:42.215 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2690] Token/tag mapping: [(non, True), (-, False), (tumor, False), (breast, False), (tissue, False)]

================================================================================
TESTING MEDSPACY ENTITY DETECTION
================================================================================

Text: 'breast cancer tissue'
  ✗ NO ENTITIES DETECTED

Text: 'normal breast tissue'
  ✗ NO ENTITIES DETECTED

Text: 'no evidence of tumor'
  ✗ NO ENTITIES DETECTED

Text: 'tumor sample from lung'
  ✗ NO ENTITIES DETECTED

Text: 'cancer cell line'
  ✗ NO ENTITIES DETECTED

Text: 'adjacent normal tissue'
  ✗ NO ENTITIES DETECTED

Text: 'metastatic carcinoma'
  ✗ NO ENTITIES DETECTED

Text: 'healthy control sample'
  ✗ NO ENTITIES DETECTED

Text: 'glioblastoma multiforme'
  ✗ NO ENTITIES DETECTED

Text: 'non-tumor breast tissue'
  ✗ NO ENTITIES DETECTED

================================================================================

In [54]:
import spacy
import medspacy
from medspacy.ner import TargetRule

# Load medspacy pipeline
nlp = medspacy.load()

# Get the target matcher component
target_matcher = nlp.get_pipe("medspacy_target_matcher")

# Define cancer-related terms to detect
cancer_rules = [
    # General cancer terms
    TargetRule("cancer", "PROBLEM"),
    TargetRule("cancers", "PROBLEM"),
    TargetRule("tumor", "PROBLEM"),
    TargetRule("tumour", "PROBLEM"),
    TargetRule("tumors", "PROBLEM"),
    TargetRule("tumours", "PROBLEM"),

    # Malignancy terms
    TargetRule("malignant", "PROBLEM"),
    TargetRule("malignancy", "PROBLEM"),

    # Specific cancer types
    TargetRule("carcinoma", "PROBLEM"),
    TargetRule("adenocarcinoma", "PROBLEM"),
    TargetRule("sarcoma", "PROBLEM"),
    TargetRule("melanoma", "PROBLEM"),
    TargetRule("glioma", "PROBLEM"),
    TargetRule("glioblastoma", "PROBLEM"),
    TargetRule("leukemia", "PROBLEM"),
    TargetRule("leukaemia", "PROBLEM"),
    TargetRule("lymphoma", "PROBLEM"),
    TargetRule("myeloma", "PROBLEM"),

    # Metastasis
    TargetRule("metastatic", "PROBLEM"),
    TargetRule("metastasis", "PROBLEM"),
    TargetRule("metastases", "PROBLEM"),

    # Neoplasm
    TargetRule("neoplasm", "PROBLEM"),
    TargetRule("neoplastic", "PROBLEM"),
]

# Add all rules to the target matcher
target_matcher.add(cancer_rules)

print(f"✓ Added {len(cancer_rules)} cancer-related target rules to medspacy")

✓ Added 23 cancer-related target rules to medspacy

In [55]:
# Re-test with TargetMatcher configured
test_texts = [
    "breast cancer tissue",
    "normal breast tissue",
    "no evidence of tumor",
    "tumor sample from lung",
    "cancer cell line",
    "adjacent normal tissue",
    "metastatic carcinoma",
    "healthy control sample",
    "glioblastoma multiforme",
    "non-tumor breast tissue"
]

print("=" * 80)
print("TESTING WITH TARGET MATCHER")
print("=" * 80)

for text in test_texts:
    doc = nlp(text)

    print(f"\nText: '{text}'")

    if doc.ents:
        for ent in doc.ents:
            negated = "✗ NEGATED" if ent._.is_negated else "✓ AFFIRMED"
            print(f"  Entity: '{ent.text}' | Label: {ent.label_} | {negated}")
    else:
        print(f"  ✗ NO ENTITIES DETECTED")

print("\n" + "=" * 80)

2025-10-28 01:18:21.419 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2691] [doc 0] Token 0 'breast' marked as sentence start (span begin)
2025-10-28 01:18:21.421 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2691] Token/tag mapping: [(breast, True), (cancer, False), (tissue, False)]
2025-10-28 01:18:21.423 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2692] [doc 0] Token 0 'normal' marked as sentence start (span begin)
2025-10-28 01:18:21.424 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2692] Token/tag mapping: [(normal, True), (breast, False), (tissue, False)]
2025-10-28 01:18:21.426 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2693] [doc 0] Token 0 'no' marked as sentence start (span begin)
2025-10-28 01:18:21.426 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2693] Token/tag mapping: [(no, True), (evidence, False), (of, False), (tumor, False)]
2025-10-28 01:18:21.427 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2694] [doc 0] Token 0 'tumor' marked as sentence start (span begin)
2025-10-28 01:18:21.428 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2694] Token/tag mapping: [(tumor, True), (sample, False), (from, False), (lung, False)]
2025-10-28 01:18:21.429 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2695] [doc 0] Token 0 'cancer' marked as sentence start (span begin)
2025-10-28 01:18:21.429 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2695] Token/tag mapping: [(cancer, True), (cell, False), (line, False)]
2025-10-28 01:18:21.432 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2696] [doc 0] Token 0 'adjacent' marked as sentence start (span begin)
2025-10-28 01:18:21.432 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2696] Token/tag mapping: [(adjacent, True), (normal, False), (tissue, False)]
2025-10-28 01:18:21.433 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2697] [doc 0] Token 0 'metastatic' marked as sentence start (span begin)
2025-10-28 01:18:21.433 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2697] Token/tag mapping: [(metastatic, True), (carcinoma, False)]
2025-10-28 01:18:21.434 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2698] [doc 0] Token 0 'healthy' marked as sentence start (span begin)
2025-10-28 01:18:21.434 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2698] Token/tag mapping: [(healthy, True), (control, False), (sample, False)]
2025-10-28 01:18:21.435 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2699] [doc 0] Token 0 'glioblastoma' marked as sentence start (span begin)
2025-10-28 01:18:21.435 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2699] Token/tag mapping: [(glioblastoma, True), (multiforme, False)]
2025-10-28 01:18:21.436 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2700] [doc 0] Token 0 'non' marked as sentence start (span begin)
2025-10-28 01:18:21.436 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2700] Token/tag mapping: [(non, True), (-, False), (tumor, False), (breast, False), (tissue, False)]

================================================================================
TESTING WITH TARGET MATCHER
================================================================================

Text: 'breast cancer tissue'
  Entity: 'cancer' | Label: PROBLEM | ✓ AFFIRMED

Text: 'normal breast tissue'
  ✗ NO ENTITIES DETECTED

Text: 'no evidence of tumor'
  Entity: 'tumor' | Label: PROBLEM | ✗ NEGATED

Text: 'tumor sample from lung'
  Entity: 'tumor' | Label: PROBLEM | ✓ AFFIRMED

Text: 'cancer cell line'
  Entity: 'cancer' | Label: PROBLEM | ✓ AFFIRMED

Text: 'adjacent normal tissue'
  ✗ NO ENTITIES DETECTED

Text: 'metastatic carcinoma'
  Entity: 'metastatic' | Label: PROBLEM | ✓ AFFIRMED
  Entity: 'carcinoma' | Label: PROBLEM | ✓ AFFIRMED

Text: 'healthy control sample'
  ✗ NO ENTITIES DETECTED

Text: 'glioblastoma multiforme'
  Entity: 'glioblastoma' | Label: PROBLEM | ✓ AFFIRMED

Text: 'non-tumor breast tissue'
  Entity: 'tumor' | Label: PROBLEM | ✓ AFFIRMED

================================================================================