In [5]:
import pandas as pd

## Look at no signal findings

In [6]:
data = pd.read_csv('outputs/classified_samples.csv')

/var/folders/3w/q_m3rh1s5xv5bh0kfpcqmd9r0000gn/T/ipykernel_39834/2936806345.py:1: DtypeWarning: Columns (13,17,21) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('outputs/classified_samples.csv')

In [7]:
no_signal = data[data['med_label'] == "NO_SIGNAL"]

In [8]:
no_signal.groupby('bioproject')['bioproject'].count()

bioproject
BP2             2
BP3             2
BP4             1
BP6             3
PRJDB11471     18
               ..
PRJNA986932     6
PRJNA988466     4
PRJNA993232     6
PRJNA996913     6
PRJNA997825     3
Name: bioproject, Length: 867, dtype: int64

## Look at non mouse data

In [14]:
all_data = pd.read_csv('data/combined_metadata_noncancer_removed.csv')

/var/folders/3w/q_m3rh1s5xv5bh0kfpcqmd9r0000gn/T/ipykernel_39834/19654637.py:1: DtypeWarning: Columns (3,5,16,20,21,22,23,24,29,30,38,39,40,41,42,43,44,46,47,48,49,50,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,119,121,122,123,124,125,126,127,128,130,131,132,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,165,166,167,168,169,170,171,172,173,174,176,177,178,179,180,181,182,183,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,201,202,203,204,205,206,207,209,210,211,212,213,214,215,217,218,221,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,262,263,264,265,266,267,268,269,270,272,273,274,275,276,277,278,279,280,281,282,283,284,285,291,292,304,305,306,307,308,309,311,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,332,333,334,335,336,337,338,339,340,341,342,343,344,346,349,350,351,352,353,354,355,356,357,360,361,363,364,366,369,370,371,372,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,390,391,392,393,395,397,399,400,401,403,404,405,406,407,408,409,410,411,412,414,418,419,421,422,423,425,426,427,428,429,430,431,432,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,492,494,495,496,497,499,500,501,502,503,505,506,507,508,510,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,536,537,538,539,541,542,543,544,545,546,547,548,549,551,553,554,555,556,557,558,559,560,561,562,563,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,585,586,588,589,590,591,592,593,594,597,598,601,602,603,604,614,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,670,671,672,673,675,677,678,679,680,681,682,683,685,686,687,688,689,690,691,693,694,695,696,697,699,700,701,703,706,707,708,709,711,713,715,718,719,720,721,724,725,727,728,729,730,731,732,733,734,735,736,737,740,741,742,743,744,745,746,748,749,750,751,752,759,760,761,762,763,764,765,766,767,768,769,770,771,772,773,774,775,776,777,778,779,780,782,783,786,787,788,789,790,791,792,793,794,795,796,798,799,800,801,802,803,804,805,806,807,808,809,810,811,812,813,814,815,816,817,818,819,820,821,822,823,824,825,826,827,829,830,831,832,833,834,835,836,838,839,840,842,855,856,859,860,861,863,864,867,868,869,871,873,874,875,876,877,878,879,880,883,885,886,887,888,889,891,892,893,894,895,896,897,898,899,900,901,902,903,904,905,906,907,908,909,910,911,912,913,914,915,916,917,918,919,920,921,922,923,924,925,926,927,928,929,930,931,932,933,934,935,936,937,938,939,940,941,943,944,945,946,947,948,949,951,953,954,956,957,958,959,960,961,962,963,964,966,967,968,969,970,971,972,973,974,976,977,978,979,980,981,982,983,984,985,986,987,988,989,990,991,992,993,994,995,996,997,998,999,1000,1001,1002,1004,1005,1006,1010,1011,1013,1014,1015,1016,1017,1018,1019,1020,1021,1023,1024,1025,1026,1027,1028,1029,1030,1031,1032,1033,1034,1035,1037,1038,1039,1040,1041,1042,1043,1045,1046,1047,1048,1049,1050,1051,1052,1055,1056,1057,1058,1059,1060,1061,1062,1063,1067,1069,1071,1072,1073,1074,1075,1076,1077,1078,1079,1080,1083,1093,1095,1096,1098,1099,1100,1101,1102,1103,1104,1105,1106,1107,1108,1109,1111,1112,1113,1114,1115,1116,1117,1118,1119,1120,1121,1122,1123,1124,1125,1126,1127,1128,1129,1130,1131,1132,1133,1134,1135,1136,1137,1138,1139,1140,1141,1142,1143,1144,1145,1149,1150,1151,1152,1154,1155,1156,1157,1158,1159,1160,1161,1162,1163,1164,1165,1166,1168,1170,1171,1173,1174,1175,1176,1177,1178,1179,1180,1181,1182,1183,1184,1185,1186,1187,1188,1189,1190,1191,1192,1193,1194,1196,1200,1201,1203,1206,1209,1211,1212,1214,1215,1218,1220,1226,1227,1228,1236,1238,1239,1240,1241,1242,1243,1244,1245,1246,1247,1249,1250,1251,1252,1253,1254,1255,1256,1257,1258,1259,1260,1261,1262,1263,1264,1265,1266,1268,1270,1271,1272,1273,1274,1275,1276,1277,1278,1279,1280,1281,1282,1283,1284,1285,1286,1287,1288,1289,1290,1291,1292,1293,1295,1296,1297,1298,1299,1300,1301,1302,1303,1304,1305,1306,1307,1308,1309,1310,1311,1312,1313,1314,1315,1316,1317,1318,1319,1320,1321,1324,1325,1326,1327,1328,1329,1330,1331,1332,1333,1334,1335,1336,1337,1338,1339,1341,1342,1343,1344,1345,1346,1347,1348,1349,1350,1351,1352,1353,1354,1355,1356,1357,1358,1359,1360,1361,1362,1363,1364,1365,1366,1367,1368,1369,1370,1371,1372,1373,1374,1376,1377,1380,1381,1382,1383,1386,1387,1388,1389,1391,1394,1396,1397,1398) have mixed types. Specify dtype option on import or set low_memory=False.
  all_data = pd.read_csv('data/combined_metadata_noncancer_removed.csv')

In [15]:
all_data = all_data.iloc[:,:100]

In [21]:
exclude = [
    "Mus musculus",
    "Mus musculus domesticus",
    "Mus musculus musculus"
]

non_mouse = all_data[~all_data['organism_scientific_name'].isin(exclude)]

In [31]:
sample_400 = non_mouse.sample(n=400, random_state=42)

In [32]:
sample_400

,experiment_alias,experiment_accession,title,study_name,sample_accession,library_name,library_strategy,library_source,library_selection,library_layout,...,clinical_description,tumor_location,disease_state,dog_breed,source_location,sample_type,phenotype,stimulus,tumor_type,diagnosis
1374,GSM5860117_r1,SRX14042174,GSM5860117: canine cortisol-secreting adrenoco...,NaN,SRS11877043,GSM5860117,RNA-Seq,TRANSCRIPTOMIC,cDNA,SINGLE,...,NaN,NaN,NaN,NaN,NaN,nan nan nan nan nan nan,NaN,NaN,NaN,NaN
2293,GSM2453759,SRX2485257,GSM2453759: DLYM-1115_PENN03_valspodar_Post; C...,NaN,SRS1915489,NaN,RNA-Seq,TRANSCRIPTOMIC,cDNA,PAIRED,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3379,z2,SRX26325965,RNA-Seq of rabbit: male liver cancer,rabbit liver cancer,SRS22852948,z2,RNA-Seq,TRANSCRIPTOMIC,cDNA,PAIRED,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1090,LID33,SRX11560378,RNA-Seq of melanoma : adult oral mucosal melanoma,Illumina trueseq stranded paired end Protocol,SRS9598731,LID33,RNA-Seq,TRANSCRIPTOMIC,Oligo-dT,PAIRED,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1803,GSM7678120_r1,SRX21232882,GSM7678120: CCB010057; Canis lupus familiaris;...,NaN,SRS18487976,GSM7678120,RNA-Seq,TRANSCRIPTOMIC,cDNA,PAIRED,...,NaN,Tibia,NaN,NaN,NaN,nan nan nan nan nan nan,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2784,CMT-158-tumor,SRX4634646,RNA-Seq of canine mammary tumor sample,RNA sequencing was performed using the Illumin...,SRS3735895,CMT-158-tumor,RNA-Seq,TRANSCRIPTOMIC,ChIP,PAIRED,...,NaN,NaN,NaN,NaN,NaN,nan nan nan nan nan nan,NaN,NaN,NaN,Benign mixed tumor
1104,LID3,SRX11560364,RNA-Seq of melanoma : adult oral mucosal melanoma,Illumina trueseq stranded paired end Protocol,SRS9598717,LID3,RNA-Seq,TRANSCRIPTOMIC,Oligo-dT,PAIRED,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1106,LID19,SRX11560362,RNA-Seq of melanoma : adult oral mucosal melanoma,Illumina trueseq stranded paired end Protocol,SRS9598715,LID19,RNA-Seq,TRANSCRIPTOMIC,Oligo-dT,PAIRED,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3166,GSM3993104,SRX6623287,GSM3993104: Cancer-associated stroma 121_tumou...,NaN,SRS5181043,NaN,RNA-Seq,TRANSCRIPTOMIC,cDNA,SINGLE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
314,GSM7658601_r1,SRX21139397,GSM7658601: 129_1414_tumor; Canis lupus famili...,NaN,SRS18403863,GSM7658601,RNA-Seq,TRANSCRIPTOMIC,cDNA,PAIRED,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
cols = [
    "title",
    "single-cell/bulk",
    "tissue",
    "disease",
    "experiment_accession",
    "bioproject",
    "biosample",
    "sample_accession",
    "study_accession",
    "library_construction_protocol",
    "source_name",
    "run_accession",
    "cancer_type"
]

filtered_df = sample_400[cols]

In [34]:
filtered_df

,title,single-cell/bulk,tissue,disease,experiment_accession,bioproject,biosample,sample_accession,study_accession,library_construction_protocol,source_name,run_accession,cancer_type
1374,GSM5860117: canine cortisol-secreting adrenoco...,bulk,nan nan nan nan nan nan,canine cortisol-secreting adrenocortical tumor,SRX14042174,PRJNA803356,GSM5860117,SRS11877043,SRP358249,cells were trypsinized and stored in RLT. Tota...,cortisol-secreting adrenocortical tumor,SRR17882906,tumor*
2293,GSM2453759: DLYM-1115_PENN03_valspodar_Post; C...,bulk,NaN,NaN,SRX2485257,PRJNA360981,GSM2453759,SRS1915489,SRP096582,Total RNA was extracted using Qiagen RNeasy Mi...,lymphoma,SRR5168428,lymphoma
3379,RNA-Seq of rabbit: male liver cancer,bulk,rabbit liver cancer,NaN,SRX26325965,PRJNA1168652,NaN,SRS22852948,SRP537430,NaN,NaN,SRR30923122,hepatocellular cancer
1090,RNA-Seq of melanoma : adult oral mucosal melanoma,bulk,nan oral mucosal tumor nan nan oral mucosal tu...,melanoma,SRX11560378,PRJNA749900,NaN,SRS9598731,SRP329980,NaN,NaN,SRR15255013,melanoma
1803,GSM7678120: CCB010057; Canis lupus familiaris;...,bulk,nan osteosarcoma tumor tisue nan nan osteosarc...,NaN,SRX21232882,PRJNA1001809,GSM7678120,SRS18487976,SRP453113,Ambion miRvana kit. Illumina paired end RNA-Se...,osteosarcoma tumor tisue,SRR25502047,tumor*
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2784,RNA-Seq of canine mammary tumor sample,bulk,nan tumor nan nan tumor nan,NaN,SRX4634646,PRJNA489087,NaN,SRS3735895,SRP159466,NaN,NaN,SRR7779615,tumor*
1104,RNA-Seq of melanoma : adult oral mucosal melanoma,bulk,nan oral mucosal control nan nan oral mucosal ...,non melanoma,SRX11560364,PRJNA749900,NaN,SRS9598717,SRP329980,NaN,NaN,SRR15255027,melanoma
1106,RNA-Seq of melanoma : adult oral mucosal melanoma,bulk,nan oral mucosal tumor nan nan oral mucosal tu...,melanoma,SRX11560362,PRJNA749900,NaN,SRS9598715,SRP329980,NaN,NaN,SRR15255029,melanoma
3166,GSM3993104: Cancer-associated stroma 121_tumou...,bulk,NaN,NaN,SRX6623287,PRJNA557680,GSM3993104,SRS5181043,SRP216930,RNA was extracted using the optimised Covaris-...,canine simple mammary carcinoma,SRR9870551,carcinoma
314,GSM7658601: 129_1414_tumor; Canis lupus famili...,bulk,NaN,NaN,SRX21139397,PRJNA997978,GSM7658601,SRS18403863,SRP451102,100 ng to 1µg was used as input to TruSeq Stra...,primary osteosarcoma,SRR25403257,osteosarcoma

In [35]:
# filtered_df.to_csv("outputs/manual_label_not_mouse.csv", index=False)

In [51]:
# excel_data_full = pd.read_excel('outputs/manual_label_not_mouse.xlsx')

In [52]:
# excel_data_raw = excel_data_full.drop("is_cancer")

## Run Classification Pipeline on Manual Label Data

In [1]:
import polars as pl
from functions import (
    classify_cancer_samples,
    initialize_medspacy_pipeline,
    generate_disease_rules,
    get_default_target_rules,
)
from text_column_processing import TextColumnConfig, preprocess_dataframe

In [2]:
# Convert pandas to polars for the pipeline
# excel_pl = pl.from_pandas(excel_data_raw)
# excel_data_full = pl.read_excel("outputs/manual_label_not_mouse.xlsx")

In [3]:
# excel_data_full = pl.read_excel("outputs/manual_label_not_mouse.xlsx")
# excel_data_raw = excel_data_full.drop("is_cancer")

# excel_pl = excel_data_raw

In [4]:
excel_pl = pl.read_excel("outputs/manual_label_not_mouse.xlsx")

In [5]:
# Initialize MedSpaCy pipeline
cancer_rules, non_cancer_rules = get_default_target_rules()
nlp = initialize_medspacy_pipeline(cancer_rules, non_cancer_rules)

# Generate disease-specific rules from the data
unique_diseases = excel_pl.select("disease").drop_nulls().unique().to_series().to_list()
auto_rules, skipped = generate_disease_rules(unique_diseases, nlp, cancer_rules + non_cancer_rules)

if auto_rules:
    tm = nlp.get_pipe("medspacy_target_matcher")
    tm.add(auto_rules)
    print(f"Added {len(auto_rules)} auto-generated disease rules")

Added 14 auto-generated disease rules

In [6]:
# Preprocess text columns
config = TextColumnConfig()
excel_pl, col_tiers = preprocess_dataframe(excel_pl, config=config, include_discovered=False)
print(f"Created {len(col_tiers['normalized'])} normalized columns")

Created 4 normalized columns

In [7]:
# Run classification
predicted_df = classify_cancer_samples(excel_pl, nlp_pipeline=nlp, batch_size=64, use_normalized=True)

2026-02-17 01:47:29.676 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=0] [doc 0] Token 0 'healthy' marked as sentence start (span begin)
2026-02-17 01:47:29.677 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=0] Token/tag mapping: [(healthy, True)]
2026-02-17 01:47:29.679 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1] [doc 0] Token 0 'GSM2453763' marked as sentence start (span begin)
2026-02-17 01:47:29.679 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1] Token/tag mapping: [(GSM2453763, True), (:, False), (DLYM, False), (-, False), (1118, False), (_, False), (PD01, False), (_, False), (valspodar, False), (_, False), (Post, False), (;, False), (Canis, False), (lupus, False), (familiaris, False), (;, False), (RNA, False), (-, False), (Seq, False)]
2026-02-17 01:47:29.680 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2] [doc 0] Token 0 'RNA' marked as sentence start (span begin)
2026-02-17 01:47:29.681 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2] Token/tag mapping: [(RNA, True), (-, False), (seq, False), (of, False), (canine, False), (FL, False)]
2026-02-17 01:47:29.682 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3] [doc 0] Token 0 'mammary' marked as sentence start (span begin)
2026-02-17 01:47:29.682 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3] Token/tag mapping: [(mammary, True), (gland, False), (adenoma, False)]
2026-02-17 01:47:29.685 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=4] [doc 0] Token 0 'bone' marked as sentence start (span begin)
2026-02-17 01:47:29.686 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=4] Token/tag mapping: [(bone, True), (tumor, False)]
2026-02-17 01:47:29.690 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=5] [doc 0] Token 0 'nan' marked as sentence start (span begin)
2026-02-17 01:47:29.691 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=5] Token/tag mapping: [(nan, True), (osteosarcoma, False), (tumor, False), (tisue, False), (nan, False), (nan, False), (osteosarcoma, False), (tumor, False), (tisue, False), (nan, False)]
2026-02-17 01:47:29.692 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=6] [doc 0] Token 0 'melanoma' marked as sentence start (span begin)
2026-02-17 01:47:29.693 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=6] Token/tag mapping: [(melanoma, True), (tumor, False)]
2026-02-17 01:47:29.694 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] [doc 0] Token 0 'primary' marked as sentence start (span begin)
2026-02-17 01:47:29.694 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] Token/tag mapping: [(primary, True), (osteosarcoma, False)]
2026-02-17 01:47:29.697 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=8] [doc 0] Token 0 'RNA' marked as sentence start (span begin)
2026-02-17 01:47:29.698 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=8] Token/tag mapping: [(RNA, True), (-, False), (seq, False), (of, False), (4T1, False), (xenograft, False), (tumor, False), (in, False), (rats, False), (:, False), (tumor, False), (necrotic, False), (core, False)]
2026-02-17 01:47:29.700 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=9] [doc 0] Token 0 'mRNA' marked as sentence start (span begin)
2026-02-17 01:47:29.700 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=9] Token/tag mapping: [(mRNA, True), (seq, False), (of, False), (canis, False), (familiaris, False), (:, False), (oral, False), (tissue, False)]
2026-02-17 01:47:29.702 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=10] [doc 0] Token 0 'canine' marked as sentence start (span begin)
2026-02-17 01:47:29.703 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=10] Token/tag mapping: [(canine, True), (mammary, False), (normal, False), (tissue, False)]
2026-02-17 01:47:29.704 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=11] [doc 0] Token 0 'GSM3070883' marked as sentence start (span begin)
2026-02-17 01:47:29.705 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=11] Token/tag mapping: [(GSM3070883, True), (:, False), (CLBL, False), (-, False), (1, False), (rep3, False), (;, False), (Canis, False), (lupus, False), (familiaris, False), (;, False), (RNA, False), (-, False), (Seq, False)]
2026-02-17 01:47:29.706 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=12] [doc 0] Token 0 'canine' marked as sentence start (span begin)
2026-02-17 01:47:29.706 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=12] Token/tag mapping: [(canine, True), (cortisol, False), (-, False), (secreting, False), (adrenocortical, False), (tumor, False)]
2026-02-17 01:47:29.708 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=13] [doc 0] Token 0 'GSM3384208' marked as sentence start (span begin)
2026-02-17 01:47:29.708 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=13] Token/tag mapping: [(GSM3384208, True), (:, False), (CMT, False), (-, False), (106, False), (-, False), (tumor, False), (;, False), (Canis, False), (lupus, False), (familiaris, False), (;, False), (RNA, False), (-, False), (Seq, False)]
2026-02-17 01:47:29.710 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=14] [doc 0] Token 0 'b' marked as sentence start (span begin)
2026-02-17 01:47:29.710 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=14] Token/tag mapping: [(b, True), (cell, False), (lymphoma, False), (tumor, False)]
2026-02-17 01:47:29.712 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=15] [doc 0] Token 0 'GSM3262418' marked as sentence start (span begin)
2026-02-17 01:47:29.712 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=15] Token/tag mapping: [(GSM3262418, True), (:, False), (WTRU5.9, False), (_, False), (BAS, False), (;, False), (Rattus, False), (norvegicus, False), (;, False), (RNA, False), (-, False), (Seq, False)]
2026-02-17 01:47:29.713 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=16] [doc 0] Token 0 'retinal' marked as sentence start (span begin)
2026-02-17 01:47:29.713 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=16] Token/tag mapping: [(retinal, True), (cell, False), (culture, False)]
2026-02-17 01:47:29.714 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=17] [doc 0] Token 0 'mammary' marked as sentence start (span begin)
2026-02-17 01:47:29.714 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=17] Token/tag mapping: [(mammary, True), (tumor, False), (tissue, False)]
2026-02-17 01:47:29.715 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=18] [doc 0] Token 0 'rabbit' marked as sentence start (span begin)
2026-02-17 01:47:29.715 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=18] Token/tag mapping: [(rabbit, True), (liver, False), (cancer, False)]
2026-02-17 01:47:29.716 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=19] [doc 0] Token 0 'NextSeq' marked as sentence start (span begin)
2026-02-17 01:47:29.716 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=19] Token/tag mapping: [(NextSeq, True), (500, False), (paired, False), (end, False), (sequencing, False), (of, False), (SAMD00294424, False)]
2026-02-17 01:47:29.717 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=20] [doc 0] Token 0 'nan' marked as sentence start (span begin)
2026-02-17 01:47:29.717 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=20] Token/tag mapping: [(nan, True), (bone, False), (nan, False), (nan, False), (bone, False), (nan, False)]
2026-02-17 01:47:29.718 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=21] [doc 0] Token 0 'RNA' marked as sentence start (span begin)
2026-02-17 01:47:29.718 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=21] Token/tag mapping: [(RNA, True), (-, False), (Seq, False), (of, False), (melanoma, False), (:, False), (adult, False), (oral, False), (mucosal, False), (melanoma, False)]
2026-02-17 01:47:29.719 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=22] [doc 0] Token 0 'GSM3384298' marked as sentence start (span begin)
2026-02-17 01:47:29.720 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=22] Token/tag mapping: [(GSM3384298, True), (:, False), (CMT, False), (-, False), (340, False), (-, False), (normal, False), (;, False), (Canis, False), (lupus, False), (familiaris, False), (;, False), (RNA, False), (-, False), (Seq, False)]
2026-02-17 01:47:29.722 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=23] [doc 0] Token 0 'nan' marked as sentence start (span begin)
2026-02-17 01:47:29.722 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=23] Token/tag mapping: [(nan, True), (abdominal, False), (mass, False), (metastatic, False), (nan, False), (nan, False), (abdominal, False), (mass, False), (metastatic, False), (nan, False)]
2026-02-17 01:47:29.722 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=24] Token/tag mapping: [(bone, False)]
2026-02-17 01:47:29.724 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=25] [doc 0] Token 0 'nan' marked as sentence start (span begin)
2026-02-17 01:47:29.724 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=25] Token/tag mapping: [(nan, True), (mammary, False), (normal, False), (tissue, False), (nan, False), (nan, False), (mammary, False), (normal, False), (tissue, False), (nan, False)]
2026-02-17 01:47:29.725 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=26] [doc 0] Token 0 'RNA' marked as sentence start (span begin)
2026-02-17 01:47:29.726 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=26] Token/tag mapping: [(RNA, True), (-, False), (Seq, False), (of, False), (dog, False), (-, False), (derived, False), (oral, False), (melanoma, False), (tissue, False), (biopsy, False)]
2026-02-17 01:47:29.727 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=27] [doc 0] Token 0 'RNA' marked as sentence start (span begin)
2026-02-17 01:47:29.727 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=27] Token/tag mapping: [(RNA, True), (-, False), (seq, False), (of, False), (canine, False), (DLBCL, False)]
2026-02-17 01:47:29.728 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=28] [doc 0] Token 0 'bladder' marked as sentence start (span begin)
2026-02-17 01:47:29.728 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=28] Token/tag mapping: [(bladder, True), (mucosa, False)]
2026-02-17 01:47:29.729 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=29] [doc 0] Token 0 'NextSeq' marked as sentence start (span begin)
2026-02-17 01:47:29.729 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=29] Token/tag mapping: [(NextSeq, True), (500, False), (paired, False), (end, False), (sequencing, False), (of, False), (SAMD00132301, False)]
2026-02-17 01:47:29.730 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=30] [doc 0] Token 0 'cell' marked as sentence start (span begin)
2026-02-17 01:47:29.730 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=30] Token/tag mapping: [(cell, True), (line, False), (derived, False), (from, False), (canine, False), (defuse, False), (large, False), (b, False), (-, False), (cell, False), (lymphoma, False)]
2026-02-17 01:47:29.731 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=31] [doc 0] Token 0 'hemangiosarcoma' marked as sentence start (span begin)
2026-02-17 01:47:29.731 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=31] Token/tag mapping: [(hemangiosarcoma, True)]
2026-02-17 01:47:29.732 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=32] [doc 0] Token 0 'canine' marked as sentence start (span begin)
2026-02-17 01:47:29.732 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=32] Token/tag mapping: [(canine, True), (mammary, False), (tumor, False), (tissue, False)]
2026-02-17 01:47:29.733 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=33] [doc 0] Token 0 'GSM7678120' marked as sentence start (span begin)
2026-02-17 01:47:29.733 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=33] Token/tag mapping: [(GSM7678120, True), (:, False), (CCB010057, False), (;, False), (Canis, False), (lupus, False), (familiaris, False), (;, False), (RNA, False), (-, False), (Seq, False)]
2026-02-17 01:47:29.735 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=34] [doc 0] Token 0 'GSM8686596' marked as sentence start (span begin)
2026-02-17 01:47:29.736 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=34] Token/tag mapping: [(GSM8686596, True), (:, False), (Control2, False), (_, False), (Boston, False), (;, False), (Canis, False), (lupus, False), (familiaris, False), (;, False), (RNA, False), (-, False), (Seq, False)]
2026-02-17 01:47:29.737 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=35] [doc 0] Token 0 'canine' marked as sentence start (span begin)
2026-02-17 01:47:29.737 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=35] Token/tag mapping: [(canine, True), (oral, False), (melanoma, False)]
2026-02-17 01:47:29.737 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=36] [doc 0] Token 0 'meningioma' marked as sentence start (span begin)
2026-02-17 01:47:29.737 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=36] Token/tag mapping: [(meningioma, True)]
2026-02-17 01:47:29.738 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=37] [doc 0] Token 0 'nan' marked as sentence start (span begin)
2026-02-17 01:47:29.738 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=37] Token/tag mapping: [(nan, True), (liver, False), (nan, False), (nan, False), (liver, False), (nan, False)]
2026-02-17 01:47:29.739 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=38] Token/tag mapping: [(dlbcl, False)]
2026-02-17 01:47:29.740 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=39] [doc 0] Token 0 'GSM7658607' marked as sentence start (span begin)
2026-02-17 01:47:29.740 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=39] Token/tag mapping: [(GSM7658607, True), (:, False), (135, False), (_, False), (0102, False), (_, False), (tumor, False), (;, False), (Canis, False), (lupus, False), (familiaris, False), (;, False), (RNA, False), (-, False), (Seq, False)]
2026-02-17 01:47:29.741 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=40] [doc 0] Token 0 'GSM3070879' marked as sentence start (span begin)
2026-02-17 01:47:29.741 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=40] Token/tag mapping: [(GSM3070879, True), (:, False), (CLBL, False), (-, False), (1, False), (M, False), (rep4, False), (;, False), (Canis, False), (lupus, False), (familiaris, False), (;, False), (RNA, False), (-, False), (Seq, False)]
2026-02-17 01:47:29.743 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=41] [doc 0] Token 0 'GSM6050734' marked as sentence start (span begin)
2026-02-17 01:47:29.743 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=41] Token/tag mapping: [(GSM6050734, True), (:, False), (SI, False), (_, False), (TAM, False), (_, False), (out, False), (_, False), (3, False), (;, False), (Rattus, False), (norvegicus, False), (;, False), (RNA, False), (-, False), (Seq, False)]
2026-02-17 01:47:29.745 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=42] [doc 0] Token 0 'cd45' marked as sentence start (span begin)
2026-02-17 01:47:29.745 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=42] Token/tag mapping: [(cd45, True), (cells, False), (from, False), (tumor, False), (in, False), (nmu, False), (treated, False), (sprague, False), (dawley, False), (rats, False)]
2026-02-17 01:47:29.747 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=43] [doc 0] Token 0 'GSM8686590' marked as sentence start (span begin)
2026-02-17 01:47:29.747 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=43] Token/tag mapping: [(GSM8686590, True), (:, False), (FBD7, False), (;, False), (Canis, False), (lupus, False), (familiaris, False), (;, False), (RNA, False), (-, False), (Seq, False)]
2026-02-17 01:47:29.749 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=44] [doc 0] Token 0 'GSM4314321' marked as sentence start (span begin)
2026-02-17 01:47:29.749 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=44] Token/tag mapping: [(GSM4314321, True), (:, False), (Animal, False), (2, False), (,, False), (tumor, False), (1, False), (,, False), (time, False), (0, False), (;, False), (Equus, False), (caballus, False), (;, False), (RNA, False), (-, False), (Seq, False)]
2026-02-17 01:47:29.750 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=45] [doc 0] Token 0 'cutaneous' marked as sentence start (span begin)
2026-02-17 01:47:29.751 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=45] Token/tag mapping: [(cutaneous, True), (melanoma, False)]
2026-02-17 01:47:29.753 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=46] [doc 0] Token 0 'osteosarcoma' marked as sentence start (span begin)
2026-02-17 01:47:29.753 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=46] Token/tag mapping: [(osteosarcoma, True), (tumor, False), (tisue, False)]
2026-02-17 01:47:29.754 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=47] [doc 0] Token 0 'nan' marked as sentence start (span begin)
2026-02-17 01:47:29.755 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=47] Token/tag mapping: [(nan, True), (kidney, False), (nan, False), (nan, False), (kidney, False), (nan, False)]
2026-02-17 01:47:29.757 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=48] [doc 0] Token 0 'RNA' marked as sentence start (span begin)

In [16]:
# Define label mapping (same as full_data.py)
FINAL_LABEL_MAP = {
    "confident_cancer": "CANCER",
    "likely_cancer": "CANCER",
    "confirmed_by_medspacy": "CANCER",
    "confirmed_non_cancer": "NON_CANCER",
    "likely_non_cancer": "NON_CANCER",
    "uncertain_no_signal": "NON_CANCER",
    "uncertain_weak_signal": "NON_CANCER",
    "uncertain_medspacy": "NON_CANCER",
}

predicted_df = predicted_df.with_columns(
    pl.col("confidence_category").replace(FINAL_LABEL_MAP).alias("final_label")
)

In [17]:
# Re-add the is_cancer column from original excel_data
# is_cancer_series = pl.from_pandas(excel_data['is_cancer'])
is_cancer_series = excel_pl['is_cancer']
predicted_df = predicted_df.with_columns(is_cancer_series.alias("is_cancer"))

## Compare Predictions vs Ground Truth

In [18]:
# Show classification summary
print("=== Classification Summary ===")
summary = (
    predicted_df
    .group_by("final_label")
    .agg(pl.len().alias("count"))
    .sort("count", descending=True)
)
print(summary)

=== Classification Summary ===
shape: (2, 2)
┌─────────────┬───────┐
│ final_label ┆ count │
│ ---         ┆ ---   │
│ str         ┆ u32   │
╞═════════════╪═══════╡
│ CANCER      ┆ 119   │
│ NON_CANCER  ┆ 81    │
└─────────────┴───────┘

In [19]:
# Compare predictions to ground truth
comparison = (
    predicted_df
    .group_by("final_label", "is_cancer")
    .agg(pl.len().alias("count"))
    .sort("final_label", "is_cancer")
)
print("\n=== Predictions vs Ground Truth ===")
print(comparison)

=== Predictions vs Ground Truth ===
shape: (4, 3)
┌─────────────┬───────────┬───────┐
│ final_label ┆ is_cancer ┆ count │
│ ---         ┆ ---       ┆ ---   │
│ str         ┆ i64       ┆ u32   │
╞═════════════╪═══════════╪═══════╡
│ CANCER      ┆ 0         ┆ 5     │
│ CANCER      ┆ 1         ┆ 114   │
│ NON_CANCER  ┆ 0         ┆ 37    │
│ NON_CANCER  ┆ 1         ┆ 44    │
└─────────────┴───────────┴───────┘

In [20]:
# Calculate accuracy for cancer predictions
cancer_predictions = predicted_df.filter(pl.col("final_label") == "CANCER")
if len(cancer_predictions) > 0:
    correct = cancer_predictions.filter(pl.col("is_cancer") == True).height
    total = cancer_predictions.height
    accuracy = correct / total * 100
    print(f"\nCancer prediction accuracy: {accuracy:.1f}% ({correct}/{total})")

# Calculate accuracy for non-cancer predictions
non_cancer_predictions = predicted_df.filter(pl.col("final_label") == "NON_CANCER")
if len(non_cancer_predictions) > 0:
    correct_non = non_cancer_predictions.filter(pl.col("is_cancer") == False).height
    total_non = non_cancer_predictions.height
    accuracy_non = correct_non / total_non * 100
    print(f"Non-cancer prediction accuracy: {accuracy_non:.1f}% ({correct_non}/{total_non})")

Cancer prediction accuracy: 95.8% (114/119)
Non-cancer prediction accuracy: 45.7% (37/81)

In [21]:
# Show false positives (predicted cancer but is_cancer=False)
false_positives = predicted_df.filter(
    (pl.col("final_label") == "CANCER") & (pl.col("is_cancer") == False)
)
print(f"\n=== False Positives ({len(false_positives)}) ===")
if len(false_positives) > 0:
    print(false_positives.select(["title", "tissue", "disease", "source_name", "final_label", "is_cancer"]))

=== False Positives (5) ===
shape: (5, 6)
┌────────────────────┬───────────────────┬──────────────┬────────────────┬─────────────┬───────────┐
│ title              ┆ tissue            ┆ disease      ┆ source_name    ┆ final_label ┆ is_cancer │
│ ---                ┆ ---               ┆ ---          ┆ ---            ┆ ---         ┆ ---       │
│ str                ┆ str               ┆ str          ┆ str            ┆ str         ┆ i64       │
╞════════════════════╪═══════════════════╪══════════════╪════════════════╪═════════════╪═══════════╡
│ RNA-Seq of         ┆ nan oral mucosal  ┆ non melanoma ┆ null           ┆ CANCER      ┆ 0         │
│ melanoma : adult   ┆ control nan n…    ┆              ┆                ┆             ┆           │
│ or…                ┆                   ┆              ┆                ┆             ┆           │
│ RNA-Seq of         ┆ nan oral mucosal  ┆ non melanoma ┆ null           ┆ CANCER      ┆ 0         │
│ melanoma : adult   ┆ control nan n…    ┆              ┆                ┆             ┆           │
│ or…                ┆                   ┆              ┆                ┆             ┆           │
│ GSM6176564:        ┆ null              ┆ Non-tumor    ┆ Mammary tissue ┆ CANCER      ┆ 0         │
│ Adjacent           ┆                   ┆ Tissue       ┆                ┆             ┆           │
│ Non-Tumor…         ┆                   ┆              ┆                ┆             ┆           │
│ GSM5862283: N3;    ┆ Blood             ┆ null         ┆ Non-lymphoma   ┆ CANCER      ┆ 0         │
│ Canis lupus fa…    ┆                   ┆              ┆                ┆             ┆           │
│ RNA-Seq of canine  ┆ tumor             ┆ null         ┆ null           ┆ CANCER      ┆ 0         │
│ mammary tumo…      ┆                   ┆              ┆                ┆             ┆           │
└────────────────────┴───────────────────┴──────────────┴────────────────┴─────────────┴───────────┘

In [22]:
# Show false negatives (predicted non-cancer but is_cancer=True)
false_negatives = predicted_df.filter(
    (pl.col("final_label") == "NON_CANCER") & (pl.col("is_cancer") == True)
)
print(f"\n=== False Negatives ({len(false_negatives)}) ===")
if len(false_negatives) > 0:
    print(false_negatives.select(["title", "tissue", "disease", "source_name", "final_label", "is_cancer"]))

=== False Negatives (44) ===
shape: (44, 6)
┌──────────────────────┬─────────────────────┬─────────┬─────────────────┬─────────────┬───────────┐
│ title                ┆ tissue              ┆ disease ┆ source_name     ┆ final_label ┆ is_cancer │
│ ---                  ┆ ---                 ┆ ---     ┆ ---             ┆ ---         ┆ ---       │
│ str                  ┆ str                 ┆ str     ┆ str             ┆ str         ┆ i64       │
╞══════════════════════╪═════════════════════╪═════════╪═════════════════╪═════════════╪═══════════╡
│ RNA-Seq of canine    ┆ normal              ┆ null    ┆ null            ┆ NON_CANCER  ┆ 1         │
│ mammary matc…        ┆                     ┆         ┆                 ┆             ┆           │
│ NextSeq 500 paired   ┆ null                ┆ null    ┆ null            ┆ NON_CANCER  ┆ 1         │
│ end sequenc…         ┆                     ┆         ┆                 ┆             ┆           │
│ RNA-seq of canine    ┆ DLBCL               ┆ null    ┆ null            ┆ NON_CANCER  ┆ 1         │
│ DLBCL                ┆                     ┆         ┆                 ┆             ┆           │
│ NextSeq 500 paired   ┆ null                ┆ null    ┆ null            ┆ NON_CANCER  ┆ 1         │
│ end sequenc…         ┆                     ┆         ┆                 ┆             ┆           │
│ GSM4042432: 11E;     ┆ null                ┆ null    ┆ mammary         ┆ NON_CANCER  ┆ 1         │
│ Canis lupus f…       ┆                     ┆         ┆ gland_Adenoma   ┆             ┆           │
│ …                    ┆ …                   ┆ …       ┆ …               ┆ …           ┆ …         │
│ GSM7021651: Sham;    ┆ spinal cord cells   ┆ null    ┆ Walker256       ┆ NON_CANCER  ┆ 1         │
│ Rattus norve…        ┆                     ┆         ┆                 ┆             ┆           │
│ GSM8242807: CCM_07;  ┆ nan cCAS nan nan    ┆ null    ┆ cCAS            ┆ NON_CANCER  ┆ 1         │
│ Canis lupu…          ┆ cCAS nan            ┆         ┆                 ┆             ┆           │
│ Illumina NovaSeq     ┆ nan nan nan nan nan ┆ null    ┆ null            ┆ NON_CANCER  ┆ 1         │
│ 6000 sequenci…       ┆ nan                 ┆         ┆                 ┆             ┆           │
│ GSM5720862:          ┆ null                ┆ null    ┆ Metadcarc1511.3 ┆ NON_CANCER  ┆ 1         │
│ 1511-3-1_S5_L003; …  ┆                     ┆         ┆ rep1            ┆             ┆           │
│ GSM5720814:          ┆ null                ┆ null    ┆ Adcarc1508 rep1 ┆ NON_CANCER  ┆ 1         │
│ 1508-1_S1_L003; Ca…  ┆                     ┆         ┆                 ┆             ┆           │
└──────────────────────┴─────────────────────┴─────────┴─────────────────┴─────────────┴───────────┘

In [23]:
# Define columns to export (include med_reason)
export_cols = [
    "title", 
    "tissue", 
    "disease", 
    "source_name", 
    "cancer_type",
    "final_label", 
    "is_cancer",
    "med_label",
    "med_reason",
    "confidence_category",
    "run_accession",
    "bioproject"
]

# Filter to only columns that exist in the dataframe
export_cols = [c for c in export_cols if c in predicted_df.columns]

In [26]:
# Export False Positives to Excel
# (predicted CANCER but actually is_cancer=False)
false_positives = predicted_df.filter(
    (pl.col("final_label") == "CANCER") & (pl.col("is_cancer") == False)
)

if len(false_positives) > 0:
    false_positives.select(export_cols).write_excel("outputs/false_positives.xlsx")
    print(f"✓ Exported {len(false_positives)} false positives to outputs/false_positives.xlsx")
else:
    print("No false positives found")

✓ Exported 5 false positives to outputs/false_positives.xlsx

In [27]:
# Export False Negatives to Excel
# (predicted NON_CANCER but actually is_cancer=True)
false_negatives = predicted_df.filter(
    (pl.col("final_label") == "NON_CANCER") & (pl.col("is_cancer") == True)
)

if len(false_negatives) > 0:
    false_negatives.select(export_cols).write_excel("outputs/false_negatives.xlsx")
    print(f"✓ Exported {len(false_negatives)} false negatives to outputs/false_negatives.xlsx")
else:
    print("No false negatives found")

✓ Exported 44 false negatives to outputs/false_negatives.xlsx

In [28]:
# Display summary
print(f"\n=== Export Summary ===")
print(f"False Positives: {len(false_positives)}")
print(f"False Negatives: {len(false_negatives)}")
print(f"\nColumns exported: {export_cols}")

=== Export Summary ===
False Positives: 5
False Negatives: 44

Columns exported: ['title', 'tissue', 'disease', 'source_name', 'cancer_type', 'final_label', 'is_cancer', 'med_label', 'med_reason', 'confidence_category', 'run_accession', 'bioproject']