In [ ]:
import pandas as pd

## Look at no signal findings

In [ ]:
data = pd.read_csv('outputs/classified_samples.csv')

In [ ]:
no_signal = data[data['med_label'] == "NO_SIGNAL"]

In [ ]:
no_signal.groupby('bioproject')['bioproject'].count()

## Look at non mouse data

In [ ]:
all_data = pd.read_csv('data/combined_metadata_noncancer_removed.csv')

In [ ]:
all_data = all_data.iloc[:,:100]

In [ ]:
exclude = [
    "Mus musculus",
    "Mus musculus domesticus",
    "Mus musculus musculus"
]

non_mouse = all_data[~all_data['organism_scientific_name'].isin(exclude)]

In [ ]:
sample_400 = non_mouse.sample(n=400, random_state=42)

In [ ]:
sample_400

In [ ]:
cols = [
    "title",
    "single-cell/bulk",
    "tissue",
    "disease",
    "experiment_accession",
    "bioproject",
    "biosample",
    "sample_accession",
    "study_accession",
    "library_construction_protocol",
    "source_name",
    "run_accession",
    "cancer_type"
]

filtered_df = sample_400[cols]

In [ ]:
filtered_df

In [ ]:
filtered_df.to_csv("outputs/manual_label_not_mouse_ag.csv", index=False)

In [ ]:
# excel_data_full = pd.read_excel('outputs/manual_label_not_mouse.xlsx')

In [ ]:
# excel_data_raw = excel_data_full.drop("is_cancer")

## Run Classification Pipeline on Manual Label Data

In [1]:
import polars as pl
from functions import (
    classify_cancer_samples,
    initialize_medspacy_pipeline,
    generate_disease_rules,
    get_default_target_rules,
)
from text_column_processing import TextColumnConfig, preprocess_dataframe

In [2]:
# Convert pandas to polars for the pipeline
# excel_pl = pl.from_pandas(excel_data_raw)
# excel_data_full = pl.read_excel("outputs/manual_label_not_mouse.xlsx")

In [3]:
# excel_data_full = pl.read_excel("outputs/manual_label_not_mouse.xlsx")
# excel_data_raw = excel_data_full.drop("is_cancer")

# excel_pl = excel_data_raw

In [4]:
excel_pl = pl.read_excel("outputs/manual_label_not_mouse.xlsx")

Could not determine dtype for column 14, falling back to string

In [5]:
excel_pl=excel_pl.select(excel_pl.columns[:-1])

In [6]:
excel_pl.select(pl.all().exclude("cancer_type"))

shape: (400, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ title     ┆ single-ce ┆ tissue    ┆ disease   ┆ … ┆ library_c ┆ source_na ┆ run_acces ┆ is_cance │
│ ---       ┆ ll/bulk   ┆ ---       ┆ ---       ┆   ┆ onstructi ┆ me        ┆ sion      ┆ r        │
│ str       ┆ ---       ┆ str       ┆ str       ┆   ┆ on_protoc ┆ ---       ┆ ---       ┆ ---      │
│           ┆ str       ┆           ┆           ┆   ┆ ol        ┆ str       ┆ str       ┆ i64      │
│           ┆           ┆           ┆           ┆   ┆ ---       ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ str       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ GSM586011 ┆ bulk      ┆ nan nan   ┆ canine    ┆ … ┆ cells     ┆ cortisol- ┆ SRR178829 ┆ 1        │
│ 7: canine ┆           ┆ nan nan   ┆ cortisol- ┆   ┆ were tryp ┆ secreting ┆ 06        ┆          │
│ cortisol- ┆           ┆ nan nan   ┆ secreting ┆   ┆ sinized   ┆ adrenocor ┆           ┆          │
│ se…       ┆           ┆           ┆ adre…     ┆   ┆ and sto…  ┆ ti…       ┆           ┆          │
│ GSM245375 ┆ bulk      ┆ null      ┆ null      ┆ … ┆ Total RNA ┆ lymphoma  ┆ SRR516842 ┆ 1        │
│ 9: DLYM-1 ┆           ┆           ┆           ┆   ┆ was       ┆           ┆ 8         ┆          │
│ 115_PENN0 ┆           ┆           ┆           ┆   ┆ extracted ┆           ┆           ┆          │
│ 3_v…      ┆           ┆           ┆           ┆   ┆ using …   ┆           ┆           ┆          │
│ RNA-Seq   ┆ bulk      ┆ rabbit    ┆ null      ┆ … ┆ null      ┆ null      ┆ SRR309231 ┆ 1        │
│ of        ┆           ┆ liver     ┆           ┆   ┆           ┆           ┆ 22        ┆          │
│ rabbit:   ┆           ┆ cancer    ┆           ┆   ┆           ┆           ┆           ┆          │
│ male      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ liver …   ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ RNA-Seq   ┆ bulk      ┆ nan oral  ┆ melanoma  ┆ … ┆ null      ┆ null      ┆ SRR152550 ┆ 1        │
│ of        ┆           ┆ mucosal   ┆           ┆   ┆           ┆           ┆ 13        ┆          │
│ melanoma  ┆           ┆ tumor nan ┆           ┆   ┆           ┆           ┆           ┆          │
│ : adult   ┆           ┆ nan…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ or…       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GSM767812 ┆ bulk      ┆ nan osteo ┆ null      ┆ … ┆ Ambion    ┆ osteosarc ┆ SRR255020 ┆ 1        │
│ 0: CCB010 ┆           ┆ sarcoma   ┆           ┆   ┆ miRvana   ┆ oma tumor ┆ 47        ┆          │
│ 057;      ┆           ┆ tumor     ┆           ┆   ┆ kit.      ┆ tisue     ┆           ┆          │
│ Canis l…  ┆           ┆ tisue n…  ┆           ┆   ┆ Illumina  ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ p…        ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ RNA-Seq   ┆ bulk      ┆ nan tumor ┆ null      ┆ … ┆ null      ┆ null      ┆ SRR777961 ┆ null     │
│ of canine ┆           ┆ nan nan   ┆           ┆   ┆           ┆           ┆ 5         ┆          │
│ mammary   ┆           ┆ tumor nan ┆           ┆   ┆           ┆           ┆           ┆          │
│ tumo…     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ RNA-Seq   ┆ bulk      ┆ nan oral  ┆ non       ┆ … ┆ null      ┆ null      ┆ SRR152550 ┆ null     │
│ of        ┆           ┆ mucosal   ┆ melanoma  ┆   ┆           ┆           ┆ 27        ┆          │
│ melanoma  ┆           ┆ control   ┆           ┆   ┆           ┆           ┆           ┆          │
│ : adult   ┆           ┆ nan n…    ┆           ┆   ┆           ┆           ┆           ┆          │
│ or…       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ RNA-Seq   ┆ bulk      ┆ nan oral  ┆ melanoma  ┆ … ┆ null      ┆ null      ┆ SRR152550 ┆ null     │
│ of        ┆           ┆ mucosal   ┆           ┆   ┆           ┆           ┆ 29        ┆          │
│ melanoma  ┆           ┆ tumor nan ┆           ┆   ┆           ┆           ┆           ┆          │
│ : adult   ┆           ┆ nan…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ or…       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GSM399310 ┆ bulk      ┆ null      ┆ null      ┆ … ┆ RNA was   ┆ canine    ┆ SRR987055 ┆ null     │
│ 4: Cancer ┆           ┆           ┆           ┆   ┆ extracted ┆ simple    ┆ 1         ┆          │
│ -associat ┆           ┆           ┆           ┆   ┆ using the ┆ mammary   ┆           ┆          │
│ ed …      ┆           ┆           ┆           ┆   ┆ op…       ┆ carcinom… ┆           ┆          │
│ GSM765860 ┆ bulk      ┆ null      ┆ null      ┆ … ┆ 100 ng to ┆ primary   ┆ SRR254032 ┆ null     │
│ 1: 129_14 ┆           ┆           ┆           ┆   ┆ 1¬µg was  ┆ osteosarc ┆ 57        ┆          │
│ 14_tumor; ┆           ┆           ┆           ┆   ┆ used as   ┆ oma       ┆           ┆          │
│ Ca…       ┆           ┆           ┆           ┆   ┆ inp…      ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [7]:
# Remove cancer_type to prevent it from influencing classification
if "cancer_type" in excel_pl.columns:
    excel_pl = excel_pl.drop("cancer_type")
    print("✓ Removed cancer_type column from analysis")

✓ Removed cancer_type column from analysis

In [8]:
excel_pl

shape: (400, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ title     ┆ single-ce ┆ tissue    ┆ disease   ┆ … ┆ library_c ┆ source_na ┆ run_acces ┆ is_cance │
│ ---       ┆ ll/bulk   ┆ ---       ┆ ---       ┆   ┆ onstructi ┆ me        ┆ sion      ┆ r        │
│ str       ┆ ---       ┆ str       ┆ str       ┆   ┆ on_protoc ┆ ---       ┆ ---       ┆ ---      │
│           ┆ str       ┆           ┆           ┆   ┆ ol        ┆ str       ┆ str       ┆ i64      │
│           ┆           ┆           ┆           ┆   ┆ ---       ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ str       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ GSM586011 ┆ bulk      ┆ nan nan   ┆ canine    ┆ … ┆ cells     ┆ cortisol- ┆ SRR178829 ┆ 1        │
│ 7: canine ┆           ┆ nan nan   ┆ cortisol- ┆   ┆ were tryp ┆ secreting ┆ 06        ┆          │
│ cortisol- ┆           ┆ nan nan   ┆ secreting ┆   ┆ sinized   ┆ adrenocor ┆           ┆          │
│ se…       ┆           ┆           ┆ adre…     ┆   ┆ and sto…  ┆ ti…       ┆           ┆          │
│ GSM245375 ┆ bulk      ┆ null      ┆ null      ┆ … ┆ Total RNA ┆ lymphoma  ┆ SRR516842 ┆ 1        │
│ 9: DLYM-1 ┆           ┆           ┆           ┆   ┆ was       ┆           ┆ 8         ┆          │
│ 115_PENN0 ┆           ┆           ┆           ┆   ┆ extracted ┆           ┆           ┆          │
│ 3_v…      ┆           ┆           ┆           ┆   ┆ using …   ┆           ┆           ┆          │
│ RNA-Seq   ┆ bulk      ┆ rabbit    ┆ null      ┆ … ┆ null      ┆ null      ┆ SRR309231 ┆ 1        │
│ of        ┆           ┆ liver     ┆           ┆   ┆           ┆           ┆ 22        ┆          │
│ rabbit:   ┆           ┆ cancer    ┆           ┆   ┆           ┆           ┆           ┆          │
│ male      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ liver …   ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ RNA-Seq   ┆ bulk      ┆ nan oral  ┆ melanoma  ┆ … ┆ null      ┆ null      ┆ SRR152550 ┆ 1        │
│ of        ┆           ┆ mucosal   ┆           ┆   ┆           ┆           ┆ 13        ┆          │
│ melanoma  ┆           ┆ tumor nan ┆           ┆   ┆           ┆           ┆           ┆          │
│ : adult   ┆           ┆ nan…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ or…       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GSM767812 ┆ bulk      ┆ nan osteo ┆ null      ┆ … ┆ Ambion    ┆ osteosarc ┆ SRR255020 ┆ 1        │
│ 0: CCB010 ┆           ┆ sarcoma   ┆           ┆   ┆ miRvana   ┆ oma tumor ┆ 47        ┆          │
│ 057;      ┆           ┆ tumor     ┆           ┆   ┆ kit.      ┆ tisue     ┆           ┆          │
│ Canis l…  ┆           ┆ tisue n…  ┆           ┆   ┆ Illumina  ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ p…        ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ RNA-Seq   ┆ bulk      ┆ nan tumor ┆ null      ┆ … ┆ null      ┆ null      ┆ SRR777961 ┆ null     │
│ of canine ┆           ┆ nan nan   ┆           ┆   ┆           ┆           ┆ 5         ┆          │
│ mammary   ┆           ┆ tumor nan ┆           ┆   ┆           ┆           ┆           ┆          │
│ tumo…     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ RNA-Seq   ┆ bulk      ┆ nan oral  ┆ non       ┆ … ┆ null      ┆ null      ┆ SRR152550 ┆ null     │
│ of        ┆           ┆ mucosal   ┆ melanoma  ┆   ┆           ┆           ┆ 27        ┆          │
│ melanoma  ┆           ┆ control   ┆           ┆   ┆           ┆           ┆           ┆          │
│ : adult   ┆           ┆ nan n…    ┆           ┆   ┆           ┆           ┆           ┆          │
│ or…       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ RNA-Seq   ┆ bulk      ┆ nan oral  ┆ melanoma  ┆ … ┆ null      ┆ null      ┆ SRR152550 ┆ null     │
│ of        ┆           ┆ mucosal   ┆           ┆   ┆           ┆           ┆ 29        ┆          │
│ melanoma  ┆           ┆ tumor nan ┆           ┆   ┆           ┆           ┆           ┆          │
│ : adult   ┆           ┆ nan…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ or…       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GSM399310 ┆ bulk      ┆ null      ┆ null      ┆ … ┆ RNA was   ┆ canine    ┆ SRR987055 ┆ null     │
│ 4: Cancer ┆           ┆           ┆           ┆   ┆ extracted ┆ simple    ┆ 1         ┆          │
│ -associat ┆           ┆           ┆           ┆   ┆ using the ┆ mammary   ┆           ┆          │
│ ed …      ┆           ┆           ┆           ┆   ┆ op…       ┆ carcinom… ┆           ┆          │
│ GSM765860 ┆ bulk      ┆ null      ┆ null      ┆ … ┆ 100 ng to ┆ primary   ┆ SRR254032 ┆ null     │
│ 1: 129_14 ┆           ┆           ┆           ┆   ┆ 1¬µg was  ┆ osteosarc ┆ 57        ┆          │
│ 14_tumor; ┆           ┆           ┆           ┆   ┆ used as   ┆ oma       ┆           ┆          │
│ Ca…       ┆           ┆           ┆           ┆   ┆ inp…      ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [9]:
# Initialize MedSpaCy pipeline
cancer_rules, non_cancer_rules = get_default_target_rules()
nlp = initialize_medspacy_pipeline(cancer_rules, non_cancer_rules)

# Generate disease-specific rules from the data
unique_diseases = excel_pl.select("disease").drop_nulls().unique().to_series().to_list()
auto_rules, skipped = generate_disease_rules(unique_diseases, nlp, cancer_rules + non_cancer_rules)

if auto_rules:
    tm = nlp.get_pipe("medspacy_target_matcher")
    tm.add(auto_rules)
    print(f"Added {len(auto_rules)} auto-generated disease rules")

Added 18 auto-generated disease rules

In [10]:
# Preprocess text columns
config = TextColumnConfig()
excel_pl, col_tiers = preprocess_dataframe(excel_pl, config=config, include_discovered=False)
print(f"Created {len(col_tiers['normalized'])} normalized columns")

Created 3 normalized columns

In [11]:
excel_pl

shape: (400, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ title     ┆ single-ce ┆ tissue    ┆ disease   ┆ … ┆ is_cancer ┆ source_na ┆ tissue_no ┆ disease_ │
│ ---       ┆ ll/bulk   ┆ ---       ┆ ---       ┆   ┆ ---       ┆ me_norm   ┆ rm        ┆ norm     │
│ str       ┆ ---       ┆ str       ┆ str       ┆   ┆ i64       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ str       ┆           ┆           ┆   ┆           ┆ str       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ GSM586011 ┆ bulk      ┆ nan nan   ┆ canine    ┆ … ┆ 1         ┆ cortisol- ┆ nan nan   ┆ canine   │
│ 7: canine ┆           ┆ nan nan   ┆ cortisol- ┆   ┆           ┆ secreting ┆ nan nan   ┆ cortisol │
│ cortisol- ┆           ┆ nan nan   ┆ secreting ┆   ┆           ┆ adrenocor ┆ nan nan   ┆ -secreti │
│ se…       ┆           ┆           ┆ adre…     ┆   ┆           ┆ ti…       ┆           ┆ ng adre… │
│ GSM245375 ┆ bulk      ┆ null      ┆ null      ┆ … ┆ 1         ┆ lymphoma  ┆           ┆          │
│ 9: DLYM-1 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 115_PENN0 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 3_v…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ RNA-Seq   ┆ bulk      ┆ rabbit    ┆ null      ┆ … ┆ 1         ┆           ┆ rabbit    ┆          │
│ of        ┆           ┆ liver     ┆           ┆   ┆           ┆           ┆ liver     ┆          │
│ rabbit:   ┆           ┆ cancer    ┆           ┆   ┆           ┆           ┆ cancer    ┆          │
│ male      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ liver …   ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ RNA-Seq   ┆ bulk      ┆ nan oral  ┆ melanoma  ┆ … ┆ 1         ┆           ┆ nan oral  ┆ melanoma │
│ of        ┆           ┆ mucosal   ┆           ┆   ┆           ┆           ┆ mucosal   ┆          │
│ melanoma  ┆           ┆ tumor nan ┆           ┆   ┆           ┆           ┆ tumor nan ┆          │
│ : adult   ┆           ┆ nan…      ┆           ┆   ┆           ┆           ┆ nan…      ┆          │
│ or…       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GSM767812 ┆ bulk      ┆ nan osteo ┆ null      ┆ … ┆ 1         ┆ osteosarc ┆ nan osteo ┆          │
│ 0: CCB010 ┆           ┆ sarcoma   ┆           ┆   ┆           ┆ oma tumor ┆ sarcoma   ┆          │
│ 057;      ┆           ┆ tumor     ┆           ┆   ┆           ┆ tisue     ┆ tumor     ┆          │
│ Canis l…  ┆           ┆ tisue n…  ┆           ┆   ┆           ┆           ┆ tisue n…  ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ RNA-Seq   ┆ bulk      ┆ nan tumor ┆ null      ┆ … ┆ null      ┆           ┆ nan tumor ┆          │
│ of canine ┆           ┆ nan nan   ┆           ┆   ┆           ┆           ┆ nan nan   ┆          │
│ mammary   ┆           ┆ tumor nan ┆           ┆   ┆           ┆           ┆ tumor nan ┆          │
│ tumo…     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ RNA-Seq   ┆ bulk      ┆ nan oral  ┆ non       ┆ … ┆ null      ┆           ┆ nan oral  ┆ non      │
│ of        ┆           ┆ mucosal   ┆ melanoma  ┆   ┆           ┆           ┆ mucosal   ┆ melanoma │
│ melanoma  ┆           ┆ control   ┆           ┆   ┆           ┆           ┆ control   ┆          │
│ : adult   ┆           ┆ nan n…    ┆           ┆   ┆           ┆           ┆ nan n…    ┆          │
│ or…       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ RNA-Seq   ┆ bulk      ┆ nan oral  ┆ melanoma  ┆ … ┆ null      ┆           ┆ nan oral  ┆ melanoma │
│ of        ┆           ┆ mucosal   ┆           ┆   ┆           ┆           ┆ mucosal   ┆          │
│ melanoma  ┆           ┆ tumor nan ┆           ┆   ┆           ┆           ┆ tumor nan ┆          │
│ : adult   ┆           ┆ nan…      ┆           ┆   ┆           ┆           ┆ nan…      ┆          │
│ or…       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GSM399310 ┆ bulk      ┆ null      ┆ null      ┆ … ┆ null      ┆ canine    ┆           ┆          │
│ 4: Cancer ┆           ┆           ┆           ┆   ┆           ┆ simple    ┆           ┆          │
│ -associat ┆           ┆           ┆           ┆   ┆           ┆ mammary   ┆           ┆          │
│ ed …      ┆           ┆           ┆           ┆   ┆           ┆ carcinom… ┆           ┆          │
│ GSM765860 ┆ bulk      ┆ null      ┆ null      ┆ … ┆ null      ┆ primary   ┆           ┆          │
│ 1: 129_14 ┆           ┆           ┆           ┆   ┆           ┆ osteosarc ┆           ┆          │
│ 14_tumor; ┆           ┆           ┆           ┆   ┆           ┆ oma       ┆           ┆          │
│ Ca…       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [12]:
# Run classification
predicted_df = classify_cancer_samples(excel_pl, nlp_pipeline=nlp, batch_size=64, use_normalized=True)

2026-03-03 10:16:00.072 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=0] [doc 0] Token 0 'cortisol' marked as sentence start (span begin)
2026-03-03 10:16:00.072 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=0] Token/tag mapping: [(cortisol, True), (-, False), (secreting, False), (adrenocortical, False), (tumor, False)]
2026-03-03 10:16:00.074 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1] [doc 0] Token 0 'nan' marked as sentence start (span begin)
2026-03-03 10:16:00.074 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1] Token/tag mapping: [(nan, True), (nan, False), (nan, False), (nan, False), (nan, False), (nan, False)]
2026-03-03 10:16:00.076 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2] [doc 0] Token 0 'canine' marked as sentence start (span begin)
2026-03-03 10:16:00.076 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2] Token/tag mapping: [(canine, True), (cortisol, False), (-, False), (secreting, False), (adrenocortical, False), (tumor, False)]
2026-03-03 10:16:00.078 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3] [doc 0] Token 0 'cortisol' marked as sentence start (span begin)
2026-03-03 10:16:00.078 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3] Token/tag mapping: [(cortisol, True), (-, False), (secreting, False), (adrenocortical, False), (tumor, False), (nan, False), (nan, False), (nan, False), (nan, False), (nan, False), (nan, False), (canine, False), (cortisol, False), (-, False), (secreting, False), (adrenocortical, False), (tumor, False)]
2026-03-03 10:16:00.079 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=4] [doc 0] Token 0 'lymphoma' marked as sentence start (span begin)
2026-03-03 10:16:00.080 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=4] Token/tag mapping: [(lymphoma, True)]
2026-03-03 10:16:00.080 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=5] [doc 0] Token 0 'lymphoma' marked as sentence start (span begin)
2026-03-03 10:16:00.080 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=5] Token/tag mapping: [(lymphoma, True)]
2026-03-03 10:16:00.081 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=6] [doc 0] Token 0 'rabbit' marked as sentence start (span begin)
2026-03-03 10:16:00.081 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=6] Token/tag mapping: [(rabbit, True), (liver, False), (cancer, False)]
2026-03-03 10:16:00.082 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] [doc 0] Token 0 'rabbit' marked as sentence start (span begin)
2026-03-03 10:16:00.082 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] Token/tag mapping: [(rabbit, True), (liver, False), (cancer, False)]
2026-03-03 10:16:00.084 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=8] [doc 0] Token 0 'nan' marked as sentence start (span begin)
2026-03-03 10:16:00.084 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=8] Token/tag mapping: [(nan, True), (oral, False), (mucosal, False), (tumor, False), (nan, False), (nan, False), (oral, False), (mucosal, False), (tumor, False), (nan, False)]
2026-03-03 10:16:00.085 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=9] [doc 0] Token 0 'melanoma' marked as sentence start (span begin)
2026-03-03 10:16:00.085 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=9] Token/tag mapping: [(melanoma, True)]
2026-03-03 10:16:00.087 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=10] [doc 0] Token 0 'nan' marked as sentence start (span begin)
2026-03-03 10:16:00.087 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=10] Token/tag mapping: [(nan, True), (oral, False), (mucosal, False), (tumor, False), (nan, False), (nan, False), (oral, False), (mucosal, False), (tumor, False), (nan, False), (melanoma, False)]
2026-03-03 10:16:00.088 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=11] [doc 0] Token 0 'osteosarcoma' marked as sentence start (span begin)
2026-03-03 10:16:00.089 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=11] Token/tag mapping: [(osteosarcoma, True), (tumor, False), (tisue, False)]
2026-03-03 10:16:00.090 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=12] [doc 0] Token 0 'nan' marked as sentence start (span begin)
2026-03-03 10:16:00.091 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=12] Token/tag mapping: [(nan, True), (osteosarcoma, False), (tumor, False), (tisue, False), (nan, False), (nan, False), (osteosarcoma, False), (tumor, False), (tisue, False), (nan, False)]
2026-03-03 10:16:00.093 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=13] [doc 0] Token 0 'osteosarcoma' marked as sentence start (span begin)
2026-03-03 10:16:00.093 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=13] Token/tag mapping: [(osteosarcoma, True), (tumor, False), (tisue, False), (nan, False), (osteosarcoma, False), (tumor, False), (tisue, False), (nan, False), (nan, False), (osteosarcoma, False), (tumor, False), (tisue, False), (nan, False)]
2026-03-03 10:16:00.094 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=14] [doc 0] Token 0 'normal' marked as sentence start (span begin)
2026-03-03 10:16:00.095 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=14] Token/tag mapping: [(normal, True)]
2026-03-03 10:16:00.095 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=15] [doc 0] Token 0 'normal' marked as sentence start (span begin)
2026-03-03 10:16:00.096 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=15] Token/tag mapping: [(normal, True)]
2026-03-03 10:16:00.096 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=16] [doc 0] Token 0 'healthy' marked as sentence start (span begin)
2026-03-03 10:16:00.097 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=16] Token/tag mapping: [(healthy, True)]
2026-03-03 10:16:00.097 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=17] [doc 0] Token 0 'healthy' marked as sentence start (span begin)
2026-03-03 10:16:00.097 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=17] Token/tag mapping: [(healthy, True)]
2026-03-03 10:16:00.098 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=18] [doc 0] Token 0 'lymphoma' marked as sentence start (span begin)
2026-03-03 10:16:00.098 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=18] Token/tag mapping: [(lymphoma, True)]
2026-03-03 10:16:00.099 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=19] [doc 0] Token 0 'lymphoma' marked as sentence start (span begin)
2026-03-03 10:16:00.100 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=19] Token/tag mapping: [(lymphoma, True)]
2026-03-03 10:16:00.101 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=20] [doc 0] Token 0 'lymphoma' marked as sentence start (span begin)
2026-03-03 10:16:00.101 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=20] Token/tag mapping: [(lymphoma, True)]
2026-03-03 10:16:00.102 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=21] [doc 0] Token 0 'lymphoma' marked as sentence start (span begin)
2026-03-03 10:16:00.102 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=21] Token/tag mapping: [(lymphoma, True)]
2026-03-03 10:16:00.103 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=22] [doc 0] Token 0 'canine' marked as sentence start (span begin)
2026-03-03 10:16:00.104 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=22] Token/tag mapping: [(canine, True), (mammary, False), (tumor, False), (tissue, False)]
2026-03-03 10:16:00.105 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=23] [doc 0] Token 0 'mammary' marked as sentence start (span begin)
2026-03-03 10:16:00.106 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=23] Token/tag mapping: [(mammary, True), (tumor, False), (tissue, False)]
2026-03-03 10:16:00.108 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=24] [doc 0] Token 0 'canine' marked as sentence start (span begin)
2026-03-03 10:16:00.108 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=24] Token/tag mapping: [(canine, True), (mammary, False), (tumor, False), (tissue, False), (mammary, False), (tumor, False), (tissue, False)]
2026-03-03 10:16:00.110 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=25] [doc 0] Token 0 'nan' marked as sentence start (span begin)
2026-03-03 10:16:00.111 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=25] Token/tag mapping: [(nan, True), (solid, False), (tumor, False), (biopsy, False), (nan, False), (nan, False), (solid, False), (tumor, False), (biopsy, False), (nan, False)]
2026-03-03 10:16:00.112 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=26] [doc 0] Token 0 'canine' marked as sentence start (span begin)
2026-03-03 10:16:00.113 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=26] Token/tag mapping: [(canine, True), (oral, False), (melanoma, False)]
2026-03-03 10:16:00.114 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=27] [doc 0] Token 0 'nan' marked as sentence start (span begin)
2026-03-03 10:16:00.115 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=27] Token/tag mapping: [(nan, True), (solid, False), (tumor, False), (biopsy, False), (nan, False), (nan, False), (solid, False), (tumor, False), (biopsy, False), (nan, False), (canine, False), (oral, False), (melanoma, False)]
2026-03-03 10:16:00.116 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=28] [doc 0] Token 0 'cutaneous' marked as sentence start (span begin)
2026-03-03 10:16:00.116 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=28] Token/tag mapping: [(cutaneous, True), (melanoma, False)]
2026-03-03 10:16:00.117 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=29] [doc 0] Token 0 'cutaneous' marked as sentence start (span begin)
2026-03-03 10:16:00.118 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=29] Token/tag mapping: [(cutaneous, True), (melanoma, False)]
2026-03-03 10:16:00.119 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=31] Token/tag mapping: [(brain, False)]
2026-03-03 10:16:00.119 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=32] Token/tag mapping: [(brain, False)]
2026-03-03 10:16:00.120 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=33] [doc 0] Token 0 'brain' marked as sentence start (span begin)
2026-03-03 10:16:00.120 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=33] Token/tag mapping: [(brain, True), (brain, False)]
2026-03-03 10:16:00.121 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=34] Token/tag mapping: [(dlbcl, False)]
2026-03-03 10:16:00.121 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=35] Token/tag mapping: [(dlbcl, False)]
2026-03-03 10:16:00.123 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=36] [doc 0] Token 0 'nan' marked as sentence start (span begin)
2026-03-03 10:16:00.123 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=36] Token/tag mapping: [(nan, True), (kidney, False), (nan, False), (nan, False), (kidney, False), (nan, False)]
2026-03-03 10:16:00.124 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=37] [doc 0] Token 0 'nan' marked as sentence start (span begin)
2026-03-03 10:16:00.125 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=37] Token/tag mapping: [(nan, True), (kidney, False), (nan, False), (nan, False), (kidney, False), (nan, False)]
2026-03-03 10:16:00.126 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=38] [doc 0] Token 0 'bone' marked as sentence start (span begin)
2026-03-03 10:16:00.126 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=38] Token/tag mapping: [(bone, True), (tumor, False)]
2026-03-03 10:16:00.126 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=39] [doc 0] Token 0 'bone' marked as sentence start (span begin)
2026-03-03 10:16:00.127 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=39] Token/tag mapping: [(bone, True), (tumor, False)]
2026-03-03 10:16:00.128 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=40] [doc 0] Token 0 'bone' marked as sentence start (span begin)
2026-03-03 10:16:00.128 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=40] Token/tag mapping: [(bone, True), (tumor, False), (bone, False), (tumor, False)]
2026-03-03 10:16:00.129 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=41] [doc 0] Token 0 'bladder' marked as sentence start (span begin)
2026-03-03 10:16:00.129 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=41] Token/tag mapping: [(bladder, True), (mucosa, False)]
2026-03-03 10:16:00.129 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=42] [doc 0] Token 0 'bladder' marked as sentence start (span begin)
2026-03-03 10:16:00.130 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=42] Token/tag mapping: [(bladder, True), (mucosa, False)]
2026-03-03 10:16:00.131 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=43] [doc 0] Token 0 'nan' marked as sentence start (span begin)
2026-03-03 10:16:00.131 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=43] Token/tag mapping: [(nan, True), (liver, False), (nan, False), (nan, False), (liver, False), (nan, False)]
2026-03-03 10:16:00.132 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=44] [doc 0] Token 0 'hemangiosarcoma' marked as sentence start (span begin)
2026-03-03 10:16:00.132 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=44] Token/tag mapping: [(hemangiosarcoma, True)]
2026-03-03 10:16:00.133 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=45] [doc 0] Token 0 'nan' marked as sentence start (span begin)
2026-03-03 10:16:00.133 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=45] Token/tag mapping: [(nan, True), (liver, False), (nan, False), (nan, False), (liver, False), (nan, False), (hemangiosarcoma, False)]
2026-03-03 10:16:00.134 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=46] [doc 0] Token 0 'mammary' marked as sentence start (span begin)
2026-03-03 10:16:00.134 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=46] Token/tag mapping: [(mammary, True), (tumor, False), (necrotic, False), (core, False)]
2026-03-03 10:16:00.135 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=47] [doc 0] Token 0 'mammary' marked as sentence start (span begin)
2026-03-03 10:16:00.135 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=47] Token/tag mapping: [(mammary, True), (tumor, False), (necrotic, False), (core, False)]
2026-03-03 10:16:00.136 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=48] [doc 0] Token 0 'canine' marked as sentence start (span begin)
2026-03-03 10:16:00.136 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=48] Token/tag mapping: [(canine, True), (mammary, False), (tumor, False), (tissue, False)]
2026-03-03 10:16:00.137 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=49] [doc 0] Token 0 'mammary' marked as sentence start (span begin)
2026-03-03 10:16:00.137 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=49] Token/tag mapping: [(mammary, True), (tumor, False), (tissue, False)]
2026-03-03 10:16:00.138 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=50] [doc 0] Token 0 'canine' marked as sentence start (span begin)
2026-03-03 10:16:00.139 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=50] Token/tag mapping: [(canine, True), (mammary, False), (tumor, False), (tissue, False), (mammary, False), (tumor, False), (tissue, False)]
2026-03-03 10:16:00.140 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=51] [doc 0] Token 0 'canine' marked as sentence start (span begin)
2026-03-03 10:16:00.140 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=51] Token/tag mapping: [(canine, True), (mammary, False), (normal, False), (tissue, False)]
2026-03-03 10:16:00.141 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=52] [doc 0] Token 0 'mammary' marked as sentence start (span begin)
2026-03-03 10:16:00.141 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=52] Token/tag mapping: [(mammary, True), (normal, False), (tissue, False)]
2026-03-03 10:16:00.142 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=53] [doc 0] Token 0 'canine' marked as sentence start (span begin)
2026-03-03 10:16:00.143 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=53] Token/tag mapping: [(canine, True), (mammary, False), (normal, False), (tissue, False), (mammary, False), (normal, False), (tissue, False)]
2026-03-03 10:16:00.146 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=54] [doc 0] Token 0 'cell' marked as sentence start (span begin)
2026-03-03 10:16:00.147 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=54] Token/tag mapping: [(cell, True), (line, False), (derived, False), (from, False), (canine, False), (b, False), (-, False), (cell, False), (lymphoma, False), (clbl1, False), (xenograft, False), (tumour, False)]
2026-03-03 10:16:00.149 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=55] [doc 0] Token 0 'cell' marked as sentence start (span begin)
2026-03-03 10:16:00.149 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=55] Token/tag mapping: [(cell, True), (line, False), (derived, False), (from, False), (canine, False), (b, False), (-, False), (cell, False), (lymphoma, False), (clbl1, False), (xenograft, False), (tumour, False)]

In [13]:
# Define label mapping (same as full_data.py)
FINAL_LABEL_MAP = {
    "confident_cancer": "CANCER",
    "likely_cancer": "CANCER",
    "confirmed_by_medspacy": "CANCER",
    "confirmed_non_cancer": "NON_CANCER",
    "likely_non_cancer": "NON_CANCER",
    "uncertain_no_signal": "NON_CANCER",
    "uncertain_weak_signal": "NON_CANCER",
    "uncertain_medspacy": "NON_CANCER",
    "NO_SIGNAL": "NON_CANCER"
}

# Use "med_label" instead of "confidence_category"
predicted_df = predicted_df.with_columns(
    pl.col("med_label").replace(FINAL_LABEL_MAP).alias("final_label")
)

In [14]:
# Re-add the is_cancer column from original excel_data
# is_cancer_series = pl.from_pandas(excel_data['is_cancer'])
is_cancer_series = excel_pl['is_cancer']
predicted_df = predicted_df.with_columns(is_cancer_series.alias("is_cancer"))

## Compare Predictions vs Ground Truth

In [15]:
# Show classification summary
print("=== Classification Summary ===")
summary = (
    predicted_df
    .group_by("final_label")
    .agg(pl.len().alias("count"))
    .sort("count", descending=True)
)
print(summary)

=== Classification Summary ===
shape: (2, 2)
┌─────────────┬───────┐
│ final_label ┆ count │
│ ---         ┆ ---   │
│ str         ┆ u32   │
╞═════════════╪═══════╡
│ CANCER      ┆ 207   │
│ NON_CANCER  ┆ 193   │
└─────────────┴───────┘

In [16]:
# Compare predictions to ground truth
comparison = (
    predicted_df
    .group_by("final_label", "is_cancer")
    .agg(pl.len().alias("count"))
    .sort("final_label", "is_cancer")
)
print("\n=== Predictions vs Ground Truth ===")
print(comparison)

=== Predictions vs Ground Truth ===
shape: (6, 3)
┌─────────────┬───────────┬───────┐
│ final_label ┆ is_cancer ┆ count │
│ ---         ┆ ---       ┆ ---   │
│ str         ┆ i64       ┆ u32   │
╞═════════════╪═══════════╪═══════╡
│ CANCER      ┆ null      ┆ 52    │
│ CANCER      ┆ 0         ┆ 2     │
│ CANCER      ┆ 1         ┆ 153   │
│ NON_CANCER  ┆ null      ┆ 48    │
│ NON_CANCER  ┆ 0         ┆ 66    │
│ NON_CANCER  ┆ 1         ┆ 79    │
└─────────────┴───────────┴───────┘

In [17]:
# Calculate accuracy for cancer predictions
cancer_predictions = predicted_df.filter(pl.col("final_label") == "CANCER")
if len(cancer_predictions) > 0:
    correct = cancer_predictions.filter(pl.col("is_cancer") == True).height
    total = cancer_predictions.height
    accuracy = correct / total * 100
    print(f"\nCancer prediction accuracy: {accuracy:.1f}% ({correct}/{total})")

# Calculate accuracy for non-cancer predictions
non_cancer_predictions = predicted_df.filter(pl.col("final_label") == "NON_CANCER")
if len(non_cancer_predictions) > 0:
    correct_non = non_cancer_predictions.filter(pl.col("is_cancer") == False).height
    total_non = non_cancer_predictions.height
    accuracy_non = correct_non / total_non * 100
    print(f"Non-cancer prediction accuracy: {accuracy_non:.1f}% ({correct_non}/{total_non})")

Cancer prediction accuracy: 73.9% (153/207)
Non-cancer prediction accuracy: 34.2% (66/193)

In [18]:
# Show false positives (predicted cancer but is_cancer=False)
false_positives = predicted_df.filter(
    (pl.col("final_label") == "CANCER") & (pl.col("is_cancer") == False)
)
print(f"\n=== False Positives ({len(false_positives)}) ===")
if len(false_positives) > 0:
    print(false_positives.select(["title", "tissue", "disease", "source_name", "final_label", "is_cancer"]))

=== False Positives (2) ===
shape: (2, 6)
┌───────────────────────────┬────────┬──────────────────┬────────────────┬─────────────┬───────────┐
│ title                     ┆ tissue ┆ disease          ┆ source_name    ┆ final_label ┆ is_cancer │
│ ---                       ┆ ---    ┆ ---              ┆ ---            ┆ ---         ┆ ---       │
│ str                       ┆ str    ┆ str              ┆ str            ┆ str         ┆ i64       │
╞═══════════════════════════╪════════╪══════════════════╪════════════════╪═════════════╪═══════════╡
│ GSM6176564: Adjacent      ┆ null   ┆ Non-tumor Tissue ┆ Mammary tissue ┆ CANCER      ┆ 0         │
│ Non-Tumor…                ┆        ┆                  ┆                ┆             ┆           │
│ RNA-Seq of canine mammary ┆ tumor  ┆ null             ┆ null           ┆ CANCER      ┆ 0         │
│ tumo…                     ┆        ┆                  ┆                ┆             ┆           │
└───────────────────────────┴────────┴──────────────────┴────────────────┴─────────────┴───────────┘

In [19]:
# Show false negatives (predicted non-cancer but is_cancer=True)
false_negatives = predicted_df.filter(
    (pl.col("final_label") == "NON_CANCER") & (pl.col("is_cancer") == True)
)
print(f"\n=== False Negatives ({len(false_negatives)}) ===")
if len(false_negatives) > 0:
    print(false_negatives.select(["title", "tissue", "disease", "source_name", "final_label", "is_cancer"]))

=== False Negatives (79) ===
shape: (79, 6)
┌───────────────────┬──────────────────┬──────────────┬──────────────────┬─────────────┬───────────┐
│ title             ┆ tissue           ┆ disease      ┆ source_name      ┆ final_label ┆ is_cancer │
│ ---               ┆ ---              ┆ ---          ┆ ---              ┆ ---         ┆ ---       │
│ str               ┆ str              ┆ str          ┆ str              ┆ str         ┆ i64       │
╞═══════════════════╪══════════════════╪══════════════╪══════════════════╪═════════════╪═══════════╡
│ RNA-Seq of canine ┆ normal           ┆ null         ┆ null             ┆ NON_CANCER  ┆ 1         │
│ mammary matc…     ┆                  ┆              ┆                  ┆             ┆           │
│ 1519_L1_litter179 ┆ cutaneous        ┆ null         ┆ null             ┆ NON_CANCER  ┆ 1         │
│                   ┆ melanoma         ┆              ┆                  ┆             ┆           │
│ NextSeq 500       ┆ null             ┆ null         ┆ null             ┆ NON_CANCER  ┆ 1         │
│ paired end        ┆                  ┆              ┆                  ┆             ┆           │
│ sequenc…          ┆                  ┆              ┆                  ┆             ┆           │
│ RNA-seq of canine ┆ DLBCL            ┆ null         ┆ null             ┆ NON_CANCER  ┆ 1         │
│ DLBCL             ┆                  ┆              ┆                  ┆             ┆           │
│ Canine bladder    ┆ bladder mucosa   ┆ null         ┆ null             ┆ NON_CANCER  ┆ 1         │
│ tumor RNAseq      ┆                  ┆              ┆                  ┆             ┆           │
│ …                 ┆ …                ┆ …            ┆ …                ┆ …           ┆ …         │
│ Illumina NovaSeq  ┆ neoplastic lymph ┆ canine       ┆ null             ┆ NON_CANCER  ┆ 1         │
│ 6000 paired e…    ┆ node             ┆ multicentric ┆                  ┆             ┆           │
│                   ┆                  ┆ high-grade…  ┆                  ┆             ┆           │
│ Transcriptome of  ┆ Horn epithelial  ┆ null         ┆ null             ┆ NON_CANCER  ┆ 1         │
│ Bos indicus:b…    ┆                  ┆              ┆                  ┆             ┆           │
│ Illumina HiSeq    ┆ null             ┆ null         ┆ null             ┆ NON_CANCER  ┆ 1         │
│ 4000 paired end…  ┆                  ┆              ┆                  ┆             ┆           │
│ RNA-seq of canine ┆ lymph node       ┆ null         ┆ null             ┆ NON_CANCER  ┆ 1         │
│ FL                ┆                  ┆              ┆                  ┆             ┆           │
│ GSM4962608:       ┆ null             ┆ null         ┆ Prostate         ┆ NON_CANCER  ┆ 1         │
│ CT1258 cell line  ┆                  ┆              ┆ carcinoma cells  ┆             ┆           │
│ -…                ┆                  ┆              ┆                  ┆             ┆           │
└───────────────────┴──────────────────┴──────────────┴──────────────────┴─────────────┴───────────┘

In [20]:
# Define columns to export (include med_reason)
export_cols = [
    "title", 
    "tissue", 
    "disease", 
    "source_name", 
    "cancer_type",
    "final_label", 
    "is_cancer",
    "med_label",
    "med_reason",
    "confidence_category",
    "run_accession",
    "bioproject"
]

# Filter to only columns that exist in the dataframe
export_cols = [c for c in export_cols if c in predicted_df.columns]

In [21]:
# Export False Positives to Excel
# (predicted CANCER but actually is_cancer=False)
false_positives = predicted_df.filter(
    (pl.col("final_label") == "CANCER") & (pl.col("is_cancer") == False)
)

if len(false_positives) > 0:
    false_positives.select(export_cols).write_excel("outputs/false_positives.xlsx")
    print(f"✓ Exported {len(false_positives)} false positives to outputs/false_positives.xlsx")
else:
    print("No false positives found")

✓ Exported 2 false positives to outputs/false_positives.xlsx

In [22]:
# Export False Negatives to Excel
# (predicted NON_CANCER but actually is_cancer=True)
false_negatives = predicted_df.filter(
    (pl.col("final_label") == "NON_CANCER") & (pl.col("is_cancer") == True)
)

if len(false_negatives) > 0:
    false_negatives.select(export_cols).write_excel("outputs/false_negatives.xlsx")
    print(f"✓ Exported {len(false_negatives)} false negatives to outputs/false_negatives.xlsx")
else:
    print("No false negatives found")

✓ Exported 79 false negatives to outputs/false_negatives.xlsx

In [23]:
all_non_cancer = predicted_df.filter(
    (pl.col("is_cancer") == False)
)

all_cancer_uncertain = predicted_df.filter(
    (pl.col('final_label') == "UNCERTAIN")
)

# all_non_cancer
all_cancer_uncertain

shape: (0, 34)
┌───────┬─────────────┬────────┬─────────┬───┬────────────┬─────────────┬─────────────┬────────────┐
│ title ┆ single-cell ┆ tissue ┆ disease ┆ … ┆ med_reason ┆ med_source_ ┆ confidence_ ┆ final_labe │
│ ---   ┆ /bulk       ┆ ---    ┆ ---     ┆   ┆ ---        ┆ columns     ┆ category    ┆ l          │
│ str   ┆ ---         ┆ str    ┆ str     ┆   ┆ str        ┆ ---         ┆ ---         ┆ ---        │
│       ┆ str         ┆        ┆         ┆   ┆            ┆ str         ┆ str         ┆ str        │
╞═══════╪═════════════╪════════╪═════════╪═══╪════════════╪═════════════╪═════════════╪════════════╡
└───────┴─────────────┴────────┴─────────┴───┴────────────┴─────────────┴─────────────┴────────────┘

In [24]:
    # Calculate all confusion matrix components
true_positives = predicted_df.filter(
    (pl.col("final_label") == "CANCER") & (pl.col("is_cancer") == True)
)
true_negatives = predicted_df.filter(
    (pl.col("final_label") == "NON_CANCER") & (pl.col("is_cancer") == False)
)
false_positives = predicted_df.filter(
    (pl.col("final_label") == "CANCER") & (pl.col("is_cancer") == False)
)
false_negatives = predicted_df.filter(
    (pl.col("final_label") == "NON_CANCER") & (pl.col("is_cancer") == True)
)

tp, tn, fp, fn = len(true_positives), len(true_negatives), len(false_positives), len(false_negatives)

print(f"\n=== Export Summary ===")
print(f"True Positives:  {tp}")
print(f"True Negatives:  {tn}")
print(f"False Positives: {fp}")
print(f"False Negatives: {fn}")

print(f"\n=== Percentages ===")
# TP% = TP / (TP + FN) aka Recall/Sensitivity
print(f"True Positives:  {tp / (tp + fn) * 100:.1f}% (of actual positives)")
# TN% = TN / (TN + FP) aka Specificity
print(f"True Negatives:  {tn / (tn + fp) * 100:.1f}% (of actual negatives)")
# FP% = FP / (FP + TN)
print(f"False Positives: {fp / (fp + tn) * 100:.1f}% (of actual negatives)")
# FN% = FN / (FN + TP)
print(f"False Negatives: {fn / (fn + tp) * 100:.1f}% (of actual positives)")

print(f"\nColumns exported: {export_cols}")

=== Export Summary ===
True Positives:  153
True Negatives:  66
False Positives: 2
False Negatives: 79

=== Percentages ===
True Positives:  65.9% (of actual positives)
True Negatives:  97.1% (of actual negatives)
False Positives: 2.9% (of actual negatives)
False Negatives: 34.1% (of actual positives)

Columns exported: ['title', 'tissue', 'disease', 'source_name', 'final_label', 'is_cancer', 'med_label', 'med_reason', 'confidence_category', 'run_accession', 'bioproject']

In [25]:
# Check what columns we actually have after classification
print("Available columns:", predicted_df.columns)

# Check if med_reason exists and what it contains
if "med_reason" in predicted_df.columns:
    print("\nSample med_reason values:")
    print(predicted_df.select(["med_label", "med_reason"]).head(10))
else:
    print("\n⚠️ med_reason column does NOT exist!")

Available columns: ['title', 'single-cell/bulk', 'tissue', 'disease', 'experiment_accession', 'bioproject', 'biosample', 'sample_accession', 'study_accession', 'library_construction_protocol', 'source_name', 'run_accession', 'is_cancer', 'source_name_norm', 'tissue_norm', 'disease_norm', 'cancer_in_sample_name', 'negative_in_sample_name', 'onco_trap_in_sample_name', 'cancer_in_source_name', 'negative_in_source_name', 'cancer_in_tissue', 'negative_in_tissue', 'cancer_in_disease', 'negative_in_disease', 'n_cancer_mentions', 'n_negative_mentions', 'regex_label', 'regex_reason', 'med_label', 'med_reason', 'med_source_columns', 'confidence_category', 'final_label']

Sample med_reason values:
shape: (10, 2)
┌────────────┬─────────────────────────────────┐
│ med_label  ┆ med_reason                      │
│ ---        ┆ ---                             │
│ str        ┆ str                             │
╞════════════╪═════════════════════════════════╡
│ CANCER     ┆ cancer_terms: canine cortisol-… │
│ CANCER     ┆ cancer_terms: lymphoma | found… │
│ CANCER     ┆ cancer_terms: liver cancer | f… │
│ CANCER     ┆ cancer_terms: melanoma, tumor … │
│ CANCER     ┆ cancer_terms: osteosarcoma, tu… │
│ NON_CANCER ┆ non_cancer_terms: normal | fou… │
│ NON_CANCER ┆ non_cancer_terms: healthy | fo… │
│ CANCER     ┆ cancer_terms: lymphoma | found… │
│ CANCER     ┆ cancer_terms: lymphoma | found… │
│ CANCER     ┆ cancer_terms: tumor | found_in… │
└────────────┴─────────────────────────────────┘

In [ ]:
from pathlib import Path
DATA_PATH = Path("data/combined_metadata_noncancer_removed.csv")

cancer_rules, non_cancer_rules = get_default_target_rules()
existing_rules = cancer_rules + non_cancer_rules

nlp = initialize_medspacy_pipeline(cancer_rules, non_cancer_rules)

if DATA_PATH.exists():
    all_samples = pl.read_csv(
        str(DATA_PATH),
        schema_overrides={"group": pl.Utf8},
        infer_schema_length=0,
    )
    unique_diseases = all_samples.select("disease").unique().to_series().to_list()

    auto_rules, skipped = generate_disease_rules(unique_diseases, nlp, existing_rules)

In [ ]:
for rule in auto_rules:
    print(rule)

## Debugging the Classifier

Right now I'm thinking that the main issue is with tokenization, so we're splitting multiword patterns up in unexpected ways. Still need to investigate further

In [29]:
predicted_df.filter((pl.col('final_label') == 'NON_CANCER') & (pl.col('is_cancer') == True))

shape: (79, 34)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ title     ┆ single-ce ┆ tissue    ┆ disease   ┆ … ┆ med_reaso ┆ med_sourc ┆ confidenc ┆ final_la │
│ ---       ┆ ll/bulk   ┆ ---       ┆ ---       ┆   ┆ n         ┆ e_columns ┆ e_categor ┆ bel      │
│ str       ┆ ---       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ y         ┆ ---      │
│           ┆ str       ┆           ┆           ┆   ┆ str       ┆ str       ┆ ---       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ RNA-Seq   ┆ bulk      ┆ normal    ┆ null      ┆ … ┆ non_cance ┆ tissue    ┆ confirmed ┆ NON_CANC │
│ of canine ┆           ┆           ┆           ┆   ┆ r_terms:  ┆           ┆ _non_canc ┆ ER       │
│ mammary   ┆           ┆           ┆           ┆   ┆ normal |  ┆           ┆ er        ┆          │
│ matc…     ┆           ┆           ┆           ┆   ┆ fou…      ┆           ┆           ┆          │
│ 1519_L1_l ┆ bulk      ┆ cutaneous ┆ null      ┆ … ┆ no_releva ┆           ┆ uncertain ┆ NON_CANC │
│ itter179  ┆           ┆ melanoma  ┆           ┆   ┆ nt_terms  ┆           ┆ _weak_sig ┆ ER       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ nal       ┆          │
│ NextSeq   ┆ bulk      ┆ null      ┆ null      ┆ … ┆ no_releva ┆           ┆ uncertain ┆ NON_CANC │
│ 500       ┆           ┆           ┆           ┆   ┆ nt_terms  ┆           ┆ _no_signa ┆ ER       │
│ paired    ┆           ┆           ┆           ┆   ┆           ┆           ┆ l         ┆          │
│ end       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ sequenc…  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ RNA-seq   ┆ bulk      ┆ DLBCL     ┆ null      ┆ … ┆ no_releva ┆           ┆ uncertain ┆ NON_CANC │
│ of canine ┆           ┆           ┆           ┆   ┆ nt_terms  ┆           ┆ _no_signa ┆ ER       │
│ DLBCL     ┆           ┆           ┆           ┆   ┆           ┆           ┆ l         ┆          │
│ Canine    ┆ bulk      ┆ bladder   ┆ null      ┆ … ┆ no_releva ┆           ┆ likely_ca ┆ NON_CANC │
│ bladder   ┆           ┆ mucosa    ┆           ┆   ┆ nt_terms  ┆           ┆ ncer      ┆ ER       │
│ tumor     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ RNAseq    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ Illumina  ┆ bulk      ┆ neoplasti ┆ canine    ┆ … ┆ no_releva ┆           ┆ uncertain ┆ NON_CANC │
│ NovaSeq   ┆           ┆ c lymph   ┆ multicent ┆   ┆ nt_terms  ┆           ┆ _weak_sig ┆ ER       │
│ 6000      ┆           ┆ node      ┆ ric high- ┆   ┆           ┆           ┆ nal       ┆          │
│ paired e… ┆           ┆           ┆ grade…    ┆   ┆           ┆           ┆           ┆          │
│ Transcrip ┆ bulk      ┆ Horn epit ┆ null      ┆ … ┆ no_releva ┆           ┆ likely_ca ┆ NON_CANC │
│ tome of   ┆           ┆ helial    ┆           ┆   ┆ nt_terms  ┆           ┆ ncer      ┆ ER       │
│ Bos indic ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ us:b…     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Illumina  ┆ bulk      ┆ null      ┆ null      ┆ … ┆ no_releva ┆           ┆ uncertain ┆ NON_CANC │
│ HiSeq     ┆           ┆           ┆           ┆   ┆ nt_terms  ┆           ┆ _no_signa ┆ ER       │
│ 4000      ┆           ┆           ┆           ┆   ┆           ┆           ┆ l         ┆          │
│ paired    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ end…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ RNA-seq   ┆ bulk      ┆ lymph     ┆ null      ┆ … ┆ no_releva ┆           ┆ uncertain ┆ NON_CANC │
│ of canine ┆           ┆ node      ┆           ┆   ┆ nt_terms  ┆           ┆ _no_signa ┆ ER       │
│ FL        ┆           ┆           ┆           ┆   ┆           ┆           ┆ l         ┆          │
│ GSM496260 ┆ bulk      ┆ null      ┆ null      ┆ … ┆ no_releva ┆           ┆ uncertain ┆ NON_CANC │
│ 8: CT1258 ┆           ┆           ┆           ┆   ┆ nt_terms  ┆           ┆ _weak_sig ┆ ER       │
│ cell line ┆           ┆           ┆           ┆   ┆           ┆           ┆ nal       ┆          │
│ -…        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [30]:
# Get false negatives
false_negatives = predicted_df.filter(
    (pl.col('final_label') == 'NON_CANCER') & (pl.col('is_cancer') == True)
)

# Look at a specific example with "cutaneous melanoma"
melanoma_cases = false_negatives.filter(pl.col('tissue').str.contains('melanoma'))

# Show key columns to understand what's happening
melanoma_cases.select([
    'tissue',
    'tissue_norm',  # Check if normalized column exists
    'disease',
    'disease_norm',
    'source_name',
    'source_name_norm',
    'med_label',
    'med_reason',
    'med_source_columns'  # This should show which columns had matches
]).head(5)

shape: (1, 9)
┌────────────┬───────────┬─────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ tissue     ┆ tissue_no ┆ disease ┆ disease_n ┆ … ┆ source_na ┆ med_label ┆ med_reaso ┆ med_sourc │
│ ---        ┆ rm        ┆ ---     ┆ orm       ┆   ┆ me_norm   ┆ ---       ┆ n         ┆ e_columns │
│ str        ┆ ---       ┆ str     ┆ ---       ┆   ┆ ---       ┆ str       ┆ ---       ┆ ---       │
│            ┆ str       ┆         ┆ str       ┆   ┆ str       ┆           ┆ str       ┆ str       │
╞════════════╪═══════════╪═════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ cutaneous  ┆ cutaneous ┆ null    ┆           ┆ … ┆           ┆ NO_SIGNAL ┆ no_releva ┆           │
│ melanoma   ┆ melanoma  ┆         ┆           ┆   ┆           ┆           ┆ nt_terms  ┆           │
└────────────┴───────────┴─────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [33]:
# Find rows where tissue actually contains melanoma
melanoma_rows = false_negatives.filter(pl.col('tissue').str.contains('melanoma', literal=False))

if len(melanoma_rows) > 0:
    example = melanoma_rows[0].to_dicts()[0]

    print(f"tissue (original): {example.get('tissue', 'N/A')}")
    print(f"tissue_norm: {example.get('tissue_norm', 'COLUMN DOES NOT EXIST')}")
    print(f"disease (original): {example.get('disease', 'N/A')}")
    print(f"disease_norm: {example.get('disease_norm', 'COLUMN DOES NOT EXIST')}")
    print(f"\nmed_reason: {example.get('med_reason', 'N/A')}")
    print(f"med_label: {example.get('med_label', 'N/A')}")

    # Most importantly - show what columns exist
    print(f"\nAvailable columns: {melanoma_rows.columns}")
else:
    print("No rows found with 'melanoma' in tissue column")
    print("\nShowing all unique tissue values in false negatives:")
    print(false_negatives.select('tissue').unique())

tissue (original): cutaneous melanoma
tissue_norm: cutaneous melanoma
disease (original): None
disease_norm:

med_reason: no_relevant_terms
med_label: NO_SIGNAL

Available columns: ['title', 'single-cell/bulk', 'tissue', 'disease', 'experiment_accession', 'bioproject', 'biosample', 'sample_accession', 'study_accession', 'library_construction_protocol', 'source_name', 'run_accession', 'is_cancer', 'source_name_norm', 'tissue_norm', 'disease_norm', 'cancer_in_sample_name', 'negative_in_sample_name', 'onco_trap_in_sample_name', 'cancer_in_source_name', 'negative_in_source_name', 'cancer_in_tissue', 'negative_in_tissue', 'cancer_in_disease', 'negative_in_disease', 'n_cancer_mentions', 'n_negative_mentions', 'regex_label', 'regex_reason', 'med_label', 'med_reason', 'med_source_columns', 'confidence_category', 'final_label']

In [34]:
from functions import get_nlp

nlp = get_nlp()

# Test the exact text
test_text = "cutaneous melanoma"
doc = nlp(test_text)

print(f"Text: '{test_text}'")
print(f"Entities found: {[(ent.text, ent.label_) for ent in doc.ents]}")

# Test just "melanoma"
doc2 = nlp("melanoma")
print(f"\nText: 'melanoma'")
print(f"Entities found: {[(ent.text, ent.label_) for ent in doc2.ents]}")

2026-03-04 12:23:14.964 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=991] [doc 0] Token 0 'cutaneous' marked as sentence start (span begin)
2026-03-04 12:23:14.965 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=991] Token/tag mapping: [(cutaneous, True), (melanoma, False)]
2026-03-04 12:23:14.967 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=992] [doc 0] Token 0 'melanoma' marked as sentence start (span begin)
2026-03-04 12:23:14.967 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=992] Token/tag mapping: [(melanoma, True)]

Text: 'cutaneous melanoma'
Entities found: [('melanoma', 'CANCER')]

Text: 'melanoma'
Entities found: [('melanoma', 'CANCER')]